#!/usr/bin/env python3
"""Generate the Chisel frontend opcode decode table from pyCircuit metadata."""

from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
OUT = ROOT / "chisel" / "src" / "main" / "scala" / "linxcore" / "frontend" / "FrontendOpcodeDecodeTable.scala"

sys.path.insert(0, str(SRC))

from common.opcode_meta_gen import OPCODE_META_FORMS  # noqa: E402


DISPATCH = {
    "NONE": 0,
    "D2": 1,
    "ALU": 2,
    "BRU": 3,
    "LSU": 4,
    "CMD": 5,
    "BN": 6,
}

BOUNDARY = {
    "FALL": 0,
    "COND": 1,
    "CALL": 2,
    "RET": 3,
    "DIRECT": 4,
    "IND": 5,
    "ICALL": 6,
}

OPERAND_KIND = {
    "NONE": 0,
    "REG": 1,
}

LOAD_STORE_PAIR_SYMBOLS = {
    "OP_HL_LBP",
    "OP_HL_LHP",
    "OP_HL_LWP",
    "OP_HL_LDP",
    "OP_HL_LBUP",
    "OP_HL_LHUP",
    "OP_HL_LWUP",
    "OP_HL_LBIP",
    "OP_HL_LHIP",
    "OP_HL_LWIP",
    "OP_HL_LDIP",
    "OP_HL_LBUIP",
    "OP_HL_LHUIP",
    "OP_HL_LWUIP",
    "OP_HL_LHIP_U",
    "OP_HL_LWIP_U",
    "OP_HL_LDIP_U",
    "OP_HL_LHUIP_U",
    "OP_HL_LWUIP_U",
    "OP_HL_SBP",
    "OP_HL_SHP",
    "OP_HL_SWP",
    "OP_HL_SDP",
    "OP_HL_SHP_U",
    "OP_HL_SWP_U",
    "OP_HL_SDP_U",
    "OP_HL_SBIP",
    "OP_HL_SHIP",
    "OP_HL_SWIP",
    "OP_HL_SDIP",
    "OP_HL_SHIP_U",
    "OP_HL_SWIP_U",
    "OP_HL_SDIP_U",
}

STORE_PCR_SYMBOLS = {
    "OP_SB_PCR",
    "OP_SH_PCR",
    "OP_SW_PCR",
    "OP_SD_PCR",
}

CACHE_MAINTAIN_PREFIXES = ("OP_BC_", "OP_IC_", "OP_DC_", "OP_TLB_")


def dispatch_code(meta) -> int:
    if meta.major_cat in {"LOAD", "STORE"}:
        return DISPATCH["LSU"]
    if meta.major_cat == "BRU_SETC_CMP":
        return DISPATCH["BRU"]
    if meta.major_cat in {"BLOCK_BOUNDARY", "BLOCK_ARGS_DESC", "CMD_PIPE", "MACRO_TEMPLATE"}:
        return DISPATCH["CMD"]
    if meta.major_cat in {"ALU_INT", "COMPRESSED", "HL_PCR"}:
        return DISPATCH["ALU"]
    return DISPATCH["D2"]


def boundary_code(meta) -> int:
    return BOUNDARY.get(meta.block_kind, BOUNDARY["FALL"])


def is_block_boundary(meta) -> bool:
    return meta.block_kind != "NONE" and meta.block_kind != "STOP"


def is_load_store_pair(meta) -> bool:
    return meta.symbol in LOAD_STORE_PAIR_SYMBOLS


def is_store_pcr(meta) -> bool:
    return meta.symbol in STORE_PCR_SYMBOLS


def cache_maintain_no_split(meta) -> bool:
    return meta.symbol.startswith(CACHE_MAINTAIN_PREFIXES)


def source_len_bytes(meta) -> int:
    if meta.source_file == "insn16.decode":
        return 2
    if meta.source_file == "insn32.decode":
        return 4
    if meta.source_file == "insn48.decode":
        return 6
    if meta.source_file == "insn64.decode":
        return 8
    return 0


def bool_lit(value: bool) -> str:
    return "true" if value else "false"


def main() -> None:
    metas = list(OPCODE_META_FORMS)
    rules = [
        (idx, meta)
        for idx, meta in enumerate(metas)
        if meta.source_file != "internal" and source_len_bytes(meta) != 0
    ]
    rules.sort(key=lambda item: (-int(item[1].mask).bit_count(), item[0]))

    symbols = {}
    for meta in metas:
        symbols.setdefault(meta.symbol, meta.op_id)

    categories = sorted({meta.major_cat for meta in metas})
    category_ids = {name: idx for idx, name in enumerate(categories)}
    imm_kinds = sorted({meta.imm_kind for meta in metas})
    imm_kind_ids = {name: idx for idx, name in enumerate(imm_kinds)}

    lines: list[str] = []
    lines.extend(
        [
            "package linxcore.frontend",
            "",
            "import chisel3._",
            "import linxcore.common.{BoundaryKind, DispatchTarget, InterfaceParams}",
            "",
            "// AUTO-GENERATED by tools/chisel/gen_frontend_decode_table.py.",
            "// Source: src/common/opcode_meta_gen.py.",
            "object FrontendOpcodeDecodeTable {",
            "  final case class Rule(",
            "      symbol: String,",
            "      opcode: Int,",
            "      lenBytes: Int,",
            "      mask: BigInt,",
            "      value: BigInt,",
            "      category: Int,",
            "      dispatch: Int,",
            "      boundary: Int,",
            "      rdKind: Int,",
            "      rs1Kind: Int,",
            "      rs2Kind: Int,",
            "      immKind: Int,",
            "      isLoad: Boolean,",
            "      isStore: Boolean,",
            "      isLoadStorePair: Boolean,",
            "      isStorePcr: Boolean,",
            "      cacheMaintainNoSplit: Boolean,",
            "      isBlockBoundary: Boolean,",
            "      isBlockStop: Boolean)",
            "",
        ]
    )

    for symbol, op_id in sorted(symbols.items(), key=lambda item: item[1]):
        lines.append(f"  val {symbol}: Int = {op_id}")
    lines.append("")
    for name, cat_id in category_ids.items():
        lines.append(f"  val Cat{name}: Int = {cat_id}")
    lines.append("")
    for name, kind_id in OPERAND_KIND.items():
        lines.append(f"  val Operand{name}: Int = {kind_id}")
    lines.append("")
    for name, imm_id in imm_kind_ids.items():
        lines.append(f"  val Imm{name}: Int = {imm_id}")
    lines.extend(
        [
            "",
            f"  val RuleCount: Int = {len(rules)}",
            "",
            "  val Rules: Seq[Rule] = Seq(",
        ]
    )

    for pos, (_, meta) in enumerate(rules):
        comma = "," if pos + 1 < len(rules) else ""
        lines.append(
            "    Rule("
            f"symbol = \"{meta.symbol}\", "
            f"opcode = {meta.op_id}, "
            f"lenBytes = {source_len_bytes(meta)}, "
            f"mask = BigInt(\"{meta.mask:x}\", 16), "
            f"value = BigInt(\"{meta.match:x}\", 16), "
            f"category = Cat{meta.major_cat}, "
            f"dispatch = {dispatch_code(meta)}, "
            f"boundary = {boundary_code(meta)}, "
            f"rdKind = Operand{meta.rd_kind}, "
            f"rs1Kind = Operand{meta.rs1_kind}, "
            f"rs2Kind = Operand{meta.rs2_kind}, "
            f"immKind = Imm{meta.imm_kind}, "
            f"isLoad = {bool_lit(meta.major_cat == 'LOAD')}, "
            f"isStore = {bool_lit(meta.major_cat == 'STORE')}, "
            f"isLoadStorePair = {bool_lit(is_load_store_pair(meta))}, "
            f"isStorePcr = {bool_lit(is_store_pcr(meta))}, "
            f"cacheMaintainNoSplit = {bool_lit(cache_maintain_no_split(meta))}, "
            f"isBlockBoundary = {bool_lit(is_block_boundary(meta))}, "
            f"isBlockStop = {bool_lit(meta.block_kind == 'STOP')}){comma}"
        )

    lines.extend(
        [
            "  )",
            "",
            "  private def dispatchFromCode(code: Int): DispatchTarget.Type = code match {",
            "    case 1 => DispatchTarget.D2",
            "    case 2 => DispatchTarget.Alu",
            "    case 3 => DispatchTarget.Bru",
            "    case 4 => DispatchTarget.Lsu",
            "    case 5 => DispatchTarget.Cmd",
            "    case 6 => DispatchTarget.Bn",
            "    case _ => DispatchTarget.None",
            "  }",
            "",
            "  private def boundaryFromCode(code: Int): BoundaryKind.Type = code match {",
            "    case 1 => BoundaryKind.Cond",
            "    case 2 => BoundaryKind.Call",
            "    case 3 => BoundaryKind.Ret",
            "    case 4 => BoundaryKind.Direct",
            "    case 5 => BoundaryKind.Ind",
            "    case 6 => BoundaryKind.ICall",
            "    case _ => BoundaryKind.Fall",
            "  }",
            "",
            "  def decode(p: InterfaceParams, insn: UInt, lenBytes: UInt): FrontendOpcodeMeta = {",
            "    val meta = Wire(new FrontendOpcodeMeta(p))",
            "    meta := 0.U.asTypeOf(meta)",
            "    meta.dispatchTarget := DispatchTarget.None",
            "    meta.boundaryKind := BoundaryKind.Fall",
            "",
            "    var matched = false.B",
            "    for (rule <- Rules) {",
            "      val hit = !matched &&",
            "        (lenBytes === rule.lenBytes.U) &&",
            "        ((insn & rule.mask.U(p.insnWidth.W)) === rule.value.U(p.insnWidth.W))",
            "      when(hit) {",
            "        meta.valid := true.B",
            "        meta.opcode := rule.opcode.U(p.opcodeWidth.W)",
            "        meta.lenBytes := rule.lenBytes.U(p.lenWidth.W)",
            "        meta.majorCategory := rule.category.U(meta.majorCategory.getWidth.W)",
            "        meta.dispatchTarget := dispatchFromCode(rule.dispatch)",
            "        meta.boundaryKind := boundaryFromCode(rule.boundary)",
            "        meta.rdKind := rule.rdKind.U(meta.rdKind.getWidth.W)",
            "        meta.rs1Kind := rule.rs1Kind.U(meta.rs1Kind.getWidth.W)",
            "        meta.rs2Kind := rule.rs2Kind.U(meta.rs2Kind.getWidth.W)",
            "        meta.immKind := rule.immKind.U(meta.immKind.getWidth.W)",
            "        meta.isLoad := rule.isLoad.B",
            "        meta.isStore := rule.isStore.B",
            "        meta.isLoadStorePair := rule.isLoadStorePair.B",
            "        meta.isStorePcr := rule.isStorePcr.B",
            "        meta.cacheMaintainNoSplit := rule.cacheMaintainNoSplit.B",
            "        meta.isBlockBoundary := rule.isBlockBoundary.B",
            "        meta.isBlockStop := rule.isBlockStop.B",
            "      }",
            "      matched = matched || hit",
            "    }",
            "",
            "    meta",
            "  }",
            "}",
            "",
        ]
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
