#!/usr/bin/env python3
"""Validate frontend fetch/RF/ALU sideband stats reports."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


SCHEMA = "linxcore.frontend_fetch_rf_alu.sideband_stats.v56"

PRESETS = {
    "replay-physical-suppress-selector-origin": {
        "nonzero": (
            "replay_liq.wait_replay_capture_accepted",
            "replay_liq.replay_queue_out_fire",
            "replay_liq.liq_alloc_accepted",
            "replay_liq.lret_w2_slot_accepted",
            "replay_liq.w2_promotion_live",
            "replay_liq.w2_retire_record_physical_bundle_suppress_plan_atomic_suppress_candidate",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_selected",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_selected_from_promotion",
            "replay_liq.w2_retire_record_physical_bundle_suppress_boundary_capture",
            "replay_liq.w2_retire_record_physical_bundle_suppress_ownership_eligible_registered_mask",
            "replay_liq.w2_retire_record_physical_bundle_suppress_live_mask_enabled_candidate",
            "replay_liq.w2_retire_record_physical_bundle_suppress_clear_proof_all_clear_aligned",
        ),
        "zero": (
            "replay_liq.w2_retire_record_physical_bundle_suppress_probe_selected",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_selected_from_probe",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_blocked_by_promote_disabled",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_blocked_by_partial_plan_mask",
            "replay_liq.w2_retire_record_physical_bundle_suppress_select_invalid_probe_promotion_mask_mismatch",
        ),
    },
}

REQUIRED_REPLAY_LIQ_KEYS = [
    "cycles_sampled",
    "load_lookup_valid",
    "load_lookup_execute_granted",
    "load_lookup_execute_with_eligible_store",
    "load_lookup_execute_with_wait_store",
    "execute_load_wait_hold",
    "resident_store_eligible",
    "resident_store_ready_forward",
    "resident_store_wait_blocked",
    "resident_store_wait_store_valid",
    "store_stq_resident",
    "store_stq_addr_ready",
    "store_stq_data_ready",
    "store_stq_addr_ready_not_data_ready",
    "store_stq_addr_and_data_ready",
    "load_lookup_execute_with_addr_ready_not_data_ready",
    "load_lookup_execute_granted_first_cycle",
    "load_lookup_execute_granted_last_cycle",
    "store_stq_addr_ready_not_data_ready_first_cycle",
    "store_stq_addr_ready_not_data_ready_last_cycle",
    "store_stq_addr_and_data_ready_first_cycle",
    "store_stq_addr_and_data_ready_last_cycle",
    "load_lookup_execute_with_addr_ready_not_data_ready_first_cycle",
    "load_lookup_execute_with_addr_ready_not_data_ready_last_cycle",
    "store_sta_dequeue_fire_first_cycle",
    "store_sta_dequeue_fire_last_cycle",
    "store_std_dequeue_fire_first_cycle",
    "store_std_dequeue_fire_last_cycle",
    "store_sta_exec_valid_first_cycle",
    "store_sta_exec_valid_last_cycle",
    "store_std_exec_valid_first_cycle",
    "store_std_exec_valid_last_cycle",
    "store_sta_queue_valid",
    "store_std_queue_valid",
    "store_sta_queue_only_valid",
    "store_sta_dequeue_fire",
    "store_std_dequeue_fire",
    "store_sta_exec_valid",
    "store_std_exec_valid",
    "store_sta_exec_only_valid",
    "resident_store_wake_valid",
    "resident_store_wake_ready",
    "wait_replay_capture_accepted",
    "wait_replay_clear_valid",
    "wait_replay_relaunch_valid",
    "replay_queue_enqueue_accepted",
    "replay_queue_out_valid",
    "replay_queue_out_fire",
    "liq_alloc_valid",
    "liq_alloc_accepted",
    "liq_launch_valid",
    "liq_launch_accepted",
    "liq_return_complete_repick_mask_nonzero",
    "liq_return_complete_source_returned_mask_nonzero",
    "liq_return_complete_data_complete_mask_nonzero",
    "liq_return_complete_request_complete_mask_nonzero",
    "liq_return_complete_candidate_mask_nonzero",
    "liq_return_complete_mask_nonzero",
    "liq_return_complete_valid",
    "liq_return_complete_candidate_count_nonzero",
    "liq_return_complete_valid_w2_occupied",
    "liq_base_lookup_valid",
    "liq_base_lookup_granted",
    "liq_base_data_returned",
    "liq_base_line_valid_mask_nonzero",
    "launch_readiness_candidate_valid",
    "launch_readiness_base_data_ready",
    "launch_readiness_sources_returned",
    "launch_readiness_ready",
    "launch_readiness_enable",
    "launch_readiness_blocked_by_disabled",
    "launch_readiness_blocked_by_no_candidate",
    "launch_readiness_blocked_by_base_lookup",
    "launch_readiness_blocked_by_base_data",
    "launch_readiness_blocked_by_scb",
    "launch_readiness_blocked_by_return",
    "liq_wait_store_mask_nonzero",
    "liq_replay_wake_valid",
    "liq_replay_wake_active",
    "liq_replay_wake_wait_store_candidate",
    "liq_replay_wake_bid_match",
    "liq_replay_wake_lsid_match",
    "liq_replay_wake_pc_match",
    "liq_replay_wake_full_match",
    "liq_replay_wake_store_unit",
    "liq_replay_wake_store_unit_full_match",
    "liq_replay_wake_store_unit_full_match_active",
    "liq_replay_wake_store_unit_full_match_flush_blocked",
    "liq_replay_wake_wait_store_clear",
    "source_return_candidate_valid",
    "source_return_store_snapshot_ready",
    "source_return_store_source_returned",
    "source_return_scb_source_returned",
    "source_return_source_returned",
    "source_return_blocked_by_disabled",
    "source_return_blocked_by_no_candidate",
    "source_return_blocked_by_base_data",
    "source_return_blocked_by_store_snapshot",
    "source_return_blocked_by_scb",
    "source_return_store_snapshot_live_request_active",
    "source_return_store_snapshot_live_evidence_valid",
    "source_return_scb_live_active",
    "source_return_scb_live_request_active",
    "source_return_scb_live_evidence_valid",
    "source_return_scb_live_pending",
    "source_return_scb_live_returned",
    "source_return_scb_live_blocked_by_request_disabled",
    "source_return_scb_live_blocked_by_no_pending",
    "source_return_scb_live_blocked_by_scb_return",
    "source_return_query_issued",
    "source_return_response_apply_valid",
    "source_return_row_state_plan_valid",
    "source_return_candidate_w2_occupied",
    "source_return_store_snapshot_ready_w2_occupied",
    "source_return_query_issued_w2_occupied",
    "source_return_response_apply_w2_occupied",
    "source_row_mutation_candidate_valid",
    "source_row_mutation_live_permit",
    "source_row_mutation_request_valid",
    "source_row_mutation_blocked_by_head_proof",
    "source_row_mutation_blocked_by_live_disabled",
    "source_row_mutation_request_w2_occupied",
    "return_data_candidate_valid",
    "return_data_request_mask_nonzero",
    "return_data_bytes_complete",
    "return_data_cross_line",
    "return_data_size_supported",
    "return_data_valid",
    "return_data_blocked_by_disabled",
    "return_data_blocked_by_no_candidate",
    "return_data_blocked_by_zero_size",
    "return_data_blocked_by_unsupported_size",
    "return_data_blocked_by_cross_line",
    "return_data_blocked_by_incomplete_bytes",
    "return_publish_candidate_valid",
    "return_publish_data_ready",
    "return_publish_ready",
    "return_publish_blocked_by_no_candidate",
    "return_publish_blocked_by_data",
    "return_publish_blocked_by_consumer",
    "return_publish_candidate_w2_occupied",
    "return_publish_ready_w2_occupied",
    "lret_payload_candidate_valid",
    "lret_payload_valid",
    "lret_payload_wakeup_required",
    "lret_payload_blocked_by_no_candidate",
    "lret_payload_blocked_by_data",
    "lret_payload_candidate_w2_occupied",
    "lret_payload_valid_w2_occupied",
    "publish_control_candidate_valid",
    "publish_control_live_enable",
    "publish_control_armed",
    "publish_control_fire",
    "publish_control_blocked_by_no_payload",
    "publish_control_blocked_by_publish",
    "publish_control_blocked_by_side_effects",
    "publish_control_blocked_by_live_disabled",
    "publish_control_candidate_w2_occupied",
    "publish_control_live_enable_w2_occupied",
    "publish_control_armed_w2_occupied",
    "publish_control_fire_w2_occupied",
    "publish_request_valid",
    "publish_request_lret",
    "publish_request_writeback",
    "publish_request_wakeup",
    "publish_request_mask_nonzero",
    "publish_request_blocked_by_no_fire",
    "publish_request_invalid_fire_without_payload",
    "lret_sink_enqueue_ready",
    "lret_sink_enqueue_accepted",
    "lret_sink_enqueue_dropped",
    "lret_sink_drain_valid",
    "lret_sink_drain_fire",
    "lret_sink_pending",
    "lret_sink_full",
    "lret_sink_blocked_by_no_payload",
    "lret_sink_blocked_by_full",
    "lret_sink_blocked_by_drain",
    "lret_sink_enqueue_ready_w2_occupied",
    "lret_sink_enqueue_accepted_w2_occupied",
    "lret_sink_enqueue_dropped_w2_occupied",
    "lret_sink_enqueue_accepted_same_cycle_drain_fire",
    "lret_sink_enqueue_accepted_same_cycle_drain_fire_w2_occupied",
    "lret_sink_enqueue_accepted_w2_without_drain_fire",
    "lret_sink_enqueue_accepted_w2_completion_clear_slot",
    "lret_sink_enqueue_accepted_w2_clear_intent",
    "lret_sink_enqueue_accepted_w2_side_effect_fire_complete",
    "lret_sink_enqueue_accepted_w2_live_clear",
    "lret_sink_followup_after_enqueue_accepted_w2",
    "lret_sink_followup_w2_still_occupied",
    "lret_sink_followup_w2_cleared",
    "lret_sink_followup_after_enqueue_completion_clear_slot",
    "lret_sink_followup_after_enqueue_completion_clear_slot_w2_cleared",
    "lret_sink_followup_after_enqueue_clear_intent",
    "lret_sink_followup_after_enqueue_clear_intent_w2_cleared",
    "lret_sink_followup_after_enqueue_side_effect_fire_complete",
    "lret_sink_followup_after_enqueue_side_effect_fire_complete_w2_cleared",
    "lret_sink_followup_after_enqueue_live_clear",
    "lret_sink_followup_after_enqueue_live_clear_w2_cleared",
    "lret_sink_pending_after_enqueue_accepted_w2",
    "lret_sink_drain_valid_after_enqueue_accepted_w2",
    "lret_sink_drain_fire_after_enqueue_accepted_w2",
    "lret_drain_permit_ready_after_enqueue_accepted_w2",
    "lret_drain_permit_pipe_free_after_enqueue_accepted_w2",
    "lret_drain_permit_pipe_full_after_enqueue_accepted_w2",
    "lret_sink_pending_w2_occupied",
    "lret_sink_drain_valid_w2_occupied",
    "lret_sink_drain_fire_w2_occupied",
    "w2_retire_record_capture_candidate",
    "w2_retire_record_payload_valid",
    "w2_retire_record_capture_valid",
    "w2_retire_record_capture_ready",
    "w2_retire_record_capture_accepted",
    "w2_retire_record_capture_accepted_w2_occupied",
    "w2_retire_record_capture_dropped",
    "w2_retire_record_record_valid",
    "w2_retire_record_record_ready",
    "w2_retire_record_record_fire",
    "w2_retire_record_pending",
    "w2_retire_record_captured_with_lret_enqueue",
    "w2_retire_record_record_from_lret_enqueue",
    "w2_retire_record_blocked_by_invalid_payload",
    "w2_retire_record_blocked_by_full",
    "lret_commit_history_load_rows",
    "lret_shadow_enqueue",
    "lret_shadow_enqueue_after_prior_commit",
    "lret_shadow_drain",
    "lret_shadow_drain_missing",
    "lret_shadow_drain_after_prior_commit",
    "lret_shadow_free_after_prior_commit",
    "lret_drain_permit_any_pipe_free",
    "lret_drain_permit_ready",
    "lret_drain_permit_blocked_by_no_entry",
    "lret_drain_permit_blocked_by_pipe_full",
    "lret_drain_permit_pipe_occupied",
    "lret_iex_data_rob_row_valid",
    "lret_iex_data_rob_row_need_flush",
    "lret_iex_data_rob_row_blocked_by_invalid_rid",
    "lret_iex_data_rob_row_blocked_by_free",
    "lret_iex_data_rob_row_blocked_by_stale_rid",
    "lret_iex_data_candidate_valid",
    "lret_iex_data_would_drain",
    "lret_iex_data_set_mem_data_valid",
    "lret_iex_data_blocked_by_disabled",
    "lret_iex_data_blocked_by_flush",
    "lret_iex_data_blocked_by_no_entry",
    "lret_iex_data_blocked_by_invalid_entry",
    "lret_iex_data_blocked_by_drain",
    "lret_iex_data_blocked_by_rob_missing",
    "lret_iex_data_blocked_by_need_flush",
    "lret_rob_resolve_candidate_valid",
    "lret_rob_resolve_valid",
    "lret_rob_resolve_ready_for_pipe_insert",
    "lret_rob_resolve_mark_all_destinations_data_valid",
    "lret_rob_resolve_mark_destination_data_valid",
    "lret_rob_resolve_ret_lane_increment",
    "lret_rob_resolve_blocked_by_disabled",
    "lret_rob_resolve_blocked_by_flush",
    "lret_rob_resolve_blocked_by_no_set_mem_data",
    "lret_rob_resolve_blocked_by_unsupported_multi_lane",
    "lret_rob_resolve_blocked_by_invalid_rid",
    "lret_rob_resolve_blocked_by_no_destination",
    "lret_lane_completion_candidate_valid",
    "lret_lane_completion_complete_valid",
    "lret_lane_completion_ready_for_pipe_insert",
    "lret_lane_completion_requires_all_lanes",
    "lret_lane_completion_blocked_by_disabled",
    "lret_lane_completion_blocked_by_flush",
    "lret_lane_completion_blocked_by_no_resolve",
    "lret_lane_completion_blocked_by_zero_returned_lanes",
    "lret_lane_completion_blocked_by_invalid_real_req_cnt",
    "lret_lane_completion_blocked_by_scalar_load_pair_incomplete",
    "lret_lane_completion_blocked_by_vector_mem_incomplete",
    "lret_tload_completion_candidate_valid",
    "lret_tload_completion_tload_candidate_valid",
    "lret_tload_completion_tile_scb_send_valid",
    "lret_tload_completion_tile_scb_is_last",
    "lret_tload_completion_complete_valid",
    "lret_tload_completion_ready_for_pipe_insert",
    "lret_tload_completion_blocked_by_disabled",
    "lret_tload_completion_blocked_by_flush",
    "lret_tload_completion_blocked_by_no_lane_completion",
    "lret_tload_completion_blocked_by_invalid_sub_inst_cnt",
    "lret_tload_completion_blocked_by_tload_pending",
    "lret_final_metadata_candidate_valid",
    "lret_final_metadata_is_load_return_marked",
    "lret_final_metadata_load_branch_resolve_called",
    "lret_final_metadata_load_branch_resolve_side_effect_valid",
    "lret_final_metadata_pipe_cycle_sideband_valid",
    "lret_final_metadata_ready_for_pipe_insert",
    "lret_final_metadata_blocked_by_disabled",
    "lret_final_metadata_blocked_by_flush",
    "lret_final_metadata_blocked_by_no_tload_completion",
    "lret_timing_stats_candidate_valid",
    "lret_timing_stats_sideband_valid",
    "lret_timing_stats_iq_name_sideband_valid",
    "lret_timing_stats_ld_rnt_cycle_valid",
    "lret_timing_stats_update_valid",
    "lret_timing_stats_latency_underflow",
    "lret_timing_stats_ready_for_pipe_insert",
    "lret_timing_stats_blocked_by_disabled",
    "lret_timing_stats_blocked_by_flush",
    "lret_timing_stats_blocked_by_no_final_metadata",
    "lret_iex_insert_candidate_valid",
    "lret_iex_insert_valid",
    "lret_iex_insert_is_load_return",
    "lret_iex_insert_wakeup_required",
    "lret_iex_insert_blocked_by_no_set_mem_data",
    "lret_iex_insert_blocked_by_no_pipe",
    "lret_iex_insert_blocked_by_invalid_rid",
    "lret_iex_insert_candidate_w2_occupied",
    "lret_iex_insert_valid_w2_occupied",
    "lret_residency_candidate_valid",
    "lret_residency_write_valid",
    "lret_residency_live_enable",
    "lret_residency_blocked_by_live_disabled",
    "lret_residency_slot_accepted",
    "lret_residency_slot_occupied",
    "lret_residency_advance_candidate_valid",
    "lret_residency_advance_valid",
    "lret_residency_advance_blocked_by_advance_disabled",
    "lret_residency_candidate_w2_occupied",
    "lret_residency_write_w2_occupied",
    "lret_residency_slot_w2_occupied",
    "lret_residency_advance_candidate_w2_occupied",
    "lret_residency_advance_valid_w2_occupied",
    "lret_w1_slot_accepted",
    "lret_w1_slot_occupied",
    "lret_w1_advance_candidate_valid",
    "lret_w1_advance_valid",
    "lret_w1_advance_blocked_by_advance_disabled",
    "lret_w1_slot_w2_occupied",
    "lret_w1_advance_candidate_w2_occupied",
    "lret_w1_advance_valid_w2_occupied",
    "lret_w2_slot_accepted",
    "lret_w2_slot_occupied",
    "lret_w2_slot_blocked_by_no_write",
    "lret_w2_slot_source_trace_valid",
    "w2_atomic_live_active",
    "w2_atomic_request_active",
    "w2_atomic_evidence_valid",
    "w2_atomic_side_effect_live_requested",
    "w2_atomic_promotion_requested",
    "w2_atomic_blocked",
    "w2_atomic_blocked_by_request_disabled",
    "w2_atomic_blocked_by_no_evidence",
    "w2_atomic_blocked_by_mode_disabled",
    "w2_atomic_blocked_by_policy",
    "w2_atomic_blocked_by_no_side_effect_sink",
    "w2_atomic_blocked_by_no_clear_commit",
    "w2_atomic_blocked_by_no_row_fill_candidate",
    "w2_atomic_blocked_by_no_lifecycle_row",
    "w2_atomic_blocked_by_no_required_side_effect",
    "w2_side_effect_candidate_valid",
    "w2_side_effect_ready",
    "w2_side_effect_live_all_required_enabled",
    "w2_side_effect_fire_valid",
    "w2_side_effect_fire_complete",
    "w2_clear_intent",
    "w2_clear_commit_ready",
    "w2_promotion_live",
    "w2_promotion_live_clear",
    "w2_promotion_advance_live",
    "w2_promotion_blocked",
    "w2_promotion_blocked_by_promotion_disabled",
    "w2_promotion_blocked_by_clear_intent",
    "w2_promotion_invalid_clear_without_slot",
    "w2_refill_ready_empty",
    "w2_refill_ready_same_cycle_eligible",
    "w2_refill_ready_same_cycle_ready",
    "w2_refill_ready_future_advance",
    "w2_refill_ready_matches_current",
    "w2_refill_ready_blocked",
    "w2_refill_ready_invalid_live_clear_without_intent",
    "w2_slot_replace_empty_write_eligible",
    "w2_slot_replace_same_cycle_eligible",
    "w2_slot_replace_same_cycle_ready",
    "w2_slot_replace_future_write_accept",
    "w2_slot_replace_matches_current",
    "w2_slot_replace_blocked",
    "w2_slot_replace_blocked_by_current_storage",
    "w2_slot_replace_invalid_future_ready_without_live_clear",
    "w2_slot_replace_overlap_candidate_occupied",
    "w2_slot_replace_overlap_candidate_clear_intent",
    "w2_slot_replace_overlap_candidate_live_clear",
    "w2_slot_replace_overlap_live_clear_same_lsid",
    "w2_slot_replace_overlap_live_clear_different_lsid",
    "w2_slot_replace_overlap_live_clear_unknown_lsid",
    "w2_slot_replace_live_clear_without_w1_candidate",
    "w2_slot_replace_w1_candidate_without_live_clear",
    "w2_slot_replace_advance_valid_on_live_clear",
    "w2_slot_replace_w1_candidate_cycle_before_clear_intent",
    "w2_slot_replace_w1_candidate_cycle_before_live_clear",
    "w2_slot_replace_clear_intent_cycle_before_w1_candidate",
    "w2_slot_replace_live_clear_cycle_before_w1_candidate",
    "w2_slot_replace_live_clear_after_w1_candidate_gap2",
    "w2_slot_replace_live_clear_after_w1_candidate_gap3",
    "w2_slot_replace_live_clear_after_w1_candidate_gap4",
    "w2_slot_replace_live_clear_after_w1_candidate_gap5_plus",
    "w2_slot_replace_w1_candidate_after_live_clear_gap2",
    "w2_slot_replace_w1_candidate_after_live_clear_gap3",
    "w2_slot_replace_w1_candidate_after_live_clear_gap4",
    "w2_slot_replace_w1_candidate_after_live_clear_gap5_plus",
    "w2_slot_replace_different_lsid_live_clear_after_w1_candidate_gap2",
    "w2_slot_replace_different_lsid_live_clear_after_w1_candidate_gap3",
    "w2_slot_replace_different_lsid_live_clear_after_w1_candidate_gap4",
    "w2_slot_replace_different_lsid_live_clear_after_w1_candidate_gap5_plus",
    "w2_slot_replace_different_lsid_w1_candidate_after_live_clear_gap2",
    "w2_slot_replace_different_lsid_w1_candidate_after_live_clear_gap3",
    "w2_slot_replace_different_lsid_w1_candidate_after_live_clear_gap4",
    "w2_slot_replace_different_lsid_w1_candidate_after_live_clear_gap5_plus",
    "w2_slot_replace_live_clear_after_w1_candidate_same_lsid",
    "w2_slot_replace_live_clear_after_w1_candidate_different_lsid",
    "w2_slot_replace_live_clear_after_w1_candidate_unknown_lsid",
    "w2_advance_enable",
    "w2_advance_replace_on_clear",
    "w2_advance_uses_future_advance",
    "w2_advance_blocked",
    "w2_advance_blocked_by_live_promotion_disabled",
    "w2_advance_invalid_future_write_without_advance",
    "w2_commit_row_trace_source_ready",
    "w2_commit_row_trace_source_instruction_ready",
    "w2_commit_row_trace_source_source_ready",
    "w2_commit_row_trace_source_blocked",
    "w2_commit_row_trace_source_blocked_by_no_metadata",
    "w2_commit_row_trace_source_blocked_by_no_source_trace",
    "w2_commit_row_trace_source_rob_lookup_row_valid",
    "w2_commit_row_trace_source_rob_lookup_instruction_valid",
    "w2_commit_row_trace_source_rob_lookup_blocked_by_need_flush",
    "w2_commit_row_trace_source_rob_lookup_blocked_by_missing_instruction",
    "w2_commit_row_trace_source_rob_lookup_blocked_by_source_trace_disabled",
    "w2_commit_row_trace_source_rob_lookup_blocked_by_source_trace_before_completion",
    "w2_commit_row_candidate_valid",
    "w2_commit_row_fill_candidate",
    "w2_commit_row_complete_candidate",
    "w2_commit_row_candidate_blocked",
    "w2_commit_row_candidate_blocked_by_no_metadata",
    "w2_commit_row_candidate_blocked_by_no_source_trace",
    "w2_commit_row_candidate_blocked_by_invalid_size",
    "w2_commit_row_candidate_blocked_by_non_gpr_destination",
    "w2_commit_row_candidate_blocked_by_row_fill_disabled",
    "w2_retire_record_commit_row_candidate_valid",
    "w2_retire_record_commit_row_fill_candidate",
    "w2_retire_record_commit_row_complete_candidate",
    "w2_retire_record_commit_row_candidate_blocked",
    "w2_retire_record_commit_row_candidate_blocked_by_no_record",
    "w2_retire_record_commit_row_candidate_blocked_by_no_metadata",
    "w2_retire_record_commit_row_candidate_blocked_by_no_source_trace",
    "w2_retire_record_commit_row_candidate_blocked_by_invalid_size",
    "w2_retire_record_commit_row_candidate_blocked_by_non_gpr_destination",
    "w2_retire_record_commit_row_candidate_blocked_by_row_fill_disabled",
    "w2_retire_record_instruction_metadata_capture_intent",
    "w2_retire_record_instruction_metadata_capture_payload_rid_valid",
    "w2_retire_record_instruction_metadata_w2_rid_valid",
    "w2_retire_record_instruction_metadata_w2_rid_matches_capture",
    "w2_retire_record_instruction_metadata_w2_metadata_ready",
    "w2_retire_record_instruction_metadata_capture_from_w2",
    "w2_retire_record_instruction_metadata_capture_from_drain",
    "w2_retire_record_instruction_metadata_capture_blocked_by_no_payload_rid",
    "w2_retire_record_instruction_metadata_capture_blocked_by_no_w2_rid",
    "w2_retire_record_instruction_metadata_capture_blocked_by_rid_mismatch",
    "w2_retire_record_instruction_metadata_capture_blocked_by_no_w2_metadata",
    "w2_retire_record_instruction_metadata_clear_accepted",
    "w2_retire_record_instruction_metadata_provider_valid",
    "w2_row_fill_candidate_valid",
    "w2_row_fill_prerequisites_ready",
    "w2_row_fill_enable",
    "w2_row_fill_blocked_by_request_disabled",
    "w2_row_fill_blocked_by_no_candidate",
    "w2_row_fill_blocked_by_no_side_effect_commit",
    "w2_row_fill_blocked_by_no_clear_commit",
    "w2_row_fill_blocked_by_live_clear_disabled",
    "w2_row_fill_blocked_by_no_replay_row_lifecycle",
    "w2_lifecycle_candidate_valid",
    "w2_lifecycle_slot_identity_valid",
    "w2_lifecycle_resolved_row_match",
    "w2_lifecycle_row_clear_ready",
    "w2_lifecycle_ready",
    "w2_lifecycle_blocked_by_no_resolved_row",
    "w2_lifecycle_blocked_by_multiple_resolved_rows",
    "w2_lifecycle_blocked_by_clear_disabled",
    "w2_lifecycle_clear_request_enable",
    "w2_lifecycle_clear_commit_enable",
    "w2_retire_record_lifecycle_candidate_valid",
    "w2_retire_record_lifecycle_slot_identity_valid",
    "w2_retire_record_lifecycle_resolved_row_match",
    "w2_retire_record_lifecycle_row_clear_ready",
    "w2_retire_record_lifecycle_blocked_by_no_resolved_row",
    "w2_retire_record_lifecycle_blocked_by_multiple_resolved_rows",
    "w2_retire_record_lifecycle_blocked_by_clear_disabled",
    "w2_retire_record_lifecycle_request_candidate",
    "w2_retire_record_lifecycle_live_promotion_candidate",
    "w2_retire_record_lifecycle_request_blocked_by_no_lifecycle_row",
    "w2_retire_record_lifecycle_request_blocked_by_no_atomic_request",
    "w2_retire_record_lifecycle_request_blocked_by_no_row_fill_candidate",
    "w2_retire_record_lifecycle_request_blocked_by_no_row_fill_enable",
    "w2_retire_record_atomic_request_evidence_valid",
    "w2_retire_record_atomic_request_row_fill_candidate_aligned",
    "w2_retire_record_atomic_request_row_fill_enable_aligned",
    "w2_retire_record_atomic_request_blocked_by_no_lifecycle_row",
    "w2_retire_record_atomic_request_blocked_by_no_row_fill_candidate",
    "w2_retire_record_atomic_request_blocked_by_no_row_fill_enable",
    "w2_retire_record_row_fill_enable_request_evidence_valid",
    "w2_retire_record_row_fill_enable_candidate_aligned",
    "w2_retire_record_row_fill_enable",
    "w2_retire_record_row_fill_enable_blocked_by_request_disabled",
    "w2_retire_record_row_fill_enable_blocked_by_no_lifecycle_row",
    "w2_retire_record_row_fill_enable_blocked_by_no_row_fill_candidate",
    "w2_retire_record_lifecycle_evidence_capture_intent",
    "w2_retire_record_lifecycle_evidence_capture_from_lifecycle",
    "w2_retire_record_lifecycle_evidence_capture_blocked_by_no_lifecycle",
    "w2_retire_record_lifecycle_evidence_clear_accepted",
    "w2_retire_record_lifecycle_evidence_provider_valid",
    "w2_retire_record_lifecycle_evidence_provider_valid_without_record",
    "w2_retire_record_lifecycle_evidence_record_valid_without_provider",
    "w2_retire_record_lifecycle_clear_fallback_capture_physical_clear",
    "w2_retire_record_lifecycle_clear_fallback_candidate",
    "w2_retire_record_lifecycle_clear_fallback_duplicate_physical_clear",
    "w2_retire_record_lifecycle_clear_fallback_clear_valid",
    "w2_retire_record_rob_fallback_capture_physical_complete",
    "w2_retire_record_rob_fallback_candidate",
    "w2_retire_record_rob_fallback_duplicate_physical_complete",
    "w2_retire_record_rob_fallback_complete_valid",
    "w2_retire_record_rf_fallback_capture_physical_writeback",
    "w2_retire_record_rf_fallback_candidate",
    "w2_retire_record_rf_fallback_duplicate_physical_writeback",
    "w2_retire_record_rf_fallback_writeback_valid",
    "w2_retire_record_wakeup_fallback_capture_physical_wakeup",
    "w2_retire_record_wakeup_fallback_candidate",
    "w2_retire_record_wakeup_fallback_duplicate_physical_wakeup",
    "w2_retire_record_wakeup_fallback_wakeup_valid",
    "w2_retire_record_fallback_owner_policy_candidate",
    "w2_retire_record_fallback_owner_policy_all_candidates_ready",
    "w2_retire_record_fallback_owner_policy_blocked_by_physical_duplicate",
    "w2_retire_record_fallback_owner_policy_no_physical_probe_active",
    "w2_retire_record_fallback_owner_policy_fallback_emit_probe_active",
    "w2_retire_record_fallback_owner_policy_fallback_live_probe_active",
    "w2_retire_record_fallback_owner_policy_retained_sole_owner_eligible",
    "w2_retire_record_fallback_owner_policy_blocked_by_global_fallback_disabled",
    "w2_retire_record_fallback_owner_policy_side_effect_enable",
    "w2_retire_record_rob_fallback_live_complete_selected",
    "w2_retire_record_rf_fallback_live_writeback_selected",
    "w2_retire_record_wakeup_fallback_live_wakeup_selected",
    "w2_retire_record_lifecycle_clear_fallback_live_clear_selected",
    "w2_retire_record_model_order_record_candidate",
    "w2_retire_record_model_order_return_side_effects_ready",
    "w2_retire_record_model_order_retire_clear_evidence_ready",
    "w2_retire_record_model_order_return_then_retire_ready",
    "w2_retire_record_model_order_fallback_owner_eligible",
    "w2_retire_record_model_order_blocked_by_missing_return_side_effect",
    "w2_retire_record_model_order_blocked_by_missing_retire_clear_evidence",
    "w2_retire_record_model_order_blocked_by_owner_disabled",
    "w2_retire_record_default_promotion_record_candidate",
    "w2_retire_record_default_promotion_pre_arm_model_order_ready",
    "w2_retire_record_default_promotion_any_physical_duplicate",
    "w2_retire_record_default_promotion_ready",
    "w2_retire_record_default_promotion_blocked_by_no_record",
    "w2_retire_record_default_promotion_blocked_by_missing_fallback_candidate",
    "w2_retire_record_default_promotion_blocked_by_missing_lifecycle_evidence",
    "w2_retire_record_default_promotion_blocked_by_physical_duplicate",
    "w2_retire_record_default_promotion_blocked_by_probe_active",
    "w2_retire_record_duplicate_vector_valid",
    "w2_retire_record_duplicate_vector_return_side_effect_bundle",
    "w2_retire_record_duplicate_vector_model_order_bundle",
    "w2_retire_record_duplicate_vector_partial",
    "w2_retire_record_duplicate_vector_single",
    "w2_retire_record_duplicate_vector_multi",
    "w2_retire_record_duplicate_vector_count_sum",
    "w2_retire_record_duplicate_vector_next_requires_bundle_transfer",
    "w2_retire_record_duplicate_vector_blocked_by_no_record",
    "w2_retire_record_duplicate_vector_blocked_by_pre_arm_not_ready",
    "w2_retire_record_duplicate_vector_blocked_by_no_duplicate",
    "w2_retire_record_bundle_transfer_plan_candidate",
    "w2_retire_record_bundle_transfer_plan_pre_arm_ready",
    "w2_retire_record_bundle_transfer_plan_model_order_bundle",
    "w2_retire_record_bundle_transfer_plan_default_transfer_candidate",
    "w2_retire_record_bundle_transfer_plan_requires_physical_bundle_suppression",
    "w2_retire_record_bundle_transfer_plan_default_promotion_already_ready",
    "w2_retire_record_bundle_transfer_plan_blocked_by_no_record",
    "w2_retire_record_bundle_transfer_plan_blocked_by_pre_arm_not_ready",
    "w2_retire_record_bundle_transfer_plan_blocked_by_no_duplicate_vector",
    "w2_retire_record_bundle_transfer_plan_blocked_by_partial_duplicate",
    "w2_retire_record_bundle_transfer_plan_blocked_by_probe_active",
    "w2_retire_record_physical_bundle_suppress_plan_transfer_candidate",
    "w2_retire_record_physical_bundle_suppress_plan_suppression_required",
    "w2_retire_record_physical_bundle_suppress_plan_physical_bundle_complete",
    "w2_retire_record_physical_bundle_suppress_plan_atomic_suppress_candidate",
    "w2_retire_record_physical_bundle_suppress_plan_suppress_rob_complete",
    "w2_retire_record_physical_bundle_suppress_plan_suppress_rf_writeback",
    "w2_retire_record_physical_bundle_suppress_plan_suppress_wakeup",
    "w2_retire_record_physical_bundle_suppress_plan_suppress_lifecycle_clear",
    "w2_retire_record_physical_bundle_suppress_plan_suppress_mask_sum",
    "w2_retire_record_physical_bundle_suppress_plan_all_or_none_suppress",
    "w2_retire_record_physical_bundle_suppress_plan_blocked_by_no_transfer_candidate",
    "w2_retire_record_physical_bundle_suppress_plan_blocked_by_no_suppression_requirement",
    "w2_retire_record_physical_bundle_suppress_plan_blocked_by_incomplete_physical_bundle",
    "w2_retire_record_physical_bundle_suppress_probe_candidate",
    "w2_retire_record_physical_bundle_suppress_probe_enabled_candidate",
    "w2_retire_record_physical_bundle_suppress_probe_selected",
    "w2_retire_record_physical_bundle_suppress_probe_selected_mask_sum",
    "w2_retire_record_physical_bundle_suppress_probe_all_or_none_input_mask",
    "w2_retire_record_physical_bundle_suppress_probe_blocked_by_probe_disabled",
    "w2_retire_record_physical_bundle_suppress_probe_blocked_by_no_atomic_candidate",
    "w2_retire_record_physical_bundle_suppress_probe_blocked_by_partial_mask",
    "w2_retire_record_physical_bundle_suppress_select_plan_promoted_candidate",
    "w2_retire_record_physical_bundle_suppress_select_selected",
    "w2_retire_record_physical_bundle_suppress_select_selected_mask_sum",
    "w2_retire_record_physical_bundle_suppress_select_all_or_none_input_mask",
    "w2_retire_record_physical_bundle_suppress_select_selected_from_probe",
    "w2_retire_record_physical_bundle_suppress_select_selected_from_promotion",
    "w2_retire_record_physical_bundle_suppress_select_blocked_by_promote_disabled",
    "w2_retire_record_physical_bundle_suppress_select_blocked_by_no_plan_candidate",
    "w2_retire_record_physical_bundle_suppress_select_blocked_by_partial_plan_mask",
    "w2_retire_record_physical_bundle_suppress_select_invalid_probe_promotion_mask_mismatch",
    "w2_retire_record_physical_bundle_suppress_boundary_capture",
    "w2_retire_record_physical_bundle_suppress_boundary_registered_valid",
    "w2_retire_record_physical_bundle_suppress_boundary_registered_mask_sum",
    "w2_retire_record_physical_bundle_suppress_boundary_registered_full_mask",
    "w2_retire_record_physical_bundle_suppress_boundary_blocked_by_no_selection",
    "w2_retire_record_physical_bundle_suppress_boundary_blocked_by_partial_mask",
    "w2_retire_record_physical_bundle_suppress_boundary_cleared_by_flush",
    "w2_retire_record_physical_bundle_suppress_identity_capture_identity",
    "w2_retire_record_physical_bundle_suppress_identity_captured_identity_valid",
    "w2_retire_record_physical_bundle_suppress_identity_registered_candidate",
    "w2_retire_record_physical_bundle_suppress_identity_retained_record_aligned",
    "w2_retire_record_physical_bundle_suppress_identity_lifecycle_row_aligned",
    "w2_retire_record_physical_bundle_suppress_identity_lifetime_aligned",
    "w2_retire_record_physical_bundle_suppress_identity_eligible_registered_mask",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_no_captured_identity",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_missing_record",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_rid_mismatch",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_load_lsid_mismatch",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_missing_lifecycle_evidence",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_lifecycle_row_mismatch",
    "w2_retire_record_physical_bundle_suppress_identity_blocked_by_not_full_mask",
    "w2_retire_record_physical_bundle_suppress_ownership_capture_ownership",
    "w2_retire_record_physical_bundle_suppress_ownership_captured_ownership_valid",
    "w2_retire_record_physical_bundle_suppress_ownership_registered_candidate",
    "w2_retire_record_physical_bundle_suppress_ownership_registered_rid_valid",
    "w2_retire_record_physical_bundle_suppress_ownership_registered_load_lsid_valid",
    "w2_retire_record_physical_bundle_suppress_ownership_registered_lifecycle_row_ready",
    "w2_retire_record_physical_bundle_suppress_ownership_registered_bundle_ready",
    "w2_retire_record_physical_bundle_suppress_ownership_eligible_registered_mask",
    "w2_retire_record_physical_bundle_suppress_ownership_blocked_by_no_captured_ownership",
    "w2_retire_record_physical_bundle_suppress_ownership_blocked_by_missing_rid",
    "w2_retire_record_physical_bundle_suppress_ownership_blocked_by_missing_load_lsid",
    "w2_retire_record_physical_bundle_suppress_ownership_blocked_by_missing_lifecycle_row",
    "w2_retire_record_physical_bundle_suppress_ownership_blocked_by_not_full_mask",
    "w2_retire_record_physical_bundle_suppress_live_mask_candidate",
    "w2_retire_record_physical_bundle_suppress_live_mask_enabled_candidate",
    "w2_retire_record_physical_bundle_suppress_live_mask_suppress_rob_complete",
    "w2_retire_record_physical_bundle_suppress_live_mask_suppress_rf_writeback",
    "w2_retire_record_physical_bundle_suppress_live_mask_suppress_wakeup",
    "w2_retire_record_physical_bundle_suppress_live_mask_suppress_lifecycle_clear",
    "w2_retire_record_physical_bundle_suppress_live_mask_suppress_mask_sum",
    "w2_retire_record_physical_bundle_suppress_live_mask_all_or_none",
    "w2_retire_record_physical_bundle_suppress_live_mask_blocked_by_live_mask_disabled",
    "w2_retire_record_physical_bundle_suppress_live_mask_blocked_by_no_eligible_ownership",
    "w2_retire_record_physical_bundle_suppress_clear_proof_candidate",
    "w2_retire_record_physical_bundle_suppress_clear_proof_full_mask",
    "w2_retire_record_physical_bundle_suppress_clear_proof_fire_complete_aligned",
    "w2_retire_record_physical_bundle_suppress_clear_proof_clear_intent_aligned",
    "w2_retire_record_physical_bundle_suppress_clear_proof_live_clear_aligned",
    "w2_retire_record_physical_bundle_suppress_clear_proof_row_fill_aligned",
    "w2_retire_record_physical_bundle_suppress_clear_proof_lifecycle_clear_suppressed",
    "w2_retire_record_physical_bundle_suppress_clear_proof_all_clear_aligned",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_partial_mask",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_no_fire_complete",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_no_clear_intent",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_no_live_clear",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_no_row_fill",
    "w2_retire_record_physical_bundle_suppress_clear_proof_blocked_by_lifecycle_clear_still_enabled",
    "resolve_queue_push_accepted",
    "resolve_queue_valid",
    "resolve_queue_push_accepted_first_cycle",
    "resolve_queue_push_accepted_last_cycle",
    "resolve_queue_valid_first_cycle",
    "resolve_queue_valid_last_cycle",
    "mdb_conflict_store_valid",
    "mdb_conflict_store_valid_first_cycle",
    "mdb_conflict_store_valid_last_cycle",
    "mdb_conflict_store_with_resolve_queue_valid",
    "mdb_conflict_store_with_resolve_queue_valid_first_cycle",
    "mdb_conflict_store_with_resolve_queue_valid_last_cycle",
    "mdb_conflict_store_without_resolve_queue_valid",
    "mdb_conflict_active_candidate",
    "mdb_conflict_resolve_candidate",
    "mdb_conflict_resolve_candidate_first_cycle",
    "mdb_conflict_resolve_candidate_last_cycle",
    "mdb_conflict_valid",
    "mdb_fanout_record_valid",
    "mdb_fanout_record_accepted",
    "mdb_fanout_record_processed",
    "mdb_fanout_bmdb_report",
    "mdb_fanout_ssit_nonempty",
    "mdb_fanout_lookup_valid",
    "mdb_fanout_lookup_accepted",
    "mdb_fanout_lookup_processed",
    "mdb_fanout_lookup_table_hit",
    "mdb_fanout_lookup_first_after_nuke",
    "mdb_fanout_lookup_conf_blocked",
    "mdb_fanout_lookup_weight_blocked",
    "mdb_fanout_lu_out_valid",
    "mdb_fanout_lu_out_hit",
    "mdb_fanout_su_out_valid",
    "mdb_fanout_su_out_hit",
    "mdb_fanout_su_wakeup_valid",
    "mdb_lookup_wait_plan_lookup_hit",
    "mdb_lookup_wait_plan_wait_intent_valid",
    "mdb_lookup_wait_plan_request_valid",
    "mdb_lookup_wait_plan_blocked_by_no_target",
    "mdb_lookup_wait_plan_blocked_by_missing_store_index",
    "mdb_lookup_wait_plan_blocked_by_missing_store_lsid",
    "mdb_lookup_wait_plan_bridge_active",
    "mdb_lookup_wait_plan_bridge_valid",
    "mdb_lookup_wait_plan_bridge_source_store_index_fits",
    "mdb_lookup_wait_plan_bridge_blocked_by_disabled",
    "mdb_lookup_wait_plan_bridge_blocked_by_flush",
    "mdb_lookup_wait_plan_bridge_blocked_by_no_request",
    "mdb_lookup_wait_plan_bridge_invalid_store_index_out_of_range",
    "mdb_lookup_wait_plan_bridge_invalid_conflicting_status_write",
    "mdb_lookup_wait_plan_bridge_invalid_wait_store_without_wait_status",
    "mdb_lookup_wait_plan_bridge_invalid_return_without_split_sources",
    "liq_row_mutation_bridge_valid",
    "liq_row_mutation_selected_source_return",
    "liq_row_mutation_selected_mdb_wait_plan",
    "liq_row_mutation_source_conflict",
    "mdb_wait_plan_row_mutation_write_enable",
    "liq_row_mutation_write_enable",
    "liq_row_mutation_apply_valid",
    "liq_row_mutation_blocked_by_bridge",
    "liq_row_mutation_blocked_by_control",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stats", type=Path, help="sideband stats JSON report")
    parser.add_argument(
        "--expect-reduced-store-replay-liq",
        action="store_true",
        help="require reduced_store_replay_liq_top=true",
    )
    parser.add_argument(
        "--require-nonzero",
        action="append",
        default=[],
        metavar="replay_liq.KEY",
        help="require a validated counter to be greater than zero",
    )
    parser.add_argument(
        "--require-zero",
        action="append",
        default=[],
        metavar="replay_liq.KEY",
        help="require a validated counter to be exactly zero",
    )
    parser.add_argument(
        "--preset",
        action="append",
        choices=sorted(PRESETS),
        default=[],
        help="apply a named bundle of replay-LIQ counter requirements",
    )
    return parser.parse_args()


def load_stats(path: Path) -> dict:
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except OSError as exc:
        print(f"error: failed to read sideband stats {path}: {exc}", file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as exc:
        print(f"error: malformed sideband stats {path}: {exc}", file=sys.stderr)
        sys.exit(2)


def validate_replay_liq(stats: dict, expect_replay_liq: bool) -> dict[str, int]:
    schema = stats.get("schema")
    if schema != SCHEMA:
        print(f"error: unexpected sideband stats schema {schema!r}", file=sys.stderr)
        sys.exit(2)

    if stats.get("reduced_store_replay_liq_top") is not expect_replay_liq:
        print(
            "error: sideband stats reduced_store_replay_liq_top does not match "
            f"expected value {expect_replay_liq}",
            file=sys.stderr,
        )
        sys.exit(2)

    replay_liq = stats.get("replay_liq")
    if not isinstance(replay_liq, dict):
        print("error: sideband stats missing replay_liq object", file=sys.stderr)
        sys.exit(2)

    for key in REQUIRED_REPLAY_LIQ_KEYS:
        value = replay_liq.get(key)
        if not isinstance(value, int) or value < 0:
            print(f"error: replay_liq.{key} must be a nonnegative integer", file=sys.stderr)
            sys.exit(2)

    if replay_liq["cycles_sampled"] <= 0:
        print("error: replay_liq.cycles_sampled must be positive", file=sys.stderr)
        sys.exit(2)

    return replay_liq


def require_nonzero(replay_liq: dict[str, int], selectors: list[str]) -> None:
    for selector in selectors:
        if not selector.startswith("replay_liq."):
            print(
                f"error: unsupported nonzero selector {selector!r}; expected replay_liq.KEY",
                file=sys.stderr,
            )
            sys.exit(2)
        key = selector.removeprefix("replay_liq.")
        if key not in replay_liq:
            print(f"error: unknown replay_liq counter {key!r}", file=sys.stderr)
            sys.exit(2)
        if replay_liq[key] <= 0:
            print(
                f"error: replay_liq.{key} must be nonzero, observed {replay_liq[key]}",
                file=sys.stderr,
            )
            sys.exit(1)


def require_zero(replay_liq: dict[str, int], selectors: list[str]) -> None:
    for selector in selectors:
        if not selector.startswith("replay_liq."):
            print(
                f"error: unsupported zero selector {selector!r}; expected replay_liq.KEY",
                file=sys.stderr,
            )
            sys.exit(2)
        key = selector.removeprefix("replay_liq.")
        if key not in replay_liq:
            print(f"error: unknown replay_liq counter {key!r}", file=sys.stderr)
            sys.exit(2)
        if replay_liq[key] != 0:
            print(
                f"error: replay_liq.{key} must be zero, observed {replay_liq[key]}",
                file=sys.stderr,
            )
            sys.exit(1)


def main() -> int:
    args = parse_args()
    stats = load_stats(args.stats)
    replay_liq = validate_replay_liq(stats, args.expect_reduced_store_replay_liq)
    preset_nonzero: list[str] = []
    preset_zero: list[str] = []
    for preset_name in args.preset:
        preset = PRESETS[preset_name]
        preset_nonzero.extend(preset["nonzero"])
        preset_zero.extend(preset["zero"])
    require_nonzero(replay_liq, [*preset_nonzero, *args.require_nonzero])
    require_zero(replay_liq, [*preset_zero, *args.require_zero])
    print(f"sideband_stats_json={args.stats}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
