package linxcore.top

import circt.stage.ChiselStage
import linxcore.common.CoreParams
import org.scalatest.funsuite.AnyFunSuite

class LinxCoreFrontendFetchRfAluTraceTopSpec extends AnyFunSuite {
  test("interface combines live fetch source with RF-backed issue and ALU diagnostics") {
    val core = CoreParams(robEntries = 8, commitWidth = 2)
    val p = LinxCoreFrontendFetchRfAluTraceTop.interfaceParamsFor(core)
    val trace = LinxCoreFrontendFetchRfAluTraceTop.traceParamsFor(p)
    val io = new LinxCoreFrontendFetchRfAluTraceTopIO(p, trace, issueQueueDepth = 4, physRegs = 64)

    assert(p.robEntries == 8)
    assert(p.commitWidth == 2)
    assert(trace.commitWidth == 2)
    assert(trace.robValueWidth == 3)
    assert(io.startPc.getWidth == 64)
    assert(io.reducedBfuBodyValid.getWidth == 1)
    assert(io.reducedBfuHeaderPc.getWidth == 64)
    assert(io.reducedBfuHSizeBytes.getWidth == 64)
    assert(io.reducedBfuBSizeBytes.getWidth == 64)
    assert(io.reducedBfuStaticGeometryValid.getWidth == 1)
    assert(io.reducedBfuStaticHeaderActive.getWidth == 1)
    assert(io.reducedBfuStaticLearnedFire.getWidth == 1)
    assert(io.reducedBfuStaticResolvedLearnedFire.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndAccepted.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndInactiveDrop.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndFlushDrop.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndUnderflow.getWidth == 1)
    assert(io.reducedBfuStaticExternalComparable.getWidth == 1)
    assert(io.reducedBfuStaticExternalMatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalHSizeMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalBSizeMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmComparable.getWidth == 1)
    assert(io.reducedBfuBodyCutArmAccepted.getWidth == 1)
    assert(io.reducedBfuBodyCutArmMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmHSizeMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmBSizeMismatch.getWidth == 1)
    assert(io.fetchReqPc.getWidth == 64)
    assert(io.fetchRespWindow.getWidth == 64)
    assert(io.sourceAdvanceBytes.getWidth == 4)
    assert(io.reducedBodyCutActive.getWidth == 1)
    assert(io.reducedBodyCutFire.getWidth == 1)
    assert(io.reducedBodyCutAdvanceBytes.getWidth == 4)
    assert(io.denseSlotQueueInFire.getWidth == 1)
    assert(io.denseSlotQueueOutFire.getWidth == 1)
    assert(io.denseSlotQueueInSlotCount.getWidth == 3)
    assert(io.denseSlotQueueCount.getWidth == 4)
    assert(io.denseSlotQueueHeadSlot.getWidth == 2)
    assert(io.blockMarkerSkipFire.getWidth == 1)
    assert(io.blockMarkerMixedPacket.getWidth == 1)
    assert(io.blockMarkerPc.getWidth == 64)
    assert(io.blockMarkerInsn.getWidth == 64)
    assert(io.blockMarkerLen.getWidth == 4)
    assert(io.blockMarkerTarget.getWidth == 64)
    assert(io.blockMarkerAllocReady.getWidth == 1)
    assert(io.blockMarkerLifecycleConflict.getWidth == 1)
    assert(io.blockMarkerAllocFire.getWidth == 1)
    assert(io.blockMarkerAllocBid.getWidth == 64)
    assert(io.blockMarkerActiveValid.getWidth == 1)
    assert(io.blockMarkerActiveBid.getWidth == 64)
    assert(io.blockMarkerActiveTarget.getWidth == 64)
    assert(io.blockMarkerStopRedirectValid.getWidth == 1)
    assert(io.blockMarkerStopRedirectPc.getWidth == 64)
    assert(io.rfInitArchTag.getWidth == 6)
    assert(io.rfInitData.getWidth == 64)
    assert(io.rfReadyMask.getWidth == 64)
    assert(io.issueQueueCount.getWidth == 3)
    assert(io.issueQueueHeadPc.getWidth == 64)
    assert(io.issueQueueHeadOpcode.getWidth == 12)
    assert(io.issueQueueHeadSrcValidMask.getWidth == 3)
    assert(io.issueQueueHeadSrcClass.length == 3)
    assert(io.issueQueueHeadSrcPhysTag.head.getWidth == 6)
    assert(io.issueQueueHeadSrcRelTag.head.getWidth == 6)
    assert(io.issueQueueSelectedIndex.getWidth == 2)
    assert(io.decRenValid.getWidth == 1)
    assert(io.decRenHeadPc.getWidth == 64)
    assert(io.decRenHeadRidValid.getWidth == 1)
    assert(io.decRenHeadRidValue.getWidth == 3)
    assert(io.robRenameUpdateAttemptValid.getWidth == 1)
    assert(io.robRenameUpdateReady.getWidth == 1)
    assert(io.robRenameUpdateIgnored.getWidth == 1)
    assert(io.localTReadyMask.getWidth == 4)
    assert(io.localUReadyMask.getWidth == 4)
    assert(io.localTPendingCount.getWidth == 3)
    assert(io.localUPendingCount.getWidth == 3)
    assert(io.localIncomingUsesLocal.getWidth == 1)
    assert(io.localIncomingBlocked.getWidth == 1)
    assert(io.decodeBlockedByRob.getWidth == 1)
    assert(io.decodeBlockedByOutput.getWidth == 1)
    assert(io.tuRenameSourceUnderflowMask.getWidth == 3)
    assert(io.executeCompleteRobValue.getWidth == 3)
    assert(io.commit.rows.length == 2)
    assert(io.robDeallocBlockLastValid.getWidth == 1)
    assert(io.robDeallocBlockLastBlockBid.getWidth == 64)
    assert(io.blockScalarDoneFire.getWidth == 1)
    assert(io.blockScalarDoneBid.getWidth == 64)
    assert(io.blockRetireFire.getWidth == 1)
    assert(io.blockRetireBid.getWidth == 64)
    assert(io.blockAllocatedMask.getWidth == 8)
    assert(io.blockCompleteMask.getWidth == 8)
    assert(io.blockPendingMask.getWidth == 8)
  }

  test("LinxCoreFrontendFetchRfAluTraceTop elaborates source, frontend, rename, RF, issue, ROB, and ALU execute") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluTraceTop(CoreParams(robEntries = 8, commitWidth = 2), mapQDepth = 8)
    )

    assert(sv.contains("module LinxCoreFrontendFetchRfAluTraceTop"))
    assert(sv.contains("module FrontendFetchPacketSource"))
    assert(sv.contains("module F4DecodeWindow"))
    assert(sv.contains("module F4DenseSlotQueue"))
    assert(sv.contains("module DecodeRenameROBPath"))
    assert(sv.contains("module ReducedScalarRegisterFile"))
    assert(sv.contains("module ReducedScalarIssueQueue"))
    assert(sv.contains("module ReducedScalarIssuePick"))
    assert(sv.contains("module ReducedScalarAluExecute"))
    assert(sv.contains("module CommitTraceMonitor"))
    assert(sv.contains("module ReducedBfuBodyCutPredictor"))
    assert(sv.contains("module ReducedBfuBodyCutArm"))
    assert(sv.contains("module ReducedBfuResolvedBodyEndOwner"))
    assert(sv.contains("module ReducedBfuStaticGeometryProducer"))
    assert(sv.contains("io_fetchReqValid"))
    assert(sv.contains("io_sourceOutFire"))
    assert(sv.contains("io_reducedBodyCutFire"))
    assert(sv.contains("io_reducedBfuStaticResolvedLearnedFire"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndAccepted"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndUnderflow"))
    assert(sv.contains("io_reducedBfuStaticExternalMatch"))
    assert(sv.contains("io_reducedBfuStaticExternalBSizeMismatch"))
    assert(sv.contains("io_reducedBfuBodyCutArmAccepted"))
    assert(sv.contains("io_reducedBfuBodyCutArmBSizeMismatch"))
    assert(sv.contains("io_denseSlotQueueOutFire"))
    assert(sv.contains("io_blockMarkerSkipFire"))
    assert(sv.contains("io_blockMarkerMixedPacket"))
    assert(sv.contains("io_blockMarkerAllocReady"))
    assert(sv.contains("io_blockMarkerLifecycleConflict"))
    assert(sv.contains("io_blockMarkerAllocFire"))
    assert(sv.contains("io_blockMarkerActiveBid"))
    assert(sv.contains("io_blockMarkerStopRedirectValid"))
    assert(sv.contains("io_rfWriteValid"))
    assert(sv.contains("io_issueQueuePickFire"))
    assert(sv.contains("io_issueQueueHeadPc"))
    assert(sv.contains("io_issueQueueHeadSrcValidMask"))
    assert(sv.contains("io_issueQueueHeadSrcPhysTag"))
    assert(sv.contains("io_decRenValid"))
    assert(sv.contains("io_decRenHeadPc"))
    assert(sv.contains("io_robRenameUpdateReady"))
    assert(sv.contains("io_localTReadyMask"))
    assert(sv.contains("io_localIncomingUsesLocal"))
    assert(sv.contains("io_localIncomingBlocked"))
    assert(sv.contains("io_decodeBlockedByTURename"))
    assert(sv.contains("io_executeCompleteValid"))
    assert(sv.contains("io_blockScalarDoneFire"))
    assert(sv.contains("io_blockRetireFire"))
    assert(sv.contains("io_blockAllocatedMask"))
    assert(sv.contains("io_commitContractError"))
  }
}
