package linxcore.top

import circt.stage.ChiselStage
import linxcore.common.CoreParams
import org.scalatest.funsuite.AnyFunSuite

class LinxCoreFrontendFetchRfAluTraceTopSpec extends AnyFunSuite {
  test("interface combines live fetch source with RF-backed issue and ALU diagnostics") {
    val core = CoreParams(robEntries = 8, commitWidth = 2)
    val p = LinxCoreFrontendFetchRfAluTraceTop.interfaceParamsFor(core)
    val trace = LinxCoreFrontendFetchRfAluTraceTop.traceParamsFor(p)
    val io = new LinxCoreFrontendFetchRfAluTraceTopIO(p, trace, issueQueueDepth = 4, physRegs = 64)

    assert(p.robEntries == 8)
    assert(p.commitWidth == 2)
    assert(trace.commitWidth == 2)
    assert(trace.robValueWidth == 3)
    assert(io.startPc.getWidth == 64)
    assert(io.reducedBfuBodyValid.getWidth == 1)
    assert(io.reducedBfuHeaderPc.getWidth == 64)
    assert(io.reducedBfuHSizeBytes.getWidth == 64)
    assert(io.reducedBfuBSizeBytes.getWidth == 64)
    assert(io.reducedBfuStaticGeometryValid.getWidth == 1)
    assert(io.reducedBfuStaticHeaderActive.getWidth == 1)
    assert(io.reducedBfuStaticLearnedFire.getWidth == 1)
    assert(io.reducedBfuStaticResolvedLearnedFire.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndAccepted.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndInactiveDrop.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndFlushDrop.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndUnderflow.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimeSelected.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceReplaySelected.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimeReplayComparable.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimeReplayMatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimeReplayMismatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimeFeedbackFire.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePending.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePendingConsumeFire.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePendingDropMismatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePendingCandidateComparable.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePendingCandidateMatch.getWidth == 1)
    assert(io.reducedBfuResolvedBodyEndSourceRuntimePendingCandidateMismatch.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidateValid.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidatePendingWithoutActiveHeader.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidateActiveHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidateReplayComparable.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidateReplayMatch.getWidth == 1)
    assert(io.reducedBfuPendingRuntimeCandidateReplayMismatch.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOraclePending.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOracleCaptureFire.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOracleReplayComparable.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOracleReplayMatch.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOracleReplayMismatch.getWidth == 1)
    assert(io.reducedBfuPromotedRuntimeBodyEndOracleOverwritePending.getWidth == 1)
    assert(io.reducedBfuStaticExternalComparable.getWidth == 1)
    assert(io.reducedBfuStaticExternalMatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalHSizeMismatch.getWidth == 1)
    assert(io.reducedBfuStaticExternalBSizeMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmComparable.getWidth == 1)
    assert(io.reducedBfuBodyCutArmAccepted.getWidth == 1)
    assert(io.reducedBfuBodyCutArmMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmHeaderMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmHSizeMismatch.getWidth == 1)
    assert(io.reducedBfuBodyCutArmBSizeMismatch.getWidth == 1)
    assert(io.fetchReqPc.getWidth == 64)
    assert(io.fetchRespWindow.getWidth == 64)
    assert(io.sourceAdvanceBytes.getWidth == 4)
    assert(io.reducedBodyCutActive.getWidth == 1)
    assert(io.reducedBodyCutFire.getWidth == 1)
    assert(io.reducedBodyCutAdvanceBytes.getWidth == 4)
    assert(io.denseSlotQueueInFire.getWidth == 1)
    assert(io.denseSlotQueueOutFire.getWidth == 1)
    assert(io.denseSlotQueueInSlotCount.getWidth == 3)
    assert(io.denseSlotQueueCount.getWidth == 4)
    assert(io.denseSlotQueueHeadSlot.getWidth == 2)
    assert(io.admittedMarkerDrainBarrier.getWidth == 1)
    assert(io.blockMarkerSkipFire.getWidth == 1)
    assert(io.blockMarkerMixedPacket.getWidth == 1)
    assert(io.blockMarkerPc.getWidth == 64)
    assert(io.blockMarkerInsn.getWidth == 64)
    assert(io.blockMarkerLen.getWidth == 4)
    assert(io.blockMarkerTarget.getWidth == 64)
    assert(io.blockMarkerAllocReady.getWidth == 1)
    assert(io.blockMarkerLifecycleConflict.getWidth == 1)
    assert(io.blockMarkerAllocFire.getWidth == 1)
    assert(io.blockMarkerAllocBid.getWidth == 64)
    assert(io.blockMarkerActiveValid.getWidth == 1)
    assert(io.blockMarkerActiveBid.getWidth == 64)
    assert(io.blockMarkerActiveTarget.getWidth == 64)
    assert(io.blockMarkerStopRedirectValid.getWidth == 1)
    assert(io.blockMarkerStopRedirectPc.getWidth == 64)
    assert(io.rfInitArchTag.getWidth == 6)
    assert(io.rfInitData.getWidth == 64)
    assert(io.rfReadyMask.getWidth == 64)
    assert(io.issueQueueCount.getWidth == 3)
    assert(io.issueQueueHeadPc.getWidth == 64)
    assert(io.issueQueueHeadOpcode.getWidth == 12)
    assert(io.issueQueueHeadSrcValidMask.getWidth == 3)
    assert(io.issueQueueHeadSrcClass.length == 3)
    assert(io.issueQueueHeadSrcPhysTag.head.getWidth == 6)
    assert(io.issueQueueHeadSrcRelTag.head.getWidth == 6)
    assert(io.issueQueueSelectedIndex.getWidth == 2)
    assert(io.decRenValid.getWidth == 1)
    assert(io.decRenHeadPc.getWidth == 64)
    assert(io.decRenHeadRidValid.getWidth == 1)
    assert(io.decRenHeadRidValue.getWidth == 3)
    assert(io.robRenameUpdateAttemptValid.getWidth == 1)
    assert(io.robRenameUpdateReady.getWidth == 1)
    assert(io.robRenameUpdateIgnored.getWidth == 1)
    assert(io.localTReadyMask.getWidth == 4)
    assert(io.localUReadyMask.getWidth == 4)
    assert(io.localTPendingCount.getWidth == 3)
    assert(io.localUPendingCount.getWidth == 3)
    assert(io.localIncomingUsesLocal.getWidth == 1)
    assert(io.localIncomingBlocked.getWidth == 1)
    assert(io.decodeBlockedByRob.getWidth == 1)
    assert(io.decodeBlockedByOutput.getWidth == 1)
    assert(io.tuRenameSourceUnderflowMask.getWidth == 3)
    assert(io.executeCompleteRobValue.getWidth == 3)
    assert(io.executeLoadWaitHold.getWidth == 1)
    assert(io.loadLookupPc.getWidth == 64)
    assert(io.loadLookupDstValid.getWidth == 1)
    assert(io.loadLookupDstKind.getWidth == 2)
    assert(io.loadLookupDstArchTag.getWidth == 6)
    assert(io.loadLookupDstRelTag.getWidth == 6)
    assert(io.loadLookupDstPhysTag.getWidth == 6)
    assert(io.loadLookupDstOldPhysTag.getWidth == 6)
    assert(io.loadLookupExecuteGranted.getWidth == 1)
    assert(io.loadLookupReplayGranted.getWidth == 1)
    assert(io.reducedStoreDispatchEnabled.getWidth == 1)
    assert(io.reducedStoreExecCompleteStoreValid.getWidth == 1)
    assert(io.reducedStoreExecCaptureFire.getWidth == 1)
    assert(io.reducedStoreExecCaptureBlocked.getWidth == 1)
    assert(io.reducedStoreExecCaptureDuplicate.getWidth == 1)
    assert(io.reducedStoreExecStaMatch.getWidth == 1)
    assert(io.reducedStoreExecStdMatch.getWidth == 1)
    assert(io.reducedStoreExecValidMask.getWidth == 4)
    assert(io.reducedStoreExecBufferCount.getWidth == 3)
    assert(io.reducedStoreStaExecValid.getWidth == 1)
    assert(io.reducedStoreStdExecValid.getWidth == 1)
    assert(io.reducedStoreCommitStoreSeen.getWidth == 1)
    assert(io.reducedStoreCommitStoreMatched.getWidth == 1)
    assert(io.reducedStoreCommitStoreUnmatched.getWidth == 1)
    assert(io.reducedStoreCommitMatchMask.getWidth == 8)
    assert(io.reducedStoreCommitPendingMarkMask.getWidth == 8)
    assert(io.reducedStoreCommitPendingFreeMask.getWidth == 8)
    assert(io.reducedStoreCommitPendingMarkCount.getWidth == 4)
    assert(io.reducedStoreCommitPendingFreeCount.getWidth == 4)
    assert(io.reducedStoreCommitMarkValid.getWidth == 1)
    assert(io.reducedStoreCommitMarkIndex.getWidth == 3)
    assert(io.reducedStoreCommitMarkAccepted.getWidth == 1)
    assert(io.reducedStoreCommitMarkIgnored.getWidth == 1)
    assert(io.reducedStoreCommitFreeValid.getWidth == 1)
    assert(io.reducedStoreCommitFreeIndex.getWidth == 3)
    assert(io.reducedStoreCommitFreeAccepted.getWidth == 1)
    assert(io.reducedStoreCommitFreeAcceptedMask.getWidth == 8)
    assert(io.reducedStoreCommitFreeCount.getWidth == 4)
    assert(io.reducedStoreDrainEnqueueAccepted.getWidth == 1)
    assert(io.reducedStoreDrainEnqueueDuplicate.getWidth == 1)
    assert(io.reducedStoreDrainIssueValidMask.getWidth == 2)
    assert(io.reducedStoreDrainIssueCount.getWidth == 2)
    assert(io.reducedStoreDrainEarlyFreeMask.getWidth == 8)
    assert(io.reducedStoreDrainQueueCount.getWidth == 4)
    assert(io.reducedStoreDrainEmpty.getWidth == 1)
    assert(io.reducedStoreDrainOrderError.getWidth == 1)
    assert(io.reducedStoreScbReadyForDrain.getWidth == 1)
    assert(io.reducedStoreScbAcceptedMask.getWidth == 4)
    assert(io.reducedStoreScbStalledMask.getWidth == 4)
    assert(io.reducedStoreScbCommitFreeMaskValid.getWidth == 1)
    assert(io.reducedStoreScbCommitFreeMask.getWidth == 8)
    assert(io.reducedStoreScbCommitFreeCount.getWidth == 3)
    assert(io.reducedStoreScbValidMask.getWidth == 8)
    assert(io.reducedStoreScbEntryCount.getWidth == 4)
    assert(io.reducedStoreMemoryValidMask.getWidth == 64)
    assert(io.reducedStoreMemoryLineCount.getWidth == 7)
    assert(io.reducedStoreMemoryLoadForwardMask.getWidth == 8)
    assert(io.reducedStoreMemoryStoreDroppedMask.getWidth == 8)
    assert(io.reducedStoreResidentForwardMask.getWidth == 8)
    assert(io.reducedStoreResidentWaitMask.getWidth == 8)
    assert(io.reducedStoreResidentEligibleMask.getWidth == 8)
    assert(io.reducedStoreResidentReadyForward.getWidth == 1)
    assert(io.reducedStoreResidentWaitBlocked.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreValid.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreIndex.getWidth == 3)
    assert(io.reducedStoreResidentWaitStoreBidValid.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreBidWrap.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreBidValue.getWidth == 3)
    assert(io.reducedStoreResidentWaitStoreLsIdValid.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreLsIdWrap.getWidth == 1)
    assert(io.reducedStoreResidentWaitStoreLsIdValue.getWidth == 3)
    assert(io.reducedStoreResidentWaitStorePc.getWidth == 64)
    assert(io.reducedStoreResidentLoadCrossesLine.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeValid.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeSelected.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeIdentityMatch.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeReady.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeCrossesLine.getWidth == 1)
    assert(io.reducedStoreResidentReplayWakeLineAddr.getWidth == 64)
    assert(io.reducedStoreResidentReplayWakeByteMask.getWidth == 64)
    assert(io.reducedLoadWaitReplayActive.getWidth == 1)
    assert(io.reducedLoadWaitReplayCaptureAccepted.getWidth == 1)
    assert(io.reducedLoadWaitReplayClearValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayStoredWaitValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayStoredWaitPc.getWidth == 64)
    assert(io.reducedLoadWaitReplayRelaunchValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchPc.getWidth == 64)
    assert(io.reducedLoadWaitReplayRelaunchAddr.getWidth == 64)
    assert(io.reducedLoadWaitReplayRelaunchSize.getWidth == 7)
    assert(io.reducedLoadWaitReplayRelaunchDstValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchDstKind.getWidth == 2)
    assert(io.reducedLoadWaitReplayRelaunchDstArchTag.getWidth == 6)
    assert(io.reducedLoadWaitReplayRelaunchDstRelTag.getWidth == 6)
    assert(io.reducedLoadWaitReplayRelaunchDstPhysTag.getWidth == 6)
    assert(io.reducedLoadWaitReplayRelaunchDstOldPhysTag.getWidth == 6)
    assert(io.reducedLoadWaitReplayRelaunchBidValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchBidWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchBidValue.getWidth == 3)
    assert(io.reducedLoadWaitReplayRelaunchGidValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchGidWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchGidValue.getWidth == 3)
    assert(io.reducedLoadWaitReplayRelaunchRidValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchRidWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchRidValue.getWidth == 3)
    assert(io.reducedLoadWaitReplayRelaunchLsIdValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchLsIdWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchLsIdValue.getWidth == 3)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreIdValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreIdWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreIdValue.getWidth == 3)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreLsIdValid.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreLsIdWrap.getWidth == 1)
    assert(io.reducedLoadWaitReplayRelaunchYoungestStoreLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayQueueOutYoungestStoreIdValid.getWidth == 1)
    assert(io.reducedLoadReplayQueueOutYoungestStoreIdWrap.getWidth == 1)
    assert(io.reducedLoadReplayQueueOutYoungestStoreIdValue.getWidth == 3)
    assert(io.reducedLoadReplayQueueOutDstValid.getWidth == 1)
    assert(io.reducedLoadReplayQueueOutDstKind.getWidth == 2)
    assert(io.reducedLoadReplayQueueOutDstArchTag.getWidth == 6)
    assert(io.reducedLoadReplayQueueOutDstRelTag.getWidth == 6)
    assert(io.reducedLoadReplayQueueOutDstPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayQueueOutDstOldPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayQueueOutYoungestStoreLsIdValid.getWidth == 1)
    assert(io.reducedLoadReplayQueueOutYoungestStoreLsIdWrap.getWidth == 1)
    assert(io.reducedLoadReplayQueueOutYoungestStoreLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqAllocEnabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqAllocConsumeReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqAllocCandidateUsable.getWidth == 1)
    assert(io.reducedLoadReplayLiqAllocBlockedByAlloc.getWidth == 1)
    assert(io.reducedLoadReplayLiqAllocAccepted.getWidth == 1)
    assert(io.reducedLoadReplayLiqAllocIndex.getWidth == 3)
    assert(io.reducedLoadReplayLiqAllocLoadIdValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqOccupiedMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqWaitMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqLaunchWaitMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqLaunchRequestCompleteMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqLaunchDataHitMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqLaunchCandidateMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqLaunchValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchIndex.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchDriveValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchAccepted.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchCandidateCount.getWidth == 4)
    assert(io.reducedLoadReplayLiqLaunchSelectedLoadIdValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchSelectedBidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchSelectedGidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchSelectedRidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchSelectedLoadLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLaunchSelectedPc.getWidth == 64)
    assert(io.reducedLoadReplayLiqLaunchSelectedAddr.getWidth == 64)
    assert(io.reducedLoadReplayLiqLaunchSelectedSize.getWidth == 7)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstKind.getWidth == 2)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstArchTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstRelTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLaunchSelectedDstOldPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLaunchSelectedRequestByteMask.getWidth == 64)
    assert(io.reducedLoadReplayLiqBaseLookupValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqBaseLookupCrossesLine.getWidth == 1)
    assert(io.reducedLoadReplayLiqBaseLookupPc.getWidth == 64)
    assert(io.reducedLoadReplayLiqBaseLookupAddr.getWidth == 64)
    assert(io.reducedLoadReplayLiqBaseLookupSize.getWidth == 7)
    assert(io.reducedLoadReplayLiqBaseLookupRequestByteMask.getWidth == 64)
    assert(io.reducedLoadReplayLiqBaseLineValidMask.getWidth == 64)
    assert(io.reducedLoadReplayLiqBaseDataReturned.getWidth == 1)
    assert(io.reducedLoadReplayLiqBaseLookupGranted.getWidth == 1)
    assert(io.reducedLoadReplayLiqBaseLookupBlockedByExecute.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBaseDataReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessSourcesReturned.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessEnable.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByBaseLookup.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByBaseData.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByScb.getWidth == 1)
    assert(io.reducedLoadReplayLiqLaunchReadinessBlockedByReturn.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnStoreSnapshotReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnStoreSourceReturned.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnScbSourceReturned.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnSourceReturned.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnBlockedByBaseData.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnBlockedByStoreSnapshot.getWidth == 1)
    assert(io.reducedLoadReplayLiqSourceReturnBlockedByScb.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetEnable.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetConsumerReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetAvailable.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetBlockedBySources.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetBlockedByBudgetDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBudgetBlockedByConsumer.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitPipeBudgetAvailable.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitMask.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitBlockedBySources.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipePermitBlockedByPipeBudget.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeAvailableMask.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeAvailable.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeSelectedPipeIndex.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBlockedBySources.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPipeBlockedByNoPipe.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessSelectedPipeIndex.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessBlockedBySources.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnReadinessBlockedByReturnPipe.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataRequestByteMask.getWidth == 64)
    assert(io.reducedLoadReplayLiqReturnDataBytesComplete.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataCrossLine.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataSizeSupported.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataRawData.getWidth == 64)
    assert(io.reducedLoadReplayLiqReturnData.getWidth == 64)
    assert(io.reducedLoadReplayLiqReturnDataValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByZeroSize.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByUnsupportedSize.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByCrossLine.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnDataBlockedByIncompleteBytes.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishDataReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishBlockedByData.getWidth == 1)
    assert(io.reducedLoadReplayLiqReturnPublishBlockedByConsumer.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBidValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBidWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPayloadGidValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadGidWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadGidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPayloadRidValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadRidWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadRidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPayloadLoadLsIdValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadLoadLsIdWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadLoadLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPayloadPc.getWidth == 64)
    assert(io.reducedLoadReplayLiqLretPayloadAddr.getWidth == 64)
    assert(io.reducedLoadReplayLiqLretPayloadSize.getWidth == 7)
    assert(io.reducedLoadReplayLiqLretPayloadDstValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadDstKind.getWidth == 2)
    assert(io.reducedLoadReplayLiqLretPayloadDstArchTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLretPayloadDstRelTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLretPayloadDstPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLretPayloadDstOldPhysTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqLretPayloadData.getWidth == 64)
    assert(io.reducedLoadReplayLiqLretPayloadPipeIndex.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadSpecWakeup.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadStackValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadWakeupRequired.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBlockedByNoCandidate.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPayloadBlockedByData.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadPayloadValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadFireValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadTargetIsAgu.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadTargetIsLda.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadPipeIndex.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadBidValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadBidWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadBidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadRidValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadRidWrap.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadRidValue.getWidth == 3)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadBlocked.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadInvalidFireWithoutPayload.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretPipeW2ResolveFirePayloadInvalidPayloadWithoutFire.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkEnqueueReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkEnqueueAccepted.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkEnqueueDropped.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkDrainValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkDrainFire.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkPending.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkFull.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkEmpty.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkCount.getWidth == 2)
    assert(io.reducedLoadReplayLiqLretSinkBlockedByFlush.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkBlockedByNoPayload.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkBlockedByFull.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretSinkBlockedByDrain.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitEnable.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitPipeOccupiedMask.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitPipeFreeMask.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitAnyPipeFree.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitSelectedPipeIndex.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitBlockedByFlush.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitBlockedByNoEntry.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretDrainPermitBlockedByPipeFull.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataEnable.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataRobRowValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataRobRowNeedFlush.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataWouldDrain.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataSetMemDataValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByFlush.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByNoEntry.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByInvalidEntry.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByDrain.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByRobMissing.getWidth == 1)
    assert(io.reducedLoadReplayLiqLretIexDataBlockedByNeedFlush.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqWritebackData.getWidth == 64)
    assert(io.reducedLoadReplayLiqWritebackIgnoredNoDestination.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackIgnoredNonGprDestination.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackArbiterReplayEnabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackArbiterSelectedExecute.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackArbiterSelectedReplay.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackArbiterReplayBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqWritebackArbiterReplayBlockedByExecute.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectLretReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectWritebackReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectWakeupReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectReady.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectBlockedByNoPayload.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectBlockedByLret.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectBlockedByWriteback.getWidth == 1)
    assert(io.reducedLoadReplayLiqSideEffectBlockedByWakeup.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlLiveEnable.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlArmed.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlFire.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlBlockedByNoPayload.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlBlockedByPublish.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlBlockedBySideEffects.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishControlBlockedByLiveDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestLret.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestWriteback.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestWakeup.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestMask.getWidth == 3)
    assert(io.reducedLoadReplayLiqPublishRequestBlockedByNoFire.getWidth == 1)
    assert(io.reducedLoadReplayLiqPublishRequestInvalidFireWithoutPayload.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupCandidateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupRequired.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupKind.getWidth == 2)
    assert(io.reducedLoadReplayLiqWakeupTag.getWidth == 6)
    assert(io.reducedLoadReplayLiqWakeupReducedGprValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupNonGpr.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupSuppressedNotRequired.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupIgnoredNoDestination.getWidth == 1)
    assert(io.reducedLoadReplayLiqWakeupBlockedByDisabled.getWidth == 1)
    assert(io.reducedLoadReplayLiqRepickMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqMissMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqResolvedMask.getWidth == 8)
    assert(io.reducedLoadReplayLiqE4UpdateValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqE4UpdateIndex.getWidth == 3)
    assert(io.reducedLoadReplayLiqE4MissKind.getWidth == 3)
    assert(io.reducedLoadReplayLiqE4WakeupValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqLhqRecordValid.getWidth == 1)
    assert(io.reducedLoadReplayLiqResidentCount.getWidth == 4)
    assert(io.reducedLoadReplayResolveQueuePushReady.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueuePushAccepted.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueClearPending.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueClearAccepted.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueClearIndex.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueRetireValid.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueRetireIsLoadStore.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueRetireIsLoad.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueRetireIsStore.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueRetireBidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueRetireRidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueRetireLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueuePreciseFlushValid.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueuePreciseFlushBidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueuePreciseFlushRidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueuePreciseFlushLsIdValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueFlushPruneMask.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueFlushPruneCount.getWidth == 4)
    assert(io.reducedLoadReplayResolveQueueRetireMask.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueRetireCount.getWidth == 4)
    assert(io.reducedLoadReplayResolveQueueValidMask.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueCount.getWidth == 4)
    assert(io.reducedLoadReplayResolveQueueEmpty.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueFull.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueHeadValid.getWidth == 1)
    assert(io.reducedLoadReplayResolveQueueHeadPeId.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueHeadStid.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueHeadTid.getWidth == 8)
    assert(io.reducedLoadReplayResolveQueueHeadPc.getWidth == 64)
    assert(io.reducedLoadReplayResolveQueueHeadAddr.getWidth == 64)
    assert(io.reducedLoadReplayResolveQueueHeadSize.getWidth == 7)
    assert(io.reducedLoadReplayResolveQueueHeadBidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueHeadGidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueHeadRidValue.getWidth == 3)
    assert(io.reducedLoadReplayResolveQueueHeadLsIdValue.getWidth == 3)
    assert(io.reducedMdbConflictStoreValid.getWidth == 1)
    assert(io.reducedMdbConflictActiveCandidateMask.getWidth == 8)
    assert(io.reducedMdbConflictResolveCandidateMask.getWidth == 8)
    assert(io.reducedMdbConflictWaitStoreMask.getWidth == 8)
    assert(io.reducedMdbConflictWaitStoreCount.getWidth == 4)
    assert(io.reducedMdbConflictValid.getWidth == 1)
    assert(io.reducedMdbConflictActiveIndex.getWidth == 3)
    assert(io.reducedMdbConflictResolveIndex.getWidth == 3)
    assert(io.reducedMdbConflictOrdinal.getWidth == 4)
    assert(io.reducedMdbConflictInnerFlush.getWidth == 1)
    assert(io.reducedMdbConflictNukeFlush.getWidth == 1)
    assert(io.reducedMdbConflictLoadBidValue.getWidth == 3)
    assert(io.reducedMdbConflictLoadLsIdValue.getWidth == 3)
    assert(io.reducedMdbConflictStoreBidValue.getWidth == 3)
    assert(io.reducedMdbConflictStoreLsIdValue.getWidth == 3)
    assert(io.reducedMdbFanoutLookupValid.getWidth == 1)
    assert(io.reducedMdbFanoutLookupReady.getWidth == 1)
    assert(io.reducedMdbFanoutLookupAccepted.getWidth == 1)
    assert(io.reducedMdbFanoutLookupProcessed.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteValid.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteReady.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteAccepted.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteProcessed.getWidth == 1)
    assert(io.reducedMdbFanoutPhaseStalledByFanout.getWidth == 1)
    assert(io.reducedMdbFanoutLuOutValid.getWidth == 1)
    assert(io.reducedMdbFanoutLuOutHit.getWidth == 1)
    assert(io.reducedMdbFanoutLuOutStoreBidValue.getWidth == 3)
    assert(io.reducedMdbFanoutSuOutValid.getWidth == 1)
    assert(io.reducedMdbFanoutSuOutHit.getWidth == 1)
    assert(io.reducedMdbFanoutSuOutStoreBidValue.getWidth == 3)
    assert(io.reducedMdbFanoutRecordValid.getWidth == 1)
    assert(io.reducedMdbFanoutRecordReady.getWidth == 1)
    assert(io.reducedMdbFanoutRecordAccepted.getWidth == 1)
    assert(io.reducedMdbFanoutRecordProcessed.getWidth == 1)
    assert(io.reducedMdbFanoutBmdbReportValid.getWidth == 1)
    assert(io.reducedMdbFanoutBmdbLoadBidValue.getWidth == 3)
    assert(io.reducedMdbFanoutBmdbStoreBidValue.getWidth == 3)
    assert(io.reducedMdbFanoutBmdbStoreStid.getWidth == 8)
    assert(io.reducedMdbFanoutDeleteMatched.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteReleased.getWidth == 1)
    assert(io.reducedMdbFanoutDeleteDroppedBelowStall.getWidth == 1)
    assert(io.reducedMdbFanoutRecordOverflow.getWidth == 1)
    assert(io.reducedMdbFanoutRecordOrderIllegal.getWidth == 1)
    assert(io.reducedMdbFanoutSsitValidMask.getWidth == 8)
    assert(io.reducedMdbFanoutSuMatchedStore.getWidth == 1)
    assert(io.reducedMdbFanoutSuStorePending.getWidth == 1)
    assert(io.reducedMdbFanoutSuWakeupValid.getWidth == 1)
    assert(io.reducedMdbFanoutSuWakeupIndex.getWidth == 3)
    assert(io.reducedLoadWaitReplaySlotPc.getWidth == 64)
    assert(io.reducedLoadWaitReplaySlotAddr.getWidth == 64)
    assert(io.storeDispatchReady.getWidth == 1)
    assert(io.storeDispatchFire.getWidth == 1)
    assert(io.storeDispatchSplit.getWidth == 1)
    assert(io.storeStaQueueValid.getWidth == 1)
    assert(io.storeStdQueueValid.getWidth == 1)
    assert(io.storeStaQueueCount.getWidth == 3)
    assert(io.storeStdQueueCount.getWidth == 3)
    assert(io.storeStqInsertIndex.getWidth == 3)
    assert(io.storeStqOccupiedMask.getWidth == 8)
    assert(io.storeStqResidentCount.getWidth == 4)
    assert(io.commit.rows.length == 2)
    assert(io.robDeallocBlockLastValid.getWidth == 1)
    assert(io.robDeallocBlockLastBlockBid.getWidth == 64)
    assert(io.blockScalarDoneFire.getWidth == 1)
    assert(io.blockScalarDoneBid.getWidth == 64)
    assert(io.blockRetireFire.getWidth == 1)
    assert(io.blockRetireBid.getWidth == 64)
    assert(io.gprCommitAccepted.getWidth == 1)
    assert(io.gprCommitBlockBid.getWidth == 64)
    assert(io.gprCommittedMapQCount.getWidth == 6)
    assert(io.gprReleasedPhysCount.getWidth == 7)
    assert(io.blockAllocatedMask.getWidth == 8)
    assert(io.blockCompleteMask.getWidth == 8)
    assert(io.blockPendingMask.getWidth == 8)
  }

  test("LinxCoreFrontendFetchRfAluTraceTop elaborates source, frontend, rename, RF, issue, ROB, and ALU execute") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluTraceTop(CoreParams(robEntries = 8, commitWidth = 2), mapQDepth = 8)
    )

    assert(sv.contains("module LinxCoreFrontendFetchRfAluTraceTop"))
    assert(sv.contains("module FrontendFetchPacketSource"))
    assert(sv.contains("module F4DecodeWindow"))
    assert(sv.contains("module F4DenseSlotQueue"))
    assert(sv.contains("module DecodeRenameROBPath"))
    assert(!sv.contains("module BlockMarkerDecodeContext"))
    assert(sv.contains("module ReducedScalarRegisterFile"))
    assert(sv.contains("module ReducedScalarIssueQueue"))
    assert(sv.contains("module ReducedScalarIssuePick"))
    assert(sv.contains("module ReducedScalarAluExecute"))
    assert(sv.contains("module CommitTraceMonitor"))
    assert(sv.contains("module ReducedBfuBodyCutPredictor"))
    assert(sv.contains("module ReducedBfuBodyCutArm"))
    assert(sv.contains("module ReducedBfuResolvedBodyEndOwner"))
    assert(sv.contains("module ReducedBfuResolvedBodyEndPending"))
    assert(sv.contains("module ReducedBfuPendingRuntimeBodyEndCandidate"))
    assert(sv.contains("module ReducedBfuPromotedRuntimeBodyEndOracle"))
    assert(sv.contains("module ReducedBfuResolvedBodyEndSource"))
    assert(sv.contains("module ReducedBfuStaticGeometryProducer"))
    assert(sv.contains("io_fetchReqValid"))
    assert(sv.contains("io_sourceOutFire"))
    assert(sv.contains("io_reducedBodyCutFire"))
    assert(sv.contains("io_reducedBfuStaticResolvedLearnedFire"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndAccepted"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndUnderflow"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndSourceRuntimeSelected"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndSourceRuntimeFeedbackFire"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndSourceRuntimePending"))
    assert(sv.contains("io_reducedBfuResolvedBodyEndSourceRuntimePendingCandidateMatch"))
    assert(sv.contains("io_reducedBfuPendingRuntimeCandidateReplayMatch"))
    assert(sv.contains("io_reducedBfuPendingRuntimeCandidateActiveHeaderMismatch"))
    assert(sv.contains("io_reducedBfuPromotedRuntimeBodyEndOracleReplayMatch"))
    assert(sv.contains("io_reducedBfuPromotedRuntimeBodyEndOracleOverwritePending"))
    assert(sv.contains("io_reducedBfuStaticExternalMatch"))
    assert(sv.contains("io_reducedBfuStaticExternalBSizeMismatch"))
    assert(sv.contains("io_reducedBfuBodyCutArmAccepted"))
    assert(sv.contains("io_reducedBfuBodyCutArmBSizeMismatch"))
    assert(sv.contains("io_denseSlotQueueOutFire"))
    assert(sv.contains("io_admittedMarkerDrainBarrier"))
    assert(sv.contains("io_blockMarkerSkipFire"))
    assert(sv.contains("io_blockMarkerMixedPacket"))
    assert(sv.contains("io_blockMarkerAllocReady"))
    assert(sv.contains("io_blockMarkerLifecycleConflict"))
    assert(sv.contains("io_blockMarkerAllocFire"))
    assert(sv.contains("io_blockMarkerActiveBid"))
    assert(sv.contains("io_blockMarkerStopRedirectValid"))
    assert(sv.contains("io_rfWriteValid"))
    assert(sv.contains("io_issueQueuePickFire"))
    assert(sv.contains("io_issueQueueHeadPc"))
    assert(sv.contains("io_issueQueueHeadSrcValidMask"))
    assert(sv.contains("io_issueQueueHeadSrcPhysTag"))
    assert(sv.contains("io_decRenValid"))
    assert(sv.contains("io_decRenHeadPc"))
    assert(sv.contains("io_robRenameUpdateReady"))
    assert(sv.contains("io_localTReadyMask"))
    assert(sv.contains("io_localIncomingUsesLocal"))
    assert(sv.contains("io_localIncomingBlocked"))
    assert(sv.contains("io_decodeBlockedByTURename"))
    assert(sv.contains("io_executeCompleteValid"))
    assert(sv.contains("io_executeLoadWaitHold"))
    assert(sv.contains("io_reducedStoreExecCaptureFire"))
    assert(sv.contains("io_reducedStoreCommitPendingMarkMask"))
    assert(sv.contains("io_reducedStoreScbCommitFreeMask"))
    assert(sv.contains("io_storeStqResidentCount"))
    assert(sv.contains("io_blockScalarDoneFire"))
    assert(sv.contains("io_blockRetireFire"))
    assert(sv.contains("io_blockAllocatedMask"))
    assert(sv.contains("io_commitContractError"))
  }

  test("optional reduced STQ dispatch mode elaborates store exec and commit/free owners") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluTraceTop(
        CoreParams(robEntries = 8, commitWidth = 2),
        mapQDepth = 8,
        useReducedStoreDispatchStq = true)
    )

    assert(sv.contains("module ReducedStoreExecResultBridge"))
    assert(sv.contains("module ReducedStoreCommitFreeOwner"))
    assert(sv.contains("module STQCommitDrain"))
    assert(sv.contains("module SCBRowBank"))
    assert(sv.contains("module ReducedStoreMemoryOverlay"))
    assert(sv.contains("module ReducedStoreResidentForward"))
    assert(sv.contains("module ResidentStoreForwardStoreSnapshot"))
    assert(sv.contains("module ReducedLoadWaitReplaySlot"))
    assert(sv.contains("module ReducedLoadReplayRelaunchQueue"))
    assert(sv.contains("module ReducedLoadReplayLiqAllocPath"))
    assert(sv.contains("module LoadResolveQueue"))
    assert(sv.contains("module MDBConflictDetect"))
    assert(sv.contains("module MDBQueueFanout"))
    assert(sv.contains("module ReducedLoadReplayCompletionDrain"))
    assert(sv.contains("io_loadLookupDstPhysTag"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchDstPhysTag"))
    assert(sv.contains("io_reducedLoadReplayQueueOutDstPhysTag"))
    assert(sv.contains("io_reducedStoreDispatchEnabled"))
    assert(sv.contains("io_reducedStoreExecCaptureFire"))
    assert(sv.contains("io_reducedStoreCommitMarkValid"))
    assert(sv.contains("io_reducedStoreCommitFreeValid"))
    assert(sv.contains("io_reducedStoreDrainIssueValidMask"))
    assert(sv.contains("io_reducedStoreScbCommitFreeMask"))
    assert(sv.contains("io_reducedStoreMemoryLineCount"))
    assert(sv.contains("io_reducedStoreMemoryLoadForwardMask"))
    assert(sv.contains("io_reducedStoreResidentForwardMask"))
    assert(sv.contains("io_reducedStoreResidentWaitMask"))
    assert(sv.contains("io_reducedStoreResidentWaitStorePc"))
    assert(sv.contains("io_reducedStoreResidentReplayWakeValid"))
    assert(sv.contains("io_reducedLoadWaitReplayClearValid"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchValid"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchGidValue"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchRidValue"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchYoungestStoreIdValue"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchYoungestStoreLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayQueueEnqueueAccepted"))
    assert(sv.contains("io_reducedLoadReplayQueueOutBidValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutGidValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutRidValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutYoungestStoreIdValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutYoungestStoreLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayDrainMatchValid"))
    assert(sv.contains("io_reducedLoadReplayDrainGidMismatch"))
    assert(sv.contains("io_reducedLoadReplayDrainLsIdMismatch"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocEnabled"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocAccepted"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchCandidateMask"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchDriveValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchAccepted"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedPc"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedRequestByteMask"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupValid"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupGranted"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupBlockedByExecute"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessCandidateValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessEnable"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBlockedByScb"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBlockedByReturn"))
    assert(sv.contains("io_reducedLoadReplayLiqSourceReturnSourceReturned"))
    assert(sv.contains("io_reducedLoadReplayLiqSourceReturnBlockedByStoreSnapshot"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetAvailable"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetBlockedByBudgetDisabled"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetBlockedByConsumer"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipePermitPipeBudgetAvailable"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipePermitBlockedByPipeBudget"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeAvailableMask"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBlockedByNoPipe"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnReadinessReady"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnReadinessBlockedByReturnPipe"))
    assert(sv.contains("io_reducedLoadReplayLiqE4UpdateValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLhqRecordValid"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupRequestByteMask"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLineValidMask"))
    assert(sv.contains("io_reducedLoadReplayLiqResidentCount"))
    assert(sv.contains("io_reducedLoadReplayResolveQueuePushAccepted"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueClearAccepted"))
    assert(sv.contains("io_reducedLoadReplayResolveQueuePreciseFlushValid"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueFlushPruneCount"))
    assert(sv.contains("io_reducedMdbConflictActiveCandidateMask"))
    assert(sv.contains("io_reducedMdbConflictResolveCandidateMask"))
    assert(sv.contains("io_reducedMdbConflictInnerFlush"))
    assert(sv.contains("io_reducedMdbFanoutLookupAccepted"))
    assert(sv.contains("io_reducedMdbFanoutLookupProcessed"))
    assert(sv.contains("io_reducedMdbFanoutDeleteReady"))
    assert(sv.contains("io_reducedMdbFanoutPhaseStalledByFanout"))
    assert(sv.contains("io_reducedMdbFanoutLuOutHit"))
    assert(sv.contains("io_reducedMdbFanoutSuOutHit"))
    assert(sv.contains("io_reducedMdbFanoutRecordAccepted"))
    assert(sv.contains("io_reducedMdbFanoutBmdbReportValid"))
    assert(sv.contains("io_reducedMdbFanoutSsitValidMask"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueValidMask"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueHeadPc"))
    assert(sv.contains("io_executeLoadWaitHold"))
    assert(sv.contains("io_storeStqInsertValid"))
  }

  test("reduced-store harness wrapper elaborates the opt-in STQ path") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluReducedStoreTraceTop(
        CoreParams(robEntries = 8, commitWidth = 2),
        mapQDepth = 8)
    )

    assert(sv.contains("module LinxCoreFrontendFetchRfAluReducedStoreTraceTop"))
    assert(sv.contains("module DecodeRenameROBPath"))
    assert(sv.contains("module ReducedStoreExecResultBridge"))
    assert(sv.contains("module ReducedStoreCommitFreeOwner"))
    assert(sv.contains("module STQCommitDrain"))
    assert(sv.contains("module SCBRowBank"))
    assert(sv.contains("module ReducedStoreMemoryOverlay"))
    assert(sv.contains("module ReducedStoreResidentForward"))
    assert(sv.contains("module ResidentStoreForwardStoreSnapshot"))
    assert(sv.contains("module ReducedLoadWaitReplaySlot"))
    assert(sv.contains("module ReducedLoadReplayRelaunchQueue"))
    assert(sv.contains("module ReducedLoadReplayLiqAllocPath"))
    assert(sv.contains("module LoadResolveQueue"))
    assert(sv.contains("module ReducedLoadReplayCompletionDrain"))
    assert(sv.contains("io_reducedStoreDispatchEnabled"))
    assert(sv.contains("io_reducedStoreScbCommitFreeMask"))
    assert(sv.contains("io_reducedStoreMemoryStoreDroppedMask"))
    assert(sv.contains("io_reducedStoreResidentEligibleMask"))
    assert(sv.contains("io_reducedStoreResidentWaitStoreBidValue"))
    assert(sv.contains("io_reducedStoreResidentReplayWakeByteMask"))
    assert(sv.contains("io_reducedLoadWaitReplayStoredWaitPc"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchPc"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchGidValue"))
    assert(sv.contains("io_reducedLoadWaitReplayRelaunchYoungestStoreIdValue"))
    assert(sv.contains("io_reducedLoadReplayQueuePending"))
    assert(sv.contains("io_reducedLoadReplayQueueOutLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutRidValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutYoungestStoreLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayDrainConsumeReady"))
    assert(sv.contains("io_reducedLoadReplayDrainAddrMismatch"))
    assert(sv.contains("io_reducedLoadReplayDrainRidMismatch"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocEnabled"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocConsumeReady"))
    assert(sv.contains("io_reducedLoadReplayLiqOccupiedMask"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchDataHitMask"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchIndex"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReady"))
    assert(sv.contains("io_reducedLoadReplayLiqRepickMask"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedLoadLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupAddr"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseDataReturned"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupGranted"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupBlockedByExecute"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBaseDataReady"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBlockedByBaseLookup"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueCount"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueClearIndex"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueFlushPruneMask"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueHeadAddr"))
    assert(sv.contains("io_executeLoadWaitHold"))
    assert(sv.contains("io_storeStqInsertValid"))
  }

  test("reduced-store replay-LIQ wrapper elaborates allocation consumer diagnostics") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluReducedStoreReplayLiqTraceTop(
        CoreParams(robEntries = 8, commitWidth = 2),
        mapQDepth = 8)
    )

    assert(sv.contains("module LinxCoreFrontendFetchRfAluReducedStoreReplayLiqTraceTop"))
    assert(sv.contains("module ReducedLoadReplayLiqAllocPath"))
    assert(sv.contains("module ReducedLoadReplayLiqAllocAdapter"))
    assert(sv.contains("module ResidentStoreForwardStoreSnapshot"))
    assert(sv.contains("module LoadLookupArbiter"))
    assert(sv.contains("module LoadReplayLaunchReadiness"))
    assert(sv.contains("module LoadReplayReturnConsumerReady"))
    assert(sv.contains("module LoadReplayReturnPipeBudget"))
    assert(sv.contains("module LoadReplayReturnPipePermit"))
    assert(sv.contains("module LoadReplayReturnDataExtract"))
    assert(sv.contains("module LoadReplayReturnPublishReady"))
    assert(sv.contains("module LoadReplayReturnLretPayload"))
    assert(sv.contains("module LoadReplayReturnWritebackCandidate"))
    assert(sv.contains("module LoadReplayReturnWakeupCandidate"))
    assert(sv.contains("module ReducedScalarWritebackArbiter"))
    assert(sv.contains("module LoadReplayReturnSideEffectReady"))
    assert(sv.contains("module LoadReplayReturnPublishControl"))
    assert(sv.contains("module LoadReplayReturnPublishRequest"))
    assert(sv.contains("module LoadInflightQueue"))
    assert(sv.contains("module LoadInflightLaunchSelect"))
    assert(sv.contains("module LoadReplayBaseDataAlign"))
    assert(sv.contains("module LoadResolveQueue"))
    assert(sv.contains("module MDBConflictDetect"))
    assert(sv.contains("module MDBQueueFanout"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocEnabled"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocConsumeReady"))
    assert(sv.contains("io_reducedLoadReplayLiqAllocAccepted"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchCandidateMask"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchDriveValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchAccepted"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedAddr"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedDstPhysTag"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedSpecWakeup"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchSelectedStackValid"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupValid"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupCrossesLine"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupGranted"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLookupBlockedByExecute"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessReady"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBlockedByBaseData"))
    assert(sv.contains("io_reducedLoadReplayLiqLaunchReadinessBlockedByReturn"))
    assert(sv.contains("io_reducedLoadReplayLiqSourceReturnScbSourceReturned"))
    assert(sv.contains("io_reducedLoadReplayLiqSourceReturnBlockedByScb"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnConsumerReady"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnConsumerBlockedByLretSink"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnConsumerBlockedByWakeupSink"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetEnable"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetConsumerReady"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPipeBudgetBlockedBySources"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnDataValid"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPublishReady"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPublishBlockedByData"))
    assert(sv.contains("io_reducedLoadReplayLiqReturnPublishBlockedByConsumer"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPayloadValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPayloadDstPhysTag"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPayloadData"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPayloadWakeupRequired"))
    assert(sv.contains("module LoadReplayReturnPipeW2ResolveFirePayload"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPipeW2ResolveFirePayloadFireValid"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPipeW2ResolveFirePayloadBidValue"))
    assert(sv.contains("io_reducedLoadReplayLiqLretPipeW2ResolveFirePayloadInvalidPayloadWithoutFire"))
    assert(sv.contains("module LoadReplayReturnLretSink"))
    assert(sv.contains("io_reducedLoadReplayLiqLretSinkEnqueueAccepted"))
    assert(sv.contains("io_reducedLoadReplayLiqLretSinkBlockedByDrain"))
    assert(sv.contains("module LoadReplayReturnIexDrainPermit"))
    assert(sv.contains("io_reducedLoadReplayLiqLretDrainPermitReady"))
    assert(sv.contains("io_reducedLoadReplayLiqLretDrainPermitBlockedByPipeFull"))
    assert(sv.contains("io_reducedLoadReplayLiqWritebackValid"))
    assert(sv.contains("io_reducedLoadReplayLiqWritebackIgnoredNonGprDestination"))
    assert(sv.contains("io_reducedLoadReplayLiqWritebackArbiterSelectedExecute"))
    assert(sv.contains("io_reducedLoadReplayLiqWritebackArbiterReplayBlockedByDisabled"))
    assert(sv.contains("io_reducedLoadReplayLiqSideEffectReady"))
    assert(sv.contains("io_reducedLoadReplayLiqSideEffectBlockedByWriteback"))
    assert(sv.contains("io_reducedLoadReplayLiqSideEffectBlockedByWakeup"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishControlArmed"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishControlFire"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishControlBlockedByLiveDisabled"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishRequestValid"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishRequestMask"))
    assert(sv.contains("io_reducedLoadReplayLiqPublishRequestInvalidFireWithoutPayload"))
    assert(sv.contains("io_reducedLoadReplayLiqWakeupValid"))
    assert(sv.contains("io_reducedLoadReplayLiqWakeupReducedGprValid"))
    assert(sv.contains("io_reducedLoadReplayLiqWakeupSuppressedNotRequired"))
    assert(sv.contains("io_reducedLoadReplayLiqMissMask"))
    assert(sv.contains("io_reducedLoadReplayLiqResolvedMask"))
    assert(sv.contains("io_reducedLoadReplayLiqE4MissKind"))
    assert(sv.contains("io_reducedLoadReplayLiqBaseLineValidMask"))
    assert(sv.contains("io_reducedLoadReplayLiqResidentCount"))
    assert(sv.contains("io_reducedLoadReplayResolveQueuePushAccepted"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueClearPending"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueRetireValid"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueRetireLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayResolveQueuePreciseFlushLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueFlushPruneCount"))
    assert(sv.contains("io_reducedMdbConflictStoreValid"))
    assert(sv.contains("io_reducedMdbConflictLoadLsIdValue"))
    assert(sv.contains("io_reducedMdbConflictStoreLsIdValue"))
    assert(sv.contains("io_reducedMdbFanoutLookupReady"))
    assert(sv.contains("io_reducedMdbFanoutLuOutStoreBidValue"))
    assert(sv.contains("io_reducedMdbFanoutSuOutStoreBidValue"))
    assert(sv.contains("io_reducedMdbFanoutRecordProcessed"))
    assert(sv.contains("io_reducedMdbFanoutBmdbLoadBidValue"))
    assert(sv.contains("io_reducedMdbFanoutDeleteDroppedBelowStall"))
    assert(sv.contains("io_reducedMdbFanoutSuWakeupValid"))
    assert(sv.contains("io_reducedLoadReplayResolveQueueHeadLsIdValue"))
    assert(sv.contains("io_reducedLoadReplayQueueOutFire"))
  }

  test("marker-row harness elaborates admitted markers with decode-time BID context") {
    val sv = ChiselStage.emitSystemVerilog(
      new LinxCoreFrontendFetchRfAluMarkerRowsTraceTop(CoreParams(robEntries = 8, commitWidth = 2), mapQDepth = 8)
    )

    assert(sv.contains("module LinxCoreFrontendFetchRfAluMarkerRowsTraceTop"))
    assert(sv.contains("module DecodeRenameROBPath"))
    assert(sv.contains("module BlockMarkerDecodeContext"))
    assert(sv.contains("io_decodeValid"))
    assert(sv.contains("io_decodeFire"))
    assert(sv.contains("io_decodeBlockBid"))
    assert(sv.contains("io_decodeUsesExistingBlock"))
    assert(sv.contains("io_robRenameUpdateReady"))
    assert(sv.contains("io_executeCompleteValid"))
    assert(sv.contains("io_blockMarkerSkipValid"))
    assert(sv.contains("io_admittedMarkerDrainBarrier"))
  }
}
