from __future__ import annotations

from pycircuit import Circuit, Wire, function, module


@function
def mask_bit(m: Circuit, *, mask: Wire, idx: Wire, width: int) -> Wire:
    """Return mask[idx] as i1, using a linear mux chain."""
    c = m.const
    out = c(0, width=1)
    for i in range(int(width)):
        out = mask[i] if (idx == c(i, width=idx.width)) else out
    return out


@function
def onehot_from_tag(m: Circuit, *, tag: Wire, width: int, tag_width: int) -> Wire:
    c = m.const
    out = c(0, width=width)
    for i in range(int(width)):
        out = c(1 << i, width=width) if (tag == c(i, width=tag_width)) else out
    return out


@module(name="JanusBccBlockStructBrob")
def build_janus_bcc_block_struct_brob(
    m: Circuit,
    *,
    slots: int = 16,
    bid_w: int = 64,
    blocktype_w: int = 4,
    trap_cause_w: int = 32,
) -> None:
    """Signal-level BROB.

    Contract (from channel history):
    - scalar_done is generated by ROB retire of EOB uops (scalar/cmd side)
    - engine_done is generated by engine completion (vec/tma/cube/tau)
    - engine blocks are complete iff scalar_done & engine_done
    - scalar-only blocks are complete iff scalar_done

    Slot mapping convention:
    - low bits of BID encode the BROB slot id (slots=16 => bid[3:0]).
    """

    clk = m.clock("clk")
    rst = m.reset("rst")
    c = m.const

    # --- Allocate (from decode/BSTART)
    alloc_valid = m.input("alloc_valid", width=1)
    alloc_bid = m.input("alloc_bid", width=bid_w)
    alloc_blocktype = m.input("alloc_blocktype", width=blocktype_w)
    alloc_needs_engine = m.input("alloc_needs_engine", width=1)

    # --- Scalar completion (from ROB retire)
    scalar_done_valid = m.input("scalar_done_valid", width=1)
    scalar_done_bid = m.input("scalar_done_bid", width=bid_w)
    scalar_done_trap_valid = m.input("scalar_done_trap_valid", width=1)
    scalar_done_trap_cause = m.input("scalar_done_trap_cause", width=trap_cause_w)

    # --- Engine completion (from engine)
    engine_done_valid = m.input("engine_done_valid", width=1)
    engine_done_bid = m.input("engine_done_bid", width=bid_w)
    engine_done_trap_valid = m.input("engine_done_trap_valid", width=1)
    engine_done_trap_cause = m.input("engine_done_trap_cause", width=trap_cause_w)

    # --- Retire/free (from ROB commit of boundary)
    retire_valid = m.input("retire_valid", width=1)
    retire_bid = m.input("retire_bid", width=bid_w)

    # --- Query (for BSTOP retirement gate / debug)
    query_valid = m.input("query_valid", width=1)
    query_bid = m.input("query_bid", width=bid_w)

    # ---- Per-slot state
    allocated = m.out("allocated", clk=clk, rst=rst, width=slots, init=c(0, width=slots), en=c(1, width=1))
    scalar_done = m.out("scalar_done", clk=clk, rst=rst, width=slots, init=c(0, width=slots), en=c(1, width=1))
    engine_done = m.out("engine_done", clk=clk, rst=rst, width=slots, init=c(0, width=slots), en=c(1, width=1))
    needs_engine = m.out("needs_engine", clk=clk, rst=rst, width=slots, init=c(0, width=slots), en=c(1, width=1))
    exception = m.out("exception", clk=clk, rst=rst, width=slots, init=c(0, width=slots), en=c(1, width=1))

    bid_slot = []
    blocktype_slot = []
    trap_cause_slot = []
    for i in range(int(slots)):
        bid_slot.append(m.out(f"bid{i}", clk=clk, rst=rst, width=bid_w, init=c(0, width=bid_w), en=c(1, width=1)))
        blocktype_slot.append(m.out(f"blocktype{i}", clk=clk, rst=rst, width=blocktype_w, init=c(0, width=blocktype_w), en=c(1, width=1)))
        trap_cause_slot.append(m.out(f"trap_cause{i}", clk=clk, rst=rst, width=trap_cause_w, init=c(0, width=trap_cause_w), en=c(1, width=1)))

    alloc_slot = alloc_bid[0:4]
    scalar_slot = scalar_done_bid[0:4]
    engine_slot = engine_done_bid[0:4]
    retire_slot = retire_bid[0:4]
    query_slot = query_bid[0:4]

    alloc_onehot = onehot_from_tag(m, tag=alloc_slot, width=slots, tag_width=4)
    scalar_hit = onehot_from_tag(m, tag=scalar_slot, width=slots, tag_width=4)
    engine_hit = onehot_from_tag(m, tag=engine_slot, width=slots, tag_width=4)
    retire_hit = onehot_from_tag(m, tag=retire_slot, width=slots, tag_width=4)
    query_hit = onehot_from_tag(m, tag=query_slot, width=slots, tag_width=4)

    # Optional safety: don't allow alloc to clobber an in-use entry.
    alloc_busy = mask_bit(m, mask=allocated.out(), idx=alloc_slot, width=slots)
    alloc_ok = ~alloc_busy
    alloc_fire = alloc_valid & alloc_ok

    scalar_fire = scalar_done_valid
    engine_fire = engine_done_valid

    # Next-state
    alloc_next = allocated.out()
    scalar_next = scalar_done.out()
    engine_next = engine_done.out()
    needs_engine_next = needs_engine.out()
    exc_next = exception.out()

    # Allocation writes
    alloc_next = (alloc_next | alloc_onehot) if alloc_fire else alloc_next
    # Clear done/exception bits for allocated slot
    scalar_next = (scalar_next & (~alloc_onehot)) if alloc_fire else scalar_next
    engine_next = (engine_next & (~alloc_onehot)) if alloc_fire else engine_next
    exc_next = (exc_next & (~alloc_onehot)) if alloc_fire else exc_next
    needs_engine_bits = alloc_onehot if alloc_needs_engine else c(0, width=slots)
    needs_engine_next = ((needs_engine_next & (~alloc_onehot)) | needs_engine_bits) if alloc_fire else needs_engine_next

    # Scalar completion sets scalar_done, may set exception
    scalar_next = (scalar_next | scalar_hit) if scalar_fire else scalar_next
    exc_next = (exc_next | scalar_hit) if (scalar_fire & scalar_done_trap_valid) else exc_next

    # Engine completion sets engine_done, may set exception
    engine_next = (engine_next | engine_hit) if engine_fire else engine_next
    exc_next = (exc_next | engine_hit) if (engine_fire & engine_done_trap_valid) else exc_next

    # Retire/free: only allow freeing allocated entries (gated by allocated bit)
    retire_fire = retire_valid
    retire_mask = retire_hit & allocated.out()
    alloc_next = (alloc_next & (~retire_mask)) if retire_fire else alloc_next
    scalar_next = (scalar_next & (~retire_mask)) if retire_fire else scalar_next
    engine_next = (engine_next & (~retire_mask)) if retire_fire else engine_next
    needs_engine_next = (needs_engine_next & (~retire_mask)) if retire_fire else needs_engine_next
    exc_next = (exc_next & (~retire_mask)) if retire_fire else exc_next

    allocated.set(alloc_next)
    scalar_done.set(scalar_next)
    engine_done.set(engine_next)
    needs_engine.set(needs_engine_next)
    exception.set(exc_next)

    # Slot payload updates
    for i in range(int(slots)):
        slot_i = c(i, width=4)
        slot_hit = alloc_slot == slot_i
        do_write = alloc_fire & slot_hit
        bid_slot[i].set(alloc_bid, when=do_write)
        blocktype_slot[i].set(alloc_blocktype, when=do_write)

        # Trap cause capture: keep last writer (scalar/engine). Exception bit indicates valid.
        trap_cause_slot[i].set(scalar_done_trap_cause, when=scalar_fire & scalar_done_trap_valid & scalar_hit[i])
        trap_cause_slot[i].set(engine_done_trap_cause, when=engine_fire & engine_done_trap_valid & engine_hit[i])

    # Completion / readiness
    complete_mask = scalar_next & ((~needs_engine_next) | engine_next)
    pending_mask = alloc_next & (~complete_mask)

    # Query: priority-encode the slot.
    query_any = query_valid & (query_hit != c(0, width=slots))
    qv = c(0, width=1)
    query_idx = c(0, width=4)
    for i in range(int(slots)):
        take = query_hit[i] & (~qv)
        qv = c(1, width=1) if take else qv
        query_idx = c(i, width=4) if take else query_idx

    q_alloc_bit = query_any & mask_bit(m, mask=alloc_next, idx=query_idx, width=slots)
    q_scalar_bit = query_any & mask_bit(m, mask=scalar_next, idx=query_idx, width=slots)
    q_engine_bit = query_any & mask_bit(m, mask=engine_next, idx=query_idx, width=slots)
    q_needs_engine_bit = query_any & mask_bit(m, mask=needs_engine_next, idx=query_idx, width=slots)
    q_exc_bit = query_any & mask_bit(m, mask=exc_next, idx=query_idx, width=slots)
    q_complete_bit = query_any & (q_scalar_bit & ((~q_needs_engine_bit) | q_engine_bit))

    q_blocktype = c(0, width=blocktype_w)
    q_trap_cause = c(0, width=trap_cause_w)
    for i in range(int(slots)):
        is_i = query_idx == c(i, width=4)
        q_blocktype = blocktype_slot[i].out() if is_i else q_blocktype
        q_trap_cause = trap_cause_slot[i].out() if is_i else q_trap_cause

    m.output("alloc_ok", alloc_ok)
    m.output("alloc_fire", alloc_fire)
    m.output("alloc_slot", alloc_slot)
    m.output("pending_mask", pending_mask)
    m.output("complete_mask", complete_mask)

    m.output("query_alloc", q_alloc_bit)
    m.output("query_scalar_done", q_scalar_bit)
    m.output("query_engine_done", q_engine_bit)
    m.output("query_needs_engine", q_needs_engine_bit)
    m.output("query_exception", q_exc_bit)
    m.output("query_complete", q_complete_bit)
    m.output("query_blocktype", q_blocktype)
    m.output("query_trap_cause", q_trap_cause)
