from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class InterfaceField:
    name: str
    width: int


InterfaceSpec = Dict[str, Tuple[InterfaceField, ...]]

# Canonical dynamic-uop metadata fields for DFX pipeview.
UOP_UID_FIELDS: Tuple[InterfaceField, ...] = (
    InterfaceField("uop_uid", 64),
    InterfaceField("uop_parent_uid", 64),
    InterfaceField("uop_kind", 3),
    InterfaceField("uop_fetch_packet_uid", 64),
    InterfaceField("uop_fetch_slot", 3),
    InterfaceField("uop_replay_depth", 8),
    InterfaceField("uop_template_kind", 3),
)


INTERFACE_SPEC: InterfaceSpec = {
    "f0_to_f1_stage": (
        InterfaceField("pc", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("redirect", 1),
    ),
    "f1_to_f2_stage": (
        InterfaceField("pc", 64),
        InterfaceField("bundle128", 1024),
        InterfaceField("bundle_base_pc", 64),
        InterfaceField("slot_base_offset", 7),
        InterfaceField("hit", 1),
        InterfaceField("miss", 1),
        InterfaceField("stall", 1),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
    ),
    "f2_to_f3_stage": (
        InterfaceField("pc", 64),
        InterfaceField("window", 64),
        InterfaceField("bundle128", 1024),
        InterfaceField("bundle_base_pc", 64),
        InterfaceField("slot_base_offset", 7),
        InterfaceField("next_pc", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
    ),
    "f3_to_ib_stage": (
        InterfaceField("pc", 64),
        InterfaceField("window", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("checkpoint_id", 6),
    ),
    "ib_to_f4_stage": (
        InterfaceField("pc", 64),
        InterfaceField("window", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("checkpoint_id", 6),
    ),
    "f3_to_f4_stage": (
        InterfaceField("pc", 64),
        InterfaceField("window", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("checkpoint_id", 6),
    ),
    "f3_to_pcb_stage": (
        InterfaceField("bstart_valid", 1),
        InterfaceField("bstart_pc", 64),
        InterfaceField("bstart_kind", 3),
        InterfaceField("bstart_block_kind", 3),
        InterfaceField("bstart_branch_kind", 3),
        InterfaceField("bstart_target", 64),
        InterfaceField("pred_take", 1),
    ),
    "f4_to_d1_stage": (
        InterfaceField("pc", 64),
        InterfaceField("window", 64),
        InterfaceField("pkt_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("checkpoint_id", 6),
    ),
    "d1_to_d2_stage": (
        InterfaceField("op", 12),
        InterfaceField("pc", 64),
        InterfaceField("uop_uid", 64),
        InterfaceField("valid", 1),
    ),
    "d2_to_d3_stage": (
        InterfaceField("op", 12),
        InterfaceField("pc", 64),
        InterfaceField("uop_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("regdst", 6),
        InterfaceField("block_uid", 64),
        InterfaceField("block_bid", 64),
        InterfaceField("load_store_id", 32),
    ),
    "d3_to_s1_stage": (
        InterfaceField("op", 12),
        InterfaceField("pc", 64),
        InterfaceField("uop_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("rob", 6),
        InterfaceField("block_uid", 64),
        InterfaceField("block_bid", 64),
        InterfaceField("load_store_id", 32),
    ),
    "s1_to_s2_stage": (
        InterfaceField("op", 12),
        InterfaceField("pc", 64),
        InterfaceField("uop_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("iq", 5),
        InterfaceField("block_uid", 64),
        InterfaceField("block_bid", 64),
        InterfaceField("load_store_id", 32),
    ),
    "s2_to_iex_stage": (
        InterfaceField("op", 12),
        InterfaceField("pc", 64),
        InterfaceField("uop_uid", 64),
        InterfaceField("valid", 1),
        InterfaceField("rob", 6),
        InterfaceField("block_uid", 64),
        InterfaceField("block_bid", 64),
        InterfaceField("load_store_id", 32),
    ),
    "iex_to_rob_stage": (
        InterfaceField("wb_valid", 1),
        InterfaceField("wb_rob", 6),
        InterfaceField("wb_value", 64),
        InterfaceField("store_valid", 1),
        InterfaceField("load_valid", 1),
    ),
    "rob_to_flush_ctrl_stage": (
        InterfaceField("redirect_valid", 1),
        InterfaceField("redirect_pc", 64),
        InterfaceField("checkpoint_id", 6),
    ),
    "bctrl_to_pe_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "pe_to_brob_stage": (
        InterfaceField("rsp_valid", 1),
        InterfaceField("rsp_tag", 8),
        InterfaceField("rsp_status", 4),
        InterfaceField("rsp_data0", 64),
        InterfaceField("rsp_data1", 64),
        InterfaceField("rsp_trap_valid", 1),
        InterfaceField("rsp_trap_cause", 32),
    ),
    "lsu_to_rob_stage": (
        InterfaceField("load_valid", 1),
        InterfaceField("load_rob", 6),
        InterfaceField("load_addr", 64),
        InterfaceField("load_data", 64),
        InterfaceField("load_lsid", 32),
        InterfaceField("store_valid", 1),
        InterfaceField("store_rob", 6),
        InterfaceField("store_lsid", 32),
    ),
    "pcb_to_bru_stage": (
        InterfaceField("lookup_hit", 1),
        InterfaceField("lookup_kind", 3),
        InterfaceField("lookup_target", 64),
        InterfaceField("lookup_pred_take", 1),
    ),
    "cmd_to_bisq_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_src_rob", 6),
    ),
    "bisq_to_bctrl_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "bctrl_to_tma_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "bctrl_to_cube_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "bctrl_to_vec_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "bctrl_to_tau_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("cmd_kind", 3),
        InterfaceField("cmd_tag", 8),
        InterfaceField("cmd_bid", 64),
        InterfaceField("cmd_tile", 6),
        InterfaceField("cmd_payload", 64),
        InterfaceField("cmd_src_rob", 6),
        InterfaceField("cmd_epoch", 8),
    ),
    "tmu_to_pe_stage": (
        InterfaceField("cmd_valid", 1),
        InterfaceField("cmd_ready", 1),
        InterfaceField("tile_data", 64),
    ),
    "pe_to_tmu_stage": (
        InterfaceField("wr_valid", 1),
        InterfaceField("wr_tile", 6),
        InterfaceField("wr_data", 64),
    ),
    "brob_to_rob_stage": (
        InterfaceField("rsp_valid", 1),
        InterfaceField("rsp_tag", 8),
        InterfaceField("rsp_bid", 64),
        InterfaceField("rsp_status", 4),
        InterfaceField("rsp_data0", 64),
        InterfaceField("rsp_data1", 64),
        InterfaceField("rsp_trap_valid", 1),
        InterfaceField("rsp_trap_cause", 32),
        InterfaceField("brob_state", 4),
        InterfaceField("brob_ready", 1),
        InterfaceField("brob_exception", 1),
        InterfaceField("brob_retired", 1),
    ),
}


def iter_signal_names(prefix: str) -> Tuple[str, ...]:
    fields = INTERFACE_SPEC[prefix]
    return tuple(f"{prefix}_{field.name}" for field in fields)
