from __future__ import annotations

# AUTO-GENERATED FILE. DO NOT EDIT.

OP_INVALID = 0
OP_BSTART_CUBE = 1
OP_BSTART_FALL = 2
OP_BSTART_FIXP = 3
OP_BSTART_FP_CALL = 4
OP_BSTART_FP_COND = 5
OP_BSTART_FP_DIRECT = 6
OP_BSTART_FP_FALL = 7
OP_BSTART_FP_ICALL = 8
OP_BSTART_FP_IND = 9
OP_BSTART_FP_RET = 10
OP_BSTART_ICALL = 11
OP_BSTART_IND = 12
OP_BSTART_MPAR = 13
OP_BSTART_MSEQ = 14
OP_BSTART_RET = 15
OP_BSTART_SPLIT_COND = 16
OP_BSTART_SPLIT_DIRECT = 17
OP_BSTART_STD_CALL = 18
OP_BSTART_STD_COND = 19
OP_BSTART_STD_DIRECT = 20
OP_BSTART_SYS = 21
OP_BSTART_TEPL = 22
OP_BSTART_TMA = 23
OP_BSTART_VPAR = 24
OP_BSTART_VSEQ = 25
OP_C_BSTART_COND = 26
OP_C_BSTART_DIRECT = 27
OP_C_BSTART_FP = 28
OP_C_BSTART_MPAR = 29
OP_C_BSTART_MSEQ = 30
OP_C_BSTART_STD_CALL = 31
OP_C_BSTART_STD_COND = 32
OP_C_BSTART_STD_DIRECT = 33
OP_C_BSTART_STD_FALL = 34
OP_C_BSTART_STD_ICALL = 35
OP_C_BSTART_STD_IND = 36
OP_C_BSTART_STD_RET = 37
OP_C_BSTART_SYS = 38
OP_C_BSTART_VPAR = 39
OP_C_BSTART_VSEQ = 40
OP_C_BSTOP = 41
OP_B_ARG = 42
OP_B_ARG_DN2NZ = 43
OP_B_ARG_DN2ZN = 44
OP_B_ARG_ND2ZN = 45
OP_B_ARG_NORM = 46
OP_B_ARG_NZ2DN = 47
OP_B_CATR = 48
OP_B_DATR = 49
OP_B_DIM_LB0 = 50
OP_B_DIM_LB1 = 51
OP_B_DIM_LB2 = 52
OP_B_EQ = 53
OP_B_GE = 54
OP_B_GEU = 55
OP_B_HINT = 56
OP_B_HINT_TRACE = 57
OP_B_LT = 58
OP_B_LTU = 59
OP_B_NE = 60
OP_ADD = 61
OP_ADDI = 62
OP_ADDIW = 63
OP_ADDW = 64
OP_AND = 65
OP_ANDI = 66
OP_ANDIW = 67
OP_ANDW = 68
OP_BCNT = 69
OP_BIC = 70
OP_BIS = 71
OP_BSTART_STD_FALL = 72
OP_BXS = 73
OP_BXU = 74
OP_CASB = 75
OP_CASD = 76
OP_CASH = 77
OP_CASW = 78
OP_CLZ = 79
OP_CSEL = 80
OP_CTZ = 81
OP_DIV = 82
OP_DIVU = 83
OP_DIVUW = 84
OP_DIVW = 85
OP_DMA = 86
OP_HL_ADDI = 87
OP_HL_ADDIW = 88
OP_HL_ANDI = 89
OP_HL_ANDIW = 90
OP_HL_BFI = 91
OP_HL_BSTART_FP_CALL = 92
OP_HL_BSTART_FP_COND = 93
OP_HL_BSTART_FP_DIRECT = 94
OP_HL_BSTART_FP_FALL = 95
OP_HL_BSTART_SYS = 96
OP_HL_CASB = 97
OP_HL_CASD = 98
OP_HL_CASH = 99
OP_HL_CASW = 100
OP_HL_CCAT = 101
OP_HL_CCATW = 102
OP_HL_CMP_ANDI = 103
OP_HL_CMP_EQI = 104
OP_HL_CMP_GEI = 105
OP_HL_CMP_GEUI = 106
OP_HL_CMP_LTI = 107
OP_HL_CMP_LTUI = 108
OP_HL_CMP_NEI = 109
OP_HL_CMP_ORI = 110
OP_HL_DIV = 111
OP_HL_DIVU = 112
OP_HL_DIVUW = 113
OP_HL_DIVW = 114
OP_HL_LBI = 115
OP_HL_LBIP = 116
OP_HL_LBI_PO = 117
OP_HL_LBI_PR = 118
OP_HL_LBP = 119
OP_HL_LBUI = 120
OP_HL_LBUIP = 121
OP_HL_LBUI_PO = 122
OP_HL_LBUI_PR = 123
OP_HL_LBUP = 124
OP_HL_LBU_PO = 125
OP_HL_LBU_PR = 126
OP_HL_LB_PO = 127
OP_HL_LB_PR = 128
OP_HL_LDI = 129
OP_HL_LDIP = 130
OP_HL_LDIP_U = 131
OP_HL_LDI_PO = 132
OP_HL_LDI_PR = 133
OP_HL_LDI_U = 134
OP_HL_LDI_UPO = 135
OP_HL_LDI_UPR = 136
OP_HL_LDP = 137
OP_HL_LD_PO = 138
OP_HL_LD_PR = 139
OP_HL_LHI = 140
OP_HL_LHIP = 141
OP_HL_LHIP_U = 142
OP_HL_LHI_PO = 143
OP_HL_LHI_PR = 144
OP_HL_LHI_U = 145
OP_HL_LHI_UPO = 146
OP_HL_LHI_UPR = 147
OP_HL_LHP = 148
OP_HL_LHUI = 149
OP_HL_LHUIP = 150
OP_HL_LHUIP_U = 151
OP_HL_LHUI_PO = 152
OP_HL_LHUI_PR = 153
OP_HL_LHUI_U = 154
OP_HL_LHUI_UPO = 155
OP_HL_LHUI_UPR = 156
OP_HL_LHUP = 157
OP_HL_LHU_PO = 158
OP_HL_LHU_PR = 159
OP_HL_LH_PO = 160
OP_HL_LH_PR = 161
OP_HL_LIS = 162
OP_HL_LIU = 163
OP_HL_LUI = 164
OP_HL_LWI = 165
OP_HL_LWIP = 166
OP_HL_LWIP_U = 167
OP_HL_LWI_PO = 168
OP_HL_LWI_PR = 169
OP_HL_LWI_U = 170
OP_HL_LWI_UPO = 171
OP_HL_LWI_UPR = 172
OP_HL_LWP = 173
OP_HL_LWUI = 174
OP_HL_LWUIP = 175
OP_HL_LWUIP_U = 176
OP_HL_LWUI_PO = 177
OP_HL_LWUI_PR = 178
OP_HL_LWUI_U = 179
OP_HL_LWUI_UPO = 180
OP_HL_LWUI_UPR = 181
OP_HL_LWUP = 182
OP_HL_LWU_PO = 183
OP_HL_LWU_PR = 184
OP_HL_LW_PO = 185
OP_HL_LW_PR = 186
OP_HL_MADD = 187
OP_HL_MADDW = 188
OP_HL_MIADD = 189
OP_HL_MISUB = 190
OP_HL_MUL = 191
OP_HL_MULU = 192
OP_HL_ORI = 193
OP_HL_ORIW = 194
OP_HL_PRF = 195
OP_HL_PRFI_U = 196
OP_HL_PRFI_UA = 197
OP_HL_PRF_A = 198
OP_HL_QMT = 199
OP_HL_QPOP = 200
OP_HL_QPUSH = 201
OP_HL_REM = 202
OP_HL_REMU = 203
OP_HL_REMUW = 204
OP_HL_REMW = 205
OP_HL_SBI = 206
OP_HL_SBIP = 207
OP_HL_SBI_PO = 208
OP_HL_SBI_PR = 209
OP_HL_SBP = 210
OP_HL_SB_PO = 211
OP_HL_SB_PR = 212
OP_HL_SDI = 213
OP_HL_SDIP = 214
OP_HL_SDIP_U = 215
OP_HL_SDI_PO = 216
OP_HL_SDI_PR = 217
OP_HL_SDI_U = 218
OP_HL_SDI_UPO = 219
OP_HL_SDI_UPR = 220
OP_HL_SDP = 221
OP_HL_SDP_U = 222
OP_HL_SD_PO = 223
OP_HL_SD_PR = 224
OP_HL_SD_UPO = 225
OP_HL_SD_UPR = 226
OP_HL_SETC_ANDI = 227
OP_HL_SETC_EQI = 228
OP_HL_SETC_GEI = 229
OP_HL_SETC_GEUI = 230
OP_HL_SETC_LTI = 231
OP_HL_SETC_LTUI = 232
OP_HL_SETC_NEI = 233
OP_HL_SETC_ORI = 234
OP_HL_SETRET = 235
OP_HL_SHI = 236
OP_HL_SHIP = 237
OP_HL_SHIP_U = 238
OP_HL_SHI_PO = 239
OP_HL_SHI_PR = 240
OP_HL_SHI_U = 241
OP_HL_SHI_UPO = 242
OP_HL_SHI_UPR = 243
OP_HL_SHP = 244
OP_HL_SHP_U = 245
OP_HL_SH_PO = 246
OP_HL_SH_PR = 247
OP_HL_SH_UPO = 248
OP_HL_SH_UPR = 249
OP_HL_SUBI = 250
OP_HL_SUBIW = 251
OP_HL_SWI = 252
OP_HL_SWIP = 253
OP_HL_SWIP_U = 254
OP_HL_SWI_PO = 255
OP_HL_SWI_PR = 256
OP_HL_SWI_U = 257
OP_HL_SWI_UPO = 258
OP_HL_SWI_UPR = 259
OP_HL_SWP = 260
OP_HL_SWP_U = 261
OP_HL_SW_PO = 262
OP_HL_SW_PR = 263
OP_HL_SW_UPO = 264
OP_HL_SW_UPR = 265
OP_HL_XORI = 266
OP_HL_XORIW = 267
OP_LUI = 268
OP_MUL = 269
OP_MULU = 270
OP_MULUW = 271
OP_MULW = 272
OP_OR = 273
OP_ORI = 274
OP_ORIW = 275
OP_ORW = 276
OP_REM = 277
OP_REMU = 278
OP_REMUW = 279
OP_REMW = 280
OP_SLL = 281
OP_SLLI = 282
OP_SLLIW = 283
OP_SLLW = 284
OP_SRA = 285
OP_SRAI = 286
OP_SRAIW = 287
OP_SRAW = 288
OP_SRL = 289
OP_SRLI = 290
OP_SRLIW = 291
OP_SRLW = 292
OP_SUB = 293
OP_SUBI = 294
OP_SUBIW = 295
OP_SUBW = 296
OP_XOR = 297
OP_XORI = 298
OP_XORIW = 299
OP_XORW = 300
OP_ADDTPC = 301
OP_B_NZ = 302
OP_B_Z = 303
OP_CMP_AND = 304
OP_CMP_ANDI = 305
OP_CMP_EQ = 306
OP_CMP_EQI = 307
OP_CMP_GE = 308
OP_CMP_GEI = 309
OP_CMP_GEU = 310
OP_CMP_GEUI = 311
OP_CMP_LT = 312
OP_CMP_LTI = 313
OP_CMP_LTU = 314
OP_CMP_LTUI = 315
OP_CMP_NE = 316
OP_CMP_NEI = 317
OP_CMP_OR = 318
OP_CMP_ORI = 319
OP_C_CMP_EQI = 320
OP_C_CMP_NEI = 321
OP_C_SETC_EQ = 322
OP_C_SETC_NE = 323
OP_C_SETC_TGT = 324
OP_HL_ADDTPC = 325
OP_SETC_AND = 326
OP_SETC_ANDI = 327
OP_SETC_EQ = 328
OP_SETC_EQI = 329
OP_SETC_GE = 330
OP_SETC_GEI = 331
OP_SETC_GEU = 332
OP_SETC_GEUI = 333
OP_SETC_LT = 334
OP_SETC_LTI = 335
OP_SETC_LTU = 336
OP_SETC_LTUI = 337
OP_SETC_NE = 338
OP_SETC_NEI = 339
OP_SETC_OR = 340
OP_SETC_ORI = 341
OP_SETC_TGT = 342
OP_SETRET = 343
OP_LB = 344
OP_LBI = 345
OP_LBU = 346
OP_LBUI = 347
OP_LBU_PCR = 348
OP_LB_PCR = 349
OP_LD = 350
OP_LDI = 351
OP_LDI_U = 352
OP_LD_ADD = 353
OP_LD_AND = 354
OP_LD_OR = 355
OP_LD_PCR = 356
OP_LD_SMAX = 357
OP_LD_SMIN = 358
OP_LD_UMAX = 359
OP_LD_UMIN = 360
OP_LD_XOR = 361
OP_LH = 362
OP_LHI = 363
OP_LHI_U = 364
OP_LHU = 365
OP_LHUI = 366
OP_LHUI_U = 367
OP_LHU_PCR = 368
OP_LH_PCR = 369
OP_LW = 370
OP_LWI = 371
OP_LWI_U = 372
OP_LWU = 373
OP_LWUI = 374
OP_LWUI_U = 375
OP_LWU_PCR = 376
OP_LW_ADD = 377
OP_LW_AND = 378
OP_LW_OR = 379
OP_LW_PCR = 380
OP_LW_SMAX = 381
OP_LW_SMIN = 382
OP_LW_UMAX = 383
OP_LW_UMIN = 384
OP_LW_XOR = 385
OP_SB = 386
OP_SBI = 387
OP_SB_PCR = 388
OP_SD = 389
OP_SDI = 390
OP_SDI_U = 391
OP_SD_ADD = 392
OP_SD_AND = 393
OP_SD_OR = 394
OP_SD_PCR = 395
OP_SD_SMAX = 396
OP_SD_SMIN = 397
OP_SD_U = 398
OP_SD_UMAX = 399
OP_SD_UMIN = 400
OP_SD_XOR = 401
OP_SH = 402
OP_SHI = 403
OP_SHI_U = 404
OP_SH_PCR = 405
OP_SH_U = 406
OP_SW = 407
OP_SWAPB = 408
OP_SWAPD = 409
OP_SWAPH = 410
OP_SWAPW = 411
OP_SWI = 412
OP_SWI_U = 413
OP_SW_ADD = 414
OP_SW_AND = 415
OP_SW_OR = 416
OP_SW_PCR = 417
OP_SW_SMAX = 418
OP_SW_SMIN = 419
OP_SW_U = 420
OP_SW_UMAX = 421
OP_SW_UMIN = 422
OP_SW_XOR = 423
OP_BIOR = 424
OP_BTEXT = 425
OP_B_IOT = 426
OP_ERCOV = 427
OP_ESAVE = 428
OP_FENTRY = 429
OP_FEXIT = 430
OP_FRET_RA = 431
OP_FRET_STK = 432
OP_MCOPY = 433
OP_MSET = 434
OP_HL_LBU_PCR = 435
OP_HL_LB_PCR = 436
OP_HL_LD_PCR = 437
OP_HL_LHU_PCR = 438
OP_HL_LH_PCR = 439
OP_HL_LWU_PCR = 440
OP_HL_LW_PCR = 441
OP_HL_SB_PCR = 442
OP_HL_SD_PCR = 443
OP_HL_SH_PCR = 444
OP_HL_SW_PCR = 445
OP_V_ADD = 446
OP_V_ADDI = 447
OP_V_AND = 448
OP_V_ANDI = 449
OP_V_BCNT = 450
OP_V_BIC = 451
OP_V_BIS = 452
OP_V_BXS = 453
OP_V_BXU = 454
OP_V_CLZ = 455
OP_V_CMP_AND = 456
OP_V_CMP_ANDI = 457
OP_V_CMP_EQ = 458
OP_V_CMP_EQI = 459
OP_V_CMP_GE = 460
OP_V_CMP_GEI = 461
OP_V_CMP_GEU = 462
OP_V_CMP_GEUI = 463
OP_V_CMP_LT = 464
OP_V_CMP_LTI = 465
OP_V_CMP_LTU = 466
OP_V_CMP_LTUI = 467
OP_V_CMP_NE = 468
OP_V_CMP_NEI = 469
OP_V_CMP_OR = 470
OP_V_CMP_ORI = 471
OP_V_CSEL = 472
OP_V_CTZ = 473
OP_V_DIV = 474
OP_V_FABS = 475
OP_V_FADD = 476
OP_V_FCLASS = 477
OP_V_FCVT = 478
OP_V_FCVTI = 479
OP_V_FDIV = 480
OP_V_FEQ = 481
OP_V_FEQS = 482
OP_V_FEXP = 483
OP_V_FGE = 484
OP_V_FGES = 485
OP_V_FLT = 486
OP_V_FLTS = 487
OP_V_FMADD = 488
OP_V_FMAX = 489
OP_V_FMIN = 490
OP_V_FMSUB = 491
OP_V_FMUL = 492
OP_V_FNE = 493
OP_V_FNES = 494
OP_V_FNMADD = 495
OP_V_FNMSUB = 496
OP_V_FRECIP = 497
OP_V_FSQRT = 498
OP_V_FSUB = 499
OP_V_ICVT = 500
OP_V_ICVTF = 501
OP_V_LB = 502
OP_V_LBU = 503
OP_V_LBU_BRG = 504
OP_V_LB_BRG = 505
OP_V_LH = 506
OP_V_LHU = 507
OP_V_LHU_BRG = 508
OP_V_LH_BRG = 509
OP_V_LW = 510
OP_V_LW_BRG = 511
OP_V_MADD = 512
OP_V_MAX = 513
OP_V_MIN = 514
OP_V_MUL = 515
OP_V_OR = 516
OP_V_ORI = 517
OP_V_PSEL = 518
OP_V_RDADD = 519
OP_V_RDAND = 520
OP_V_RDFADD = 521
OP_V_RDFMAX = 522
OP_V_RDFMIN = 523
OP_V_RDMAX = 524
OP_V_RDMIN = 525
OP_V_RDOR = 526
OP_V_RDXOR = 527
OP_V_REM = 528
OP_V_REV = 529
OP_V_SB = 530
OP_V_SB_BRG = 531
OP_V_SH = 532
OP_V_SH_BRG = 533
OP_V_SLL = 534
OP_V_SLLI = 535
OP_V_SRA = 536
OP_V_SRAI = 537
OP_V_SRL = 538
OP_V_SRLI = 539
OP_V_SUB = 540
OP_V_SUBI = 541
OP_V_SW = 542
OP_V_SW_BRG = 543
OP_V_XOR = 544
OP_V_XORI = 545
OP_ACRC = 546
OP_ACRE = 547
OP_EBREAK = 548
OP_FABS = 549
OP_FADD = 550
OP_FCVT = 551
OP_FCVTZ = 552
OP_FDIV = 553
OP_FEQ = 554
OP_FGE = 555
OP_FLT = 556
OP_FMUL = 557
OP_FSUB = 558
OP_HL_SSRGET = 559
OP_HL_SSRSET = 560
OP_SSRGET = 561
OP_SSRSET = 562
OP_SSRSWAP = 563
OP_C_ADD = 564
OP_C_ADDI = 565
OP_C_AND = 566
OP_C_B_DIM = 567
OP_C_B_DIMI = 568
OP_C_EBREAK = 569
OP_C_LDI = 570
OP_C_LWI = 571
OP_C_MOVI = 572
OP_C_MOVR = 573
OP_C_OR = 574
OP_C_SDI = 575
OP_C_SEXT_B = 576
OP_C_SEXT_H = 577
OP_C_SEXT_W = 578
OP_C_SLLI = 579
OP_C_SRLI = 580
OP_C_SSRGET = 581
OP_C_SUB = 582
OP_C_SWI = 583
OP_C_ZEXT_B = 584
OP_C_ZEXT_H = 585
OP_C_ZEXT_W = 586
OP_ASSERT = 587
OP_BC_IALL = 588
OP_BC_IVA = 589
OP_BSE = 590
OP_BSTOP = 591
OP_BWE = 592
OP_BWI = 593
OP_BWT = 594
OP_C_BSTART_STD = 595
OP_C_SETRET = 596
OP_DC_CISW = 597
OP_DC_CIVA = 598
OP_DC_CSW = 599
OP_DC_CVA = 600
OP_DC_IALL = 601
OP_DC_ISW = 602
OP_DC_IVA = 603
OP_DC_ZVA = 604
OP_FCVTA = 605
OP_FCVTM = 606
OP_FCVTN = 607
OP_FCVTP = 608
OP_FENCE_D = 609
OP_FENCE_I = 610
OP_FEQS = 611
OP_FEXP = 612
OP_FGES = 613
OP_FLTS = 614
OP_FMADD = 615
OP_FMAX = 616
OP_FMIN = 617
OP_FMSUB = 618
OP_FNE = 619
OP_FNES = 620
OP_FNMADD = 621
OP_FNMSUB = 622
OP_FRECIP = 623
OP_FSQRT = 624
OP_IC_IALL = 625
OP_IC_IVA = 626
OP_J = 628
OP_JR = 629
OP_LR_B = 630
OP_LR_D = 631
OP_LR_H = 632
OP_LR_W = 633
OP_LSRGET = 634
OP_L_BSTART_FP = 635
OP_L_BSTART_STD = 636
OP_L_BSTART_SYS = 637
OP_MADD = 638
OP_MADDW = 639
OP_MAX = 640
OP_MAXU = 641
OP_MIN = 642
OP_MINU = 643
OP_PRF = 644
OP_PRFI_U = 645
OP_REV = 646
OP_SCVTF = 647
OP_SC_B = 648
OP_SC_D = 649
OP_SC_H = 650
OP_SC_W = 651
OP_START_CALL_32 = 652
OP_START_CALL_48 = 653
OP_TLB_IA = 654
OP_TLB_IALL = 655
OP_TLB_IAV = 656
OP_TLB_IV = 657
OP_UCVTF = 658

__all__ = [
    "OP_INVALID",
    "OP_BSTART_CUBE",
    "OP_BSTART_FALL",
    "OP_BSTART_FIXP",
    "OP_BSTART_FP_CALL",
    "OP_BSTART_FP_COND",
    "OP_BSTART_FP_DIRECT",
    "OP_BSTART_FP_FALL",
    "OP_BSTART_FP_ICALL",
    "OP_BSTART_FP_IND",
    "OP_BSTART_FP_RET",
    "OP_BSTART_ICALL",
    "OP_BSTART_IND",
    "OP_BSTART_MPAR",
    "OP_BSTART_MSEQ",
    "OP_BSTART_RET",
    "OP_BSTART_SPLIT_COND",
    "OP_BSTART_SPLIT_DIRECT",
    "OP_BSTART_STD_CALL",
    "OP_BSTART_STD_COND",
    "OP_BSTART_STD_DIRECT",
    "OP_BSTART_SYS",
    "OP_BSTART_TEPL",
    "OP_BSTART_TMA",
    "OP_BSTART_VPAR",
    "OP_BSTART_VSEQ",
    "OP_C_BSTART_COND",
    "OP_C_BSTART_DIRECT",
    "OP_C_BSTART_FP",
    "OP_C_BSTART_MPAR",
    "OP_C_BSTART_MSEQ",
    "OP_C_BSTART_STD_CALL",
    "OP_C_BSTART_STD_COND",
    "OP_C_BSTART_STD_DIRECT",
    "OP_C_BSTART_STD_FALL",
    "OP_C_BSTART_STD_ICALL",
    "OP_C_BSTART_STD_IND",
    "OP_C_BSTART_STD_RET",
    "OP_C_BSTART_SYS",
    "OP_C_BSTART_VPAR",
    "OP_C_BSTART_VSEQ",
    "OP_C_BSTOP",
    "OP_B_ARG",
    "OP_B_ARG_DN2NZ",
    "OP_B_ARG_DN2ZN",
    "OP_B_ARG_ND2ZN",
    "OP_B_ARG_NORM",
    "OP_B_ARG_NZ2DN",
    "OP_B_CATR",
    "OP_B_DATR",
    "OP_B_DIM_LB0",
    "OP_B_DIM_LB1",
    "OP_B_DIM_LB2",
    "OP_B_EQ",
    "OP_B_GE",
    "OP_B_GEU",
    "OP_B_HINT",
    "OP_B_HINT_TRACE",
    "OP_B_LT",
    "OP_B_LTU",
    "OP_B_NE",
    "OP_ADD",
    "OP_ADDI",
    "OP_ADDIW",
    "OP_ADDW",
    "OP_AND",
    "OP_ANDI",
    "OP_ANDIW",
    "OP_ANDW",
    "OP_BCNT",
    "OP_BIC",
    "OP_BIS",
    "OP_BSTART_STD_FALL",
    "OP_BXS",
    "OP_BXU",
    "OP_CASB",
    "OP_CASD",
    "OP_CASH",
    "OP_CASW",
    "OP_CLZ",
    "OP_CSEL",
    "OP_CTZ",
    "OP_DIV",
    "OP_DIVU",
    "OP_DIVUW",
    "OP_DIVW",
    "OP_DMA",
    "OP_HL_ADDI",
    "OP_HL_ADDIW",
    "OP_HL_ANDI",
    "OP_HL_ANDIW",
    "OP_HL_BFI",
    "OP_HL_BSTART_FP_CALL",
    "OP_HL_BSTART_FP_COND",
    "OP_HL_BSTART_FP_DIRECT",
    "OP_HL_BSTART_FP_FALL",
    "OP_HL_BSTART_SYS",
    "OP_HL_CASB",
    "OP_HL_CASD",
    "OP_HL_CASH",
    "OP_HL_CASW",
    "OP_HL_CCAT",
    "OP_HL_CCATW",
    "OP_HL_CMP_ANDI",
    "OP_HL_CMP_EQI",
    "OP_HL_CMP_GEI",
    "OP_HL_CMP_GEUI",
    "OP_HL_CMP_LTI",
    "OP_HL_CMP_LTUI",
    "OP_HL_CMP_NEI",
    "OP_HL_CMP_ORI",
    "OP_HL_DIV",
    "OP_HL_DIVU",
    "OP_HL_DIVUW",
    "OP_HL_DIVW",
    "OP_HL_LBI",
    "OP_HL_LBIP",
    "OP_HL_LBI_PO",
    "OP_HL_LBI_PR",
    "OP_HL_LBP",
    "OP_HL_LBUI",
    "OP_HL_LBUIP",
    "OP_HL_LBUI_PO",
    "OP_HL_LBUI_PR",
    "OP_HL_LBUP",
    "OP_HL_LBU_PO",
    "OP_HL_LBU_PR",
    "OP_HL_LB_PO",
    "OP_HL_LB_PR",
    "OP_HL_LDI",
    "OP_HL_LDIP",
    "OP_HL_LDIP_U",
    "OP_HL_LDI_PO",
    "OP_HL_LDI_PR",
    "OP_HL_LDI_U",
    "OP_HL_LDI_UPO",
    "OP_HL_LDI_UPR",
    "OP_HL_LDP",
    "OP_HL_LD_PO",
    "OP_HL_LD_PR",
    "OP_HL_LHI",
    "OP_HL_LHIP",
    "OP_HL_LHIP_U",
    "OP_HL_LHI_PO",
    "OP_HL_LHI_PR",
    "OP_HL_LHI_U",
    "OP_HL_LHI_UPO",
    "OP_HL_LHI_UPR",
    "OP_HL_LHP",
    "OP_HL_LHUI",
    "OP_HL_LHUIP",
    "OP_HL_LHUIP_U",
    "OP_HL_LHUI_PO",
    "OP_HL_LHUI_PR",
    "OP_HL_LHUI_U",
    "OP_HL_LHUI_UPO",
    "OP_HL_LHUI_UPR",
    "OP_HL_LHUP",
    "OP_HL_LHU_PO",
    "OP_HL_LHU_PR",
    "OP_HL_LH_PO",
    "OP_HL_LH_PR",
    "OP_HL_LIS",
    "OP_HL_LIU",
    "OP_HL_LUI",
    "OP_HL_LWI",
    "OP_HL_LWIP",
    "OP_HL_LWIP_U",
    "OP_HL_LWI_PO",
    "OP_HL_LWI_PR",
    "OP_HL_LWI_U",
    "OP_HL_LWI_UPO",
    "OP_HL_LWI_UPR",
    "OP_HL_LWP",
    "OP_HL_LWUI",
    "OP_HL_LWUIP",
    "OP_HL_LWUIP_U",
    "OP_HL_LWUI_PO",
    "OP_HL_LWUI_PR",
    "OP_HL_LWUI_U",
    "OP_HL_LWUI_UPO",
    "OP_HL_LWUI_UPR",
    "OP_HL_LWUP",
    "OP_HL_LWU_PO",
    "OP_HL_LWU_PR",
    "OP_HL_LW_PO",
    "OP_HL_LW_PR",
    "OP_HL_MADD",
    "OP_HL_MADDW",
    "OP_HL_MIADD",
    "OP_HL_MISUB",
    "OP_HL_MUL",
    "OP_HL_MULU",
    "OP_HL_ORI",
    "OP_HL_ORIW",
    "OP_HL_PRF",
    "OP_HL_PRFI_U",
    "OP_HL_PRFI_UA",
    "OP_HL_PRF_A",
    "OP_HL_QMT",
    "OP_HL_QPOP",
    "OP_HL_QPUSH",
    "OP_HL_REM",
    "OP_HL_REMU",
    "OP_HL_REMUW",
    "OP_HL_REMW",
    "OP_HL_SBI",
    "OP_HL_SBIP",
    "OP_HL_SBI_PO",
    "OP_HL_SBI_PR",
    "OP_HL_SBP",
    "OP_HL_SB_PO",
    "OP_HL_SB_PR",
    "OP_HL_SDI",
    "OP_HL_SDIP",
    "OP_HL_SDIP_U",
    "OP_HL_SDI_PO",
    "OP_HL_SDI_PR",
    "OP_HL_SDI_U",
    "OP_HL_SDI_UPO",
    "OP_HL_SDI_UPR",
    "OP_HL_SDP",
    "OP_HL_SDP_U",
    "OP_HL_SD_PO",
    "OP_HL_SD_PR",
    "OP_HL_SD_UPO",
    "OP_HL_SD_UPR",
    "OP_HL_SETC_ANDI",
    "OP_HL_SETC_EQI",
    "OP_HL_SETC_GEI",
    "OP_HL_SETC_GEUI",
    "OP_HL_SETC_LTI",
    "OP_HL_SETC_LTUI",
    "OP_HL_SETC_NEI",
    "OP_HL_SETC_ORI",
    "OP_HL_SETRET",
    "OP_HL_SHI",
    "OP_HL_SHIP",
    "OP_HL_SHIP_U",
    "OP_HL_SHI_PO",
    "OP_HL_SHI_PR",
    "OP_HL_SHI_U",
    "OP_HL_SHI_UPO",
    "OP_HL_SHI_UPR",
    "OP_HL_SHP",
    "OP_HL_SHP_U",
    "OP_HL_SH_PO",
    "OP_HL_SH_PR",
    "OP_HL_SH_UPO",
    "OP_HL_SH_UPR",
    "OP_HL_SUBI",
    "OP_HL_SUBIW",
    "OP_HL_SWI",
    "OP_HL_SWIP",
    "OP_HL_SWIP_U",
    "OP_HL_SWI_PO",
    "OP_HL_SWI_PR",
    "OP_HL_SWI_U",
    "OP_HL_SWI_UPO",
    "OP_HL_SWI_UPR",
    "OP_HL_SWP",
    "OP_HL_SWP_U",
    "OP_HL_SW_PO",
    "OP_HL_SW_PR",
    "OP_HL_SW_UPO",
    "OP_HL_SW_UPR",
    "OP_HL_XORI",
    "OP_HL_XORIW",
    "OP_LUI",
    "OP_MUL",
    "OP_MULU",
    "OP_MULUW",
    "OP_MULW",
    "OP_OR",
    "OP_ORI",
    "OP_ORIW",
    "OP_ORW",
    "OP_REM",
    "OP_REMU",
    "OP_REMUW",
    "OP_REMW",
    "OP_SLL",
    "OP_SLLI",
    "OP_SLLIW",
    "OP_SLLW",
    "OP_SRA",
    "OP_SRAI",
    "OP_SRAIW",
    "OP_SRAW",
    "OP_SRL",
    "OP_SRLI",
    "OP_SRLIW",
    "OP_SRLW",
    "OP_SUB",
    "OP_SUBI",
    "OP_SUBIW",
    "OP_SUBW",
    "OP_XOR",
    "OP_XORI",
    "OP_XORIW",
    "OP_XORW",
    "OP_ADDTPC",
    "OP_B_NZ",
    "OP_B_Z",
    "OP_CMP_AND",
    "OP_CMP_ANDI",
    "OP_CMP_EQ",
    "OP_CMP_EQI",
    "OP_CMP_GE",
    "OP_CMP_GEI",
    "OP_CMP_GEU",
    "OP_CMP_GEUI",
    "OP_CMP_LT",
    "OP_CMP_LTI",
    "OP_CMP_LTU",
    "OP_CMP_LTUI",
    "OP_CMP_NE",
    "OP_CMP_NEI",
    "OP_CMP_OR",
    "OP_CMP_ORI",
    "OP_C_CMP_EQI",
    "OP_C_CMP_NEI",
    "OP_C_SETC_EQ",
    "OP_C_SETC_NE",
    "OP_C_SETC_TGT",
    "OP_HL_ADDTPC",
    "OP_SETC_AND",
    "OP_SETC_ANDI",
    "OP_SETC_EQ",
    "OP_SETC_EQI",
    "OP_SETC_GE",
    "OP_SETC_GEI",
    "OP_SETC_GEU",
    "OP_SETC_GEUI",
    "OP_SETC_LT",
    "OP_SETC_LTI",
    "OP_SETC_LTU",
    "OP_SETC_LTUI",
    "OP_SETC_NE",
    "OP_SETC_NEI",
    "OP_SETC_OR",
    "OP_SETC_ORI",
    "OP_SETC_TGT",
    "OP_SETRET",
    "OP_LB",
    "OP_LBI",
    "OP_LBU",
    "OP_LBUI",
    "OP_LBU_PCR",
    "OP_LB_PCR",
    "OP_LD",
    "OP_LDI",
    "OP_LDI_U",
    "OP_LD_ADD",
    "OP_LD_AND",
    "OP_LD_OR",
    "OP_LD_PCR",
    "OP_LD_SMAX",
    "OP_LD_SMIN",
    "OP_LD_UMAX",
    "OP_LD_UMIN",
    "OP_LD_XOR",
    "OP_LH",
    "OP_LHI",
    "OP_LHI_U",
    "OP_LHU",
    "OP_LHUI",
    "OP_LHUI_U",
    "OP_LHU_PCR",
    "OP_LH_PCR",
    "OP_LW",
    "OP_LWI",
    "OP_LWI_U",
    "OP_LWU",
    "OP_LWUI",
    "OP_LWUI_U",
    "OP_LWU_PCR",
    "OP_LW_ADD",
    "OP_LW_AND",
    "OP_LW_OR",
    "OP_LW_PCR",
    "OP_LW_SMAX",
    "OP_LW_SMIN",
    "OP_LW_UMAX",
    "OP_LW_UMIN",
    "OP_LW_XOR",
    "OP_SB",
    "OP_SBI",
    "OP_SB_PCR",
    "OP_SD",
    "OP_SDI",
    "OP_SDI_U",
    "OP_SD_ADD",
    "OP_SD_AND",
    "OP_SD_OR",
    "OP_SD_PCR",
    "OP_SD_SMAX",
    "OP_SD_SMIN",
    "OP_SD_U",
    "OP_SD_UMAX",
    "OP_SD_UMIN",
    "OP_SD_XOR",
    "OP_SH",
    "OP_SHI",
    "OP_SHI_U",
    "OP_SH_PCR",
    "OP_SH_U",
    "OP_SW",
    "OP_SWAPB",
    "OP_SWAPD",
    "OP_SWAPH",
    "OP_SWAPW",
    "OP_SWI",
    "OP_SWI_U",
    "OP_SW_ADD",
    "OP_SW_AND",
    "OP_SW_OR",
    "OP_SW_PCR",
    "OP_SW_SMAX",
    "OP_SW_SMIN",
    "OP_SW_U",
    "OP_SW_UMAX",
    "OP_SW_UMIN",
    "OP_SW_XOR",
    "OP_BIOR",
    "OP_BTEXT",
    "OP_B_IOT",
    "OP_ERCOV",
    "OP_ESAVE",
    "OP_FENTRY",
    "OP_FEXIT",
    "OP_FRET_RA",
    "OP_FRET_STK",
    "OP_MCOPY",
    "OP_MSET",
    "OP_HL_LBU_PCR",
    "OP_HL_LB_PCR",
    "OP_HL_LD_PCR",
    "OP_HL_LHU_PCR",
    "OP_HL_LH_PCR",
    "OP_HL_LWU_PCR",
    "OP_HL_LW_PCR",
    "OP_HL_SB_PCR",
    "OP_HL_SD_PCR",
    "OP_HL_SH_PCR",
    "OP_HL_SW_PCR",
    "OP_V_ADD",
    "OP_V_ADDI",
    "OP_V_AND",
    "OP_V_ANDI",
    "OP_V_BCNT",
    "OP_V_BIC",
    "OP_V_BIS",
    "OP_V_BXS",
    "OP_V_BXU",
    "OP_V_CLZ",
    "OP_V_CMP_AND",
    "OP_V_CMP_ANDI",
    "OP_V_CMP_EQ",
    "OP_V_CMP_EQI",
    "OP_V_CMP_GE",
    "OP_V_CMP_GEI",
    "OP_V_CMP_GEU",
    "OP_V_CMP_GEUI",
    "OP_V_CMP_LT",
    "OP_V_CMP_LTI",
    "OP_V_CMP_LTU",
    "OP_V_CMP_LTUI",
    "OP_V_CMP_NE",
    "OP_V_CMP_NEI",
    "OP_V_CMP_OR",
    "OP_V_CMP_ORI",
    "OP_V_CSEL",
    "OP_V_CTZ",
    "OP_V_DIV",
    "OP_V_FABS",
    "OP_V_FADD",
    "OP_V_FCLASS",
    "OP_V_FCVT",
    "OP_V_FCVTI",
    "OP_V_FDIV",
    "OP_V_FEQ",
    "OP_V_FEQS",
    "OP_V_FEXP",
    "OP_V_FGE",
    "OP_V_FGES",
    "OP_V_FLT",
    "OP_V_FLTS",
    "OP_V_FMADD",
    "OP_V_FMAX",
    "OP_V_FMIN",
    "OP_V_FMSUB",
    "OP_V_FMUL",
    "OP_V_FNE",
    "OP_V_FNES",
    "OP_V_FNMADD",
    "OP_V_FNMSUB",
    "OP_V_FRECIP",
    "OP_V_FSQRT",
    "OP_V_FSUB",
    "OP_V_ICVT",
    "OP_V_ICVTF",
    "OP_V_LB",
    "OP_V_LBU",
    "OP_V_LBU_BRG",
    "OP_V_LB_BRG",
    "OP_V_LH",
    "OP_V_LHU",
    "OP_V_LHU_BRG",
    "OP_V_LH_BRG",
    "OP_V_LW",
    "OP_V_LW_BRG",
    "OP_V_MADD",
    "OP_V_MAX",
    "OP_V_MIN",
    "OP_V_MUL",
    "OP_V_OR",
    "OP_V_ORI",
    "OP_V_PSEL",
    "OP_V_RDADD",
    "OP_V_RDAND",
    "OP_V_RDFADD",
    "OP_V_RDFMAX",
    "OP_V_RDFMIN",
    "OP_V_RDMAX",
    "OP_V_RDMIN",
    "OP_V_RDOR",
    "OP_V_RDXOR",
    "OP_V_REM",
    "OP_V_REV",
    "OP_V_SB",
    "OP_V_SB_BRG",
    "OP_V_SH",
    "OP_V_SH_BRG",
    "OP_V_SLL",
    "OP_V_SLLI",
    "OP_V_SRA",
    "OP_V_SRAI",
    "OP_V_SRL",
    "OP_V_SRLI",
    "OP_V_SUB",
    "OP_V_SUBI",
    "OP_V_SW",
    "OP_V_SW_BRG",
    "OP_V_XOR",
    "OP_V_XORI",
    "OP_ACRC",
    "OP_ACRE",
    "OP_EBREAK",
    "OP_FABS",
    "OP_FADD",
    "OP_FCVT",
    "OP_FCVTZ",
    "OP_FDIV",
    "OP_FEQ",
    "OP_FGE",
    "OP_FLT",
    "OP_FMUL",
    "OP_FSUB",
    "OP_HL_SSRGET",
    "OP_HL_SSRSET",
    "OP_SSRGET",
    "OP_SSRSET",
    "OP_SSRSWAP",
    "OP_C_ADD",
    "OP_C_ADDI",
    "OP_C_AND",
    "OP_C_B_DIM",
    "OP_C_B_DIMI",
    "OP_C_EBREAK",
    "OP_C_LDI",
    "OP_C_LWI",
    "OP_C_MOVI",
    "OP_C_MOVR",
    "OP_C_OR",
    "OP_C_SDI",
    "OP_C_SEXT_B",
    "OP_C_SEXT_H",
    "OP_C_SEXT_W",
    "OP_C_SLLI",
    "OP_C_SRLI",
    "OP_C_SSRGET",
    "OP_C_SUB",
    "OP_C_SWI",
    "OP_C_ZEXT_B",
    "OP_C_ZEXT_H",
    "OP_C_ZEXT_W",
    "OP_ASSERT",
    "OP_BC_IALL",
    "OP_BC_IVA",
    "OP_BSE",
    "OP_BSTOP",
    "OP_BWE",
    "OP_BWI",
    "OP_BWT",
    "OP_C_BSTART_STD",
    "OP_C_SETRET",
    "OP_DC_CISW",
    "OP_DC_CIVA",
    "OP_DC_CSW",
    "OP_DC_CVA",
    "OP_DC_IALL",
    "OP_DC_ISW",
    "OP_DC_IVA",
    "OP_DC_ZVA",
    "OP_FCVTA",
    "OP_FCVTM",
    "OP_FCVTN",
    "OP_FCVTP",
    "OP_FENCE_D",
    "OP_FENCE_I",
    "OP_FEQS",
    "OP_FEXP",
    "OP_FGES",
    "OP_FLTS",
    "OP_FMADD",
    "OP_FMAX",
    "OP_FMIN",
    "OP_FMSUB",
    "OP_FNE",
    "OP_FNES",
    "OP_FNMADD",
    "OP_FNMSUB",
    "OP_FRECIP",
    "OP_FSQRT",
    "OP_IC_IALL",
    "OP_IC_IVA",
    "OP_J",
    "OP_JR",
    "OP_LR_B",
    "OP_LR_D",
    "OP_LR_H",
    "OP_LR_W",
    "OP_LSRGET",
    "OP_L_BSTART_FP",
    "OP_L_BSTART_STD",
    "OP_L_BSTART_SYS",
    "OP_MADD",
    "OP_MADDW",
    "OP_MAX",
    "OP_MAXU",
    "OP_MIN",
    "OP_MINU",
    "OP_PRF",
    "OP_PRFI_U",
    "OP_REV",
    "OP_SCVTF",
    "OP_SC_B",
    "OP_SC_D",
    "OP_SC_H",
    "OP_SC_W",
    "OP_START_CALL_32",
    "OP_START_CALL_48",
    "OP_TLB_IA",
    "OP_TLB_IALL",
    "OP_TLB_IAV",
    "OP_TLB_IV",
    "OP_UCVTF",
]
