from __future__ import annotations

# AUTO-GENERATED FILE. DO NOT EDIT.

OP_INVALID = 0
OP_BSTART_CUBE = 1
OP_BSTART_FIXP = 2
OP_BSTART_FP_CALL = 3
OP_BSTART_FP_COND = 4
OP_BSTART_FP_DIRECT = 5
OP_BSTART_FP_FALL = 6
OP_BSTART_FP_ICALL = 7
OP_BSTART_FP_IND = 8
OP_BSTART_FP_RET = 9
OP_BSTART_ICALL = 10
OP_BSTART_IND = 11
OP_BSTART_MPAR = 12
OP_BSTART_MSEQ = 13
OP_BSTART_RET = 14
OP_BSTART_STD_CALL = 15
OP_BSTART_STD_COND = 16
OP_BSTART_STD_DIRECT = 17
OP_BSTART_SYS = 18
OP_BSTART_TEPL = 19
OP_BSTART_TMA = 20
OP_BSTART_VPAR = 21
OP_BSTART_VSEQ = 22
OP_C_BSTART_COND = 23
OP_C_BSTART_DIRECT = 24
OP_C_BSTART_FP = 25
OP_C_BSTART_MPAR = 26
OP_C_BSTART_MSEQ = 27
OP_C_BSTART_STD_CALL = 28
OP_C_BSTART_STD_COND = 29
OP_C_BSTART_STD_DIRECT = 30
OP_C_BSTART_STD_FALL = 31
OP_C_BSTART_STD_ICALL = 32
OP_C_BSTART_STD_IND = 33
OP_C_BSTART_STD_RET = 34
OP_C_BSTART_SYS = 35
OP_C_BSTART_VPAR = 36
OP_C_BSTART_VSEQ = 37
OP_C_BSTOP = 38
OP_B_ARG = 39
OP_B_ATTR = 40
OP_B_DIM_LB0 = 41
OP_B_DIM_LB1 = 42
OP_B_DIM_LB2 = 43
OP_B_EQ = 44
OP_B_GE = 45
OP_B_GEU = 46
OP_B_HINT = 47
OP_B_HINT_TRACE = 48
OP_B_IOD = 49
OP_B_LT = 50
OP_B_LTU = 51
OP_B_NE = 52
OP_ADD = 53
OP_ADDI = 54
OP_ADDIW = 55
OP_ADDW = 56
OP_AND = 57
OP_ANDI = 58
OP_ANDIW = 59
OP_ANDW = 60
OP_BCNT = 61
OP_BIC = 62
OP_BIS = 63
OP_BSTART_STD_FALL = 64
OP_BXS = 65
OP_BXU = 66
OP_CLZ = 67
OP_CSEL = 68
OP_CTZ = 69
OP_DIV = 70
OP_DIVU = 71
OP_DIVUW = 72
OP_DIVW = 73
OP_HL_ADDI = 74
OP_HL_ADDIW = 75
OP_HL_ANDI = 76
OP_HL_ANDIW = 77
OP_HL_BFI = 78
OP_HL_BSTART_FP_CALL = 79
OP_HL_BSTART_FP_COND = 80
OP_HL_BSTART_FP_DIRECT = 81
OP_HL_BSTART_FP_FALL = 82
OP_HL_BSTART_SYS = 83
OP_HL_CASB = 84
OP_HL_CASD = 85
OP_HL_CASH = 86
OP_HL_CASW = 87
OP_HL_CCAT = 88
OP_HL_CCATW = 89
OP_HL_CMP_ANDI = 90
OP_HL_CMP_EQI = 91
OP_HL_CMP_GEI = 92
OP_HL_CMP_GEUI = 93
OP_HL_CMP_LTI = 94
OP_HL_CMP_LTUI = 95
OP_HL_CMP_NEI = 96
OP_HL_CMP_ORI = 97
OP_HL_LBI = 98
OP_HL_LBIP = 99
OP_HL_LBI_PO = 100
OP_HL_LBI_PR = 101
OP_HL_LBP = 102
OP_HL_LBUI = 103
OP_HL_LBUIP = 104
OP_HL_LBUI_PO = 105
OP_HL_LBUI_PR = 106
OP_HL_LBUP = 107
OP_HL_LBU_PO = 108
OP_HL_LBU_PR = 109
OP_HL_LB_PO = 110
OP_HL_LB_PR = 111
OP_HL_LDI = 112
OP_HL_LDIP = 113
OP_HL_LDIP_U = 114
OP_HL_LDI_PO = 115
OP_HL_LDI_PR = 116
OP_HL_LDI_U = 117
OP_HL_LDI_UPO = 118
OP_HL_LDI_UPR = 119
OP_HL_LDP = 120
OP_HL_LD_PO = 121
OP_HL_LD_PR = 122
OP_HL_LHI = 123
OP_HL_LHIP = 124
OP_HL_LHIP_U = 125
OP_HL_LHI_PO = 126
OP_HL_LHI_PR = 127
OP_HL_LHI_U = 128
OP_HL_LHI_UPO = 129
OP_HL_LHI_UPR = 130
OP_HL_LHP = 131
OP_HL_LHUI = 132
OP_HL_LHUIP = 133
OP_HL_LHUIP_U = 134
OP_HL_LHUI_PO = 135
OP_HL_LHUI_PR = 136
OP_HL_LHUI_U = 137
OP_HL_LHUI_UPO = 138
OP_HL_LHUI_UPR = 139
OP_HL_LHUP = 140
OP_HL_LHU_PO = 141
OP_HL_LHU_PR = 142
OP_HL_LH_PO = 143
OP_HL_LH_PR = 144
OP_HL_LIS = 145
OP_HL_LIU = 146
OP_HL_LUI = 147
OP_HL_LWI = 148
OP_HL_LWIP = 149
OP_HL_LWIP_U = 150
OP_HL_LWI_PO = 151
OP_HL_LWI_PR = 152
OP_HL_LWI_U = 153
OP_HL_LWI_UPO = 154
OP_HL_LWI_UPR = 155
OP_HL_LWP = 156
OP_HL_LWUI = 157
OP_HL_LWUIP = 158
OP_HL_LWUIP_U = 159
OP_HL_LWUI_PO = 160
OP_HL_LWUI_PR = 161
OP_HL_LWUI_U = 162
OP_HL_LWUI_UPO = 163
OP_HL_LWUI_UPR = 164
OP_HL_LWUP = 165
OP_HL_LWU_PO = 166
OP_HL_LWU_PR = 167
OP_HL_LW_PO = 168
OP_HL_LW_PR = 169
OP_HL_MIADD = 170
OP_HL_MISUB = 171
OP_HL_ORI = 172
OP_HL_ORIW = 173
OP_HL_PRF = 174
OP_HL_PRFI_U = 175
OP_HL_PRFI_UA = 176
OP_HL_PRF_A = 177
OP_HL_QMT = 178
OP_HL_QPOP = 179
OP_HL_QPUSH = 180
OP_HL_SBI = 181
OP_HL_SBIP = 182
OP_HL_SBI_PO = 183
OP_HL_SBI_PR = 184
OP_HL_SBP = 185
OP_HL_SB_PO = 186
OP_HL_SB_PR = 187
OP_HL_SDI = 188
OP_HL_SDIP = 189
OP_HL_SDIP_U = 190
OP_HL_SDI_PO = 191
OP_HL_SDI_PR = 192
OP_HL_SDI_U = 193
OP_HL_SDI_UPO = 194
OP_HL_SDI_UPR = 195
OP_HL_SDP = 196
OP_HL_SDP_U = 197
OP_HL_SD_PO = 198
OP_HL_SD_PR = 199
OP_HL_SD_UPO = 200
OP_HL_SD_UPR = 201
OP_HL_SETC_EQI = 202
OP_HL_SETC_GEI = 203
OP_HL_SETC_GEUI = 204
OP_HL_SETC_LTI = 205
OP_HL_SETC_LTUI = 206
OP_HL_SETC_NEI = 207
OP_HL_SETRET = 208
OP_HL_SHI = 209
OP_HL_SHIP = 210
OP_HL_SHIP_U = 211
OP_HL_SHI_PO = 212
OP_HL_SHI_PR = 213
OP_HL_SHI_U = 214
OP_HL_SHI_UPO = 215
OP_HL_SHI_UPR = 216
OP_HL_SHP = 217
OP_HL_SHP_U = 218
OP_HL_SH_PO = 219
OP_HL_SH_PR = 220
OP_HL_SH_UPO = 221
OP_HL_SH_UPR = 222
OP_HL_SUBI = 223
OP_HL_SUBIW = 224
OP_HL_SWI = 225
OP_HL_SWIP = 226
OP_HL_SWIP_U = 227
OP_HL_SWI_PO = 228
OP_HL_SWI_PR = 229
OP_HL_SWI_U = 230
OP_HL_SWI_UPO = 231
OP_HL_SWI_UPR = 232
OP_HL_SWP = 233
OP_HL_SWP_U = 234
OP_HL_SW_PO = 235
OP_HL_SW_PR = 236
OP_HL_SW_UPO = 237
OP_HL_SW_UPR = 238
OP_HL_XORI = 239
OP_HL_XORIW = 240
OP_LUI = 241
OP_MUL = 242
OP_MULU = 243
OP_MULUW = 244
OP_MULW = 245
OP_OR = 246
OP_ORI = 247
OP_ORIW = 248
OP_ORW = 249
OP_REM = 250
OP_REMU = 251
OP_REMUW = 252
OP_REMW = 253
OP_SLL = 254
OP_SLLI = 255
OP_SLLIW = 256
OP_SLLW = 257
OP_SRA = 258
OP_SRAI = 259
OP_SRAIW = 260
OP_SRAW = 261
OP_SRL = 262
OP_SRLI = 263
OP_SRLIW = 264
OP_SRLW = 265
OP_SUB = 266
OP_SUBI = 267
OP_SUBIW = 268
OP_SUBW = 269
OP_XOR = 270
OP_XORI = 271
OP_XORIW = 272
OP_XORW = 273
OP_ADDTPC = 274
OP_B_NZ = 275
OP_B_Z = 276
OP_CMP_AND = 277
OP_CMP_ANDI = 278
OP_CMP_EQ = 279
OP_CMP_EQI = 280
OP_CMP_GE = 281
OP_CMP_GEI = 282
OP_CMP_GEU = 283
OP_CMP_GEUI = 284
OP_CMP_LT = 285
OP_CMP_LTI = 286
OP_CMP_LTU = 287
OP_CMP_LTUI = 288
OP_CMP_NE = 289
OP_CMP_NEI = 290
OP_CMP_OR = 291
OP_CMP_ORI = 292
OP_C_CMP_EQI = 293
OP_C_CMP_NEI = 294
OP_C_SETC_EQ = 295
OP_C_SETC_NE = 296
OP_C_SETC_TGT = 297
OP_HL_ADDTPC = 298
OP_SETC_AND = 299
OP_SETC_ANDI = 300
OP_SETC_EQ = 301
OP_SETC_EQI = 302
OP_SETC_GE = 303
OP_SETC_GEI = 304
OP_SETC_GEU = 305
OP_SETC_GEUI = 306
OP_SETC_LT = 307
OP_SETC_LTI = 308
OP_SETC_LTU = 309
OP_SETC_LTUI = 310
OP_SETC_NE = 311
OP_SETC_NEI = 312
OP_SETC_OR = 313
OP_SETC_ORI = 314
OP_SETC_TGT = 315
OP_SETRET = 316
OP_LB = 317
OP_LBI = 318
OP_LBU = 319
OP_LBUI = 320
OP_LBU_PCR = 321
OP_LB_PCR = 322
OP_LD = 323
OP_LDI = 324
OP_LDI_U = 325
OP_LD_ADD = 326
OP_LD_AND = 327
OP_LD_OR = 328
OP_LD_PCR = 329
OP_LD_SMAX = 330
OP_LD_SMIN = 331
OP_LD_UMAX = 332
OP_LD_UMIN = 333
OP_LD_XOR = 334
OP_LH = 335
OP_LHI = 336
OP_LHI_U = 337
OP_LHU = 338
OP_LHUI = 339
OP_LHUI_U = 340
OP_LHU_PCR = 341
OP_LH_PCR = 342
OP_LW = 343
OP_LWI = 344
OP_LWI_U = 345
OP_LWU = 346
OP_LWUI = 347
OP_LWUI_U = 348
OP_LWU_PCR = 349
OP_LW_ADD = 350
OP_LW_AND = 351
OP_LW_OR = 352
OP_LW_PCR = 353
OP_LW_SMAX = 354
OP_LW_SMIN = 355
OP_LW_UMAX = 356
OP_LW_UMIN = 357
OP_LW_XOR = 358
OP_SB = 359
OP_SBI = 360
OP_SB_PCR = 361
OP_SD = 362
OP_SDI = 363
OP_SDI_U = 364
OP_SD_ADD = 365
OP_SD_AND = 366
OP_SD_OR = 367
OP_SD_PCR = 368
OP_SD_SMAX = 369
OP_SD_SMIN = 370
OP_SD_U = 371
OP_SD_UMAX = 372
OP_SD_UMIN = 373
OP_SD_XOR = 374
OP_SH = 375
OP_SHI = 376
OP_SHI_U = 377
OP_SH_PCR = 378
OP_SH_U = 379
OP_SW = 380
OP_SWAPB = 381
OP_SWAPD = 382
OP_SWAPH = 383
OP_SWAPW = 384
OP_SWI = 385
OP_SWI_U = 386
OP_SW_ADD = 387
OP_SW_AND = 388
OP_SW_OR = 389
OP_SW_PCR = 390
OP_SW_SMAX = 391
OP_SW_SMIN = 392
OP_SW_U = 393
OP_SW_UMAX = 394
OP_SW_UMIN = 395
OP_SW_XOR = 396
OP_BIOR = 397
OP_BLOAD = 398
OP_BSTORE = 399
OP_BTEXT = 400
OP_ERCOV = 401
OP_ESAVE = 402
OP_FENTRY = 403
OP_FEXIT = 404
OP_FRET_RA = 405
OP_FRET_STK = 406
OP_MCOPY = 407
OP_MSET = 408
OP_HL_LBU_PCR = 409
OP_HL_LB_PCR = 410
OP_HL_LD_PCR = 411
OP_HL_LHU_PCR = 412
OP_HL_LH_PCR = 413
OP_HL_LWU_PCR = 414
OP_HL_LW_PCR = 415
OP_HL_SB_PCR = 416
OP_HL_SD_PCR = 417
OP_HL_SH_PCR = 418
OP_HL_SW_PCR = 419
OP_V_ADD = 420
OP_V_CMP_EQ = 421
OP_V_CMP_GE = 422
OP_V_CMP_GEU = 423
OP_V_CMP_LT = 424
OP_V_CMP_LTU = 425
OP_V_CMP_NE = 426
OP_V_CSEL = 427
OP_V_FABS = 428
OP_V_FADD = 429
OP_V_FDIV = 430
OP_V_FEQ = 431
OP_V_FGE = 432
OP_V_FLT = 433
OP_V_FMUL = 434
OP_V_FNE = 435
OP_V_FSUB = 436
OP_V_LW = 437
OP_V_LW_BRG = 438
OP_V_MUL = 439
OP_V_RDADD = 440
OP_V_RDAND = 441
OP_V_RDFADD = 442
OP_V_RDFMAX = 443
OP_V_RDFMIN = 444
OP_V_RDMAX = 445
OP_V_RDMIN = 446
OP_V_RDOR = 447
OP_V_RDXOR = 448
OP_V_SUB = 449
OP_V_SW = 450
OP_V_SW_BRG = 451
OP_ACRC = 452
OP_ACRE = 453
OP_EBREAK = 454
OP_FABS = 455
OP_FADD = 456
OP_FCVT = 457
OP_FCVTZ = 458
OP_FDIV = 459
OP_FEQ = 460
OP_FGE = 461
OP_FLT = 462
OP_FMUL = 463
OP_FSUB = 464
OP_HL_SSRGET = 465
OP_HL_SSRSET = 466
OP_SSRGET = 467
OP_SSRSET = 468
OP_SSRSWAP = 469
OP_C_ADD = 470
OP_C_ADDI = 471
OP_C_AND = 472
OP_C_B_DIM = 473
OP_C_B_DIMI = 474
OP_C_EBREAK = 475
OP_C_LDI = 476
OP_C_LWI = 477
OP_C_MOVI = 478
OP_C_MOVR = 479
OP_C_OR = 480
OP_C_SDI = 481
OP_C_SEXT_B = 482
OP_C_SEXT_H = 483
OP_C_SEXT_W = 484
OP_C_SLLI = 485
OP_C_SRLI = 486
OP_C_SSRGET = 487
OP_C_SUB = 488
OP_C_SWI = 489
OP_C_ZEXT_B = 490
OP_C_ZEXT_H = 491
OP_C_ZEXT_W = 492
OP_ASSERT = 493
OP_BC_IALL = 494
OP_BC_IVA = 495
OP_BSE = 496
OP_BSTOP = 497
OP_BWE = 498
OP_BWI = 499
OP_BWT = 500
OP_C_BSTART_STD = 501
OP_C_SETRET = 502
OP_DC_CISW = 503
OP_DC_CIVA = 504
OP_DC_CSW = 505
OP_DC_CVA = 506
OP_DC_IALL = 507
OP_DC_ISW = 508
OP_DC_IVA = 509
OP_DC_ZVA = 510
OP_FENCE_D = 511
OP_FENCE_I = 512
OP_IC_IALL = 513
OP_IC_IVA = 514
OP_J = 516
OP_JR = 517
OP_LR_B = 518
OP_LR_D = 519
OP_LR_H = 520
OP_LR_W = 521
OP_LSRGET = 522
OP_MADD = 523
OP_MADDW = 524
OP_MAX = 525
OP_MAXU = 526
OP_MIN = 527
OP_MINU = 528
OP_PRF = 529
OP_PRFI_U = 530
OP_REV = 531
OP_SCVTF = 532
OP_SC_B = 533
OP_SC_D = 534
OP_SC_H = 535
OP_SC_W = 536
OP_TLB_IA = 537
OP_TLB_IALL = 538
OP_TLB_IAV = 539
OP_TLB_IV = 540
OP_UCVTF = 541

__all__ = [
    "OP_INVALID",
    "OP_BSTART_CUBE",
    "OP_BSTART_FIXP",
    "OP_BSTART_FP_CALL",
    "OP_BSTART_FP_COND",
    "OP_BSTART_FP_DIRECT",
    "OP_BSTART_FP_FALL",
    "OP_BSTART_FP_ICALL",
    "OP_BSTART_FP_IND",
    "OP_BSTART_FP_RET",
    "OP_BSTART_ICALL",
    "OP_BSTART_IND",
    "OP_BSTART_MPAR",
    "OP_BSTART_MSEQ",
    "OP_BSTART_RET",
    "OP_BSTART_STD_CALL",
    "OP_BSTART_STD_COND",
    "OP_BSTART_STD_DIRECT",
    "OP_BSTART_SYS",
    "OP_BSTART_TEPL",
    "OP_BSTART_TMA",
    "OP_BSTART_VPAR",
    "OP_BSTART_VSEQ",
    "OP_C_BSTART_COND",
    "OP_C_BSTART_DIRECT",
    "OP_C_BSTART_FP",
    "OP_C_BSTART_MPAR",
    "OP_C_BSTART_MSEQ",
    "OP_C_BSTART_STD_CALL",
    "OP_C_BSTART_STD_COND",
    "OP_C_BSTART_STD_DIRECT",
    "OP_C_BSTART_STD_FALL",
    "OP_C_BSTART_STD_ICALL",
    "OP_C_BSTART_STD_IND",
    "OP_C_BSTART_STD_RET",
    "OP_C_BSTART_SYS",
    "OP_C_BSTART_VPAR",
    "OP_C_BSTART_VSEQ",
    "OP_C_BSTOP",
    "OP_B_ARG",
    "OP_B_ATTR",
    "OP_B_DIM_LB0",
    "OP_B_DIM_LB1",
    "OP_B_DIM_LB2",
    "OP_B_EQ",
    "OP_B_GE",
    "OP_B_GEU",
    "OP_B_HINT",
    "OP_B_HINT_TRACE",
    "OP_B_IOD",
    "OP_B_LT",
    "OP_B_LTU",
    "OP_B_NE",
    "OP_ADD",
    "OP_ADDI",
    "OP_ADDIW",
    "OP_ADDW",
    "OP_AND",
    "OP_ANDI",
    "OP_ANDIW",
    "OP_ANDW",
    "OP_BCNT",
    "OP_BIC",
    "OP_BIS",
    "OP_BSTART_STD_FALL",
    "OP_BXS",
    "OP_BXU",
    "OP_CLZ",
    "OP_CSEL",
    "OP_CTZ",
    "OP_DIV",
    "OP_DIVU",
    "OP_DIVUW",
    "OP_DIVW",
    "OP_HL_ADDI",
    "OP_HL_ADDIW",
    "OP_HL_ANDI",
    "OP_HL_ANDIW",
    "OP_HL_BFI",
    "OP_HL_BSTART_FP_CALL",
    "OP_HL_BSTART_FP_COND",
    "OP_HL_BSTART_FP_DIRECT",
    "OP_HL_BSTART_FP_FALL",
    "OP_HL_BSTART_SYS",
    "OP_HL_CASB",
    "OP_HL_CASD",
    "OP_HL_CASH",
    "OP_HL_CASW",
    "OP_HL_CCAT",
    "OP_HL_CCATW",
    "OP_HL_CMP_ANDI",
    "OP_HL_CMP_EQI",
    "OP_HL_CMP_GEI",
    "OP_HL_CMP_GEUI",
    "OP_HL_CMP_LTI",
    "OP_HL_CMP_LTUI",
    "OP_HL_CMP_NEI",
    "OP_HL_CMP_ORI",
    "OP_HL_LBI",
    "OP_HL_LBIP",
    "OP_HL_LBI_PO",
    "OP_HL_LBI_PR",
    "OP_HL_LBP",
    "OP_HL_LBUI",
    "OP_HL_LBUIP",
    "OP_HL_LBUI_PO",
    "OP_HL_LBUI_PR",
    "OP_HL_LBUP",
    "OP_HL_LBU_PO",
    "OP_HL_LBU_PR",
    "OP_HL_LB_PO",
    "OP_HL_LB_PR",
    "OP_HL_LDI",
    "OP_HL_LDIP",
    "OP_HL_LDIP_U",
    "OP_HL_LDI_PO",
    "OP_HL_LDI_PR",
    "OP_HL_LDI_U",
    "OP_HL_LDI_UPO",
    "OP_HL_LDI_UPR",
    "OP_HL_LDP",
    "OP_HL_LD_PO",
    "OP_HL_LD_PR",
    "OP_HL_LHI",
    "OP_HL_LHIP",
    "OP_HL_LHIP_U",
    "OP_HL_LHI_PO",
    "OP_HL_LHI_PR",
    "OP_HL_LHI_U",
    "OP_HL_LHI_UPO",
    "OP_HL_LHI_UPR",
    "OP_HL_LHP",
    "OP_HL_LHUI",
    "OP_HL_LHUIP",
    "OP_HL_LHUIP_U",
    "OP_HL_LHUI_PO",
    "OP_HL_LHUI_PR",
    "OP_HL_LHUI_U",
    "OP_HL_LHUI_UPO",
    "OP_HL_LHUI_UPR",
    "OP_HL_LHUP",
    "OP_HL_LHU_PO",
    "OP_HL_LHU_PR",
    "OP_HL_LH_PO",
    "OP_HL_LH_PR",
    "OP_HL_LIS",
    "OP_HL_LIU",
    "OP_HL_LUI",
    "OP_HL_LWI",
    "OP_HL_LWIP",
    "OP_HL_LWIP_U",
    "OP_HL_LWI_PO",
    "OP_HL_LWI_PR",
    "OP_HL_LWI_U",
    "OP_HL_LWI_UPO",
    "OP_HL_LWI_UPR",
    "OP_HL_LWP",
    "OP_HL_LWUI",
    "OP_HL_LWUIP",
    "OP_HL_LWUIP_U",
    "OP_HL_LWUI_PO",
    "OP_HL_LWUI_PR",
    "OP_HL_LWUI_U",
    "OP_HL_LWUI_UPO",
    "OP_HL_LWUI_UPR",
    "OP_HL_LWUP",
    "OP_HL_LWU_PO",
    "OP_HL_LWU_PR",
    "OP_HL_LW_PO",
    "OP_HL_LW_PR",
    "OP_HL_MIADD",
    "OP_HL_MISUB",
    "OP_HL_ORI",
    "OP_HL_ORIW",
    "OP_HL_PRF",
    "OP_HL_PRFI_U",
    "OP_HL_PRFI_UA",
    "OP_HL_PRF_A",
    "OP_HL_QMT",
    "OP_HL_QPOP",
    "OP_HL_QPUSH",
    "OP_HL_SBI",
    "OP_HL_SBIP",
    "OP_HL_SBI_PO",
    "OP_HL_SBI_PR",
    "OP_HL_SBP",
    "OP_HL_SB_PO",
    "OP_HL_SB_PR",
    "OP_HL_SDI",
    "OP_HL_SDIP",
    "OP_HL_SDIP_U",
    "OP_HL_SDI_PO",
    "OP_HL_SDI_PR",
    "OP_HL_SDI_U",
    "OP_HL_SDI_UPO",
    "OP_HL_SDI_UPR",
    "OP_HL_SDP",
    "OP_HL_SDP_U",
    "OP_HL_SD_PO",
    "OP_HL_SD_PR",
    "OP_HL_SD_UPO",
    "OP_HL_SD_UPR",
    "OP_HL_SETC_EQI",
    "OP_HL_SETC_GEI",
    "OP_HL_SETC_GEUI",
    "OP_HL_SETC_LTI",
    "OP_HL_SETC_LTUI",
    "OP_HL_SETC_NEI",
    "OP_HL_SETRET",
    "OP_HL_SHI",
    "OP_HL_SHIP",
    "OP_HL_SHIP_U",
    "OP_HL_SHI_PO",
    "OP_HL_SHI_PR",
    "OP_HL_SHI_U",
    "OP_HL_SHI_UPO",
    "OP_HL_SHI_UPR",
    "OP_HL_SHP",
    "OP_HL_SHP_U",
    "OP_HL_SH_PO",
    "OP_HL_SH_PR",
    "OP_HL_SH_UPO",
    "OP_HL_SH_UPR",
    "OP_HL_SUBI",
    "OP_HL_SUBIW",
    "OP_HL_SWI",
    "OP_HL_SWIP",
    "OP_HL_SWIP_U",
    "OP_HL_SWI_PO",
    "OP_HL_SWI_PR",
    "OP_HL_SWI_U",
    "OP_HL_SWI_UPO",
    "OP_HL_SWI_UPR",
    "OP_HL_SWP",
    "OP_HL_SWP_U",
    "OP_HL_SW_PO",
    "OP_HL_SW_PR",
    "OP_HL_SW_UPO",
    "OP_HL_SW_UPR",
    "OP_HL_XORI",
    "OP_HL_XORIW",
    "OP_LUI",
    "OP_MUL",
    "OP_MULU",
    "OP_MULUW",
    "OP_MULW",
    "OP_OR",
    "OP_ORI",
    "OP_ORIW",
    "OP_ORW",
    "OP_REM",
    "OP_REMU",
    "OP_REMUW",
    "OP_REMW",
    "OP_SLL",
    "OP_SLLI",
    "OP_SLLIW",
    "OP_SLLW",
    "OP_SRA",
    "OP_SRAI",
    "OP_SRAIW",
    "OP_SRAW",
    "OP_SRL",
    "OP_SRLI",
    "OP_SRLIW",
    "OP_SRLW",
    "OP_SUB",
    "OP_SUBI",
    "OP_SUBIW",
    "OP_SUBW",
    "OP_XOR",
    "OP_XORI",
    "OP_XORIW",
    "OP_XORW",
    "OP_ADDTPC",
    "OP_B_NZ",
    "OP_B_Z",
    "OP_CMP_AND",
    "OP_CMP_ANDI",
    "OP_CMP_EQ",
    "OP_CMP_EQI",
    "OP_CMP_GE",
    "OP_CMP_GEI",
    "OP_CMP_GEU",
    "OP_CMP_GEUI",
    "OP_CMP_LT",
    "OP_CMP_LTI",
    "OP_CMP_LTU",
    "OP_CMP_LTUI",
    "OP_CMP_NE",
    "OP_CMP_NEI",
    "OP_CMP_OR",
    "OP_CMP_ORI",
    "OP_C_CMP_EQI",
    "OP_C_CMP_NEI",
    "OP_C_SETC_EQ",
    "OP_C_SETC_NE",
    "OP_C_SETC_TGT",
    "OP_HL_ADDTPC",
    "OP_SETC_AND",
    "OP_SETC_ANDI",
    "OP_SETC_EQ",
    "OP_SETC_EQI",
    "OP_SETC_GE",
    "OP_SETC_GEI",
    "OP_SETC_GEU",
    "OP_SETC_GEUI",
    "OP_SETC_LT",
    "OP_SETC_LTI",
    "OP_SETC_LTU",
    "OP_SETC_LTUI",
    "OP_SETC_NE",
    "OP_SETC_NEI",
    "OP_SETC_OR",
    "OP_SETC_ORI",
    "OP_SETC_TGT",
    "OP_SETRET",
    "OP_LB",
    "OP_LBI",
    "OP_LBU",
    "OP_LBUI",
    "OP_LBU_PCR",
    "OP_LB_PCR",
    "OP_LD",
    "OP_LDI",
    "OP_LDI_U",
    "OP_LD_ADD",
    "OP_LD_AND",
    "OP_LD_OR",
    "OP_LD_PCR",
    "OP_LD_SMAX",
    "OP_LD_SMIN",
    "OP_LD_UMAX",
    "OP_LD_UMIN",
    "OP_LD_XOR",
    "OP_LH",
    "OP_LHI",
    "OP_LHI_U",
    "OP_LHU",
    "OP_LHUI",
    "OP_LHUI_U",
    "OP_LHU_PCR",
    "OP_LH_PCR",
    "OP_LW",
    "OP_LWI",
    "OP_LWI_U",
    "OP_LWU",
    "OP_LWUI",
    "OP_LWUI_U",
    "OP_LWU_PCR",
    "OP_LW_ADD",
    "OP_LW_AND",
    "OP_LW_OR",
    "OP_LW_PCR",
    "OP_LW_SMAX",
    "OP_LW_SMIN",
    "OP_LW_UMAX",
    "OP_LW_UMIN",
    "OP_LW_XOR",
    "OP_SB",
    "OP_SBI",
    "OP_SB_PCR",
    "OP_SD",
    "OP_SDI",
    "OP_SDI_U",
    "OP_SD_ADD",
    "OP_SD_AND",
    "OP_SD_OR",
    "OP_SD_PCR",
    "OP_SD_SMAX",
    "OP_SD_SMIN",
    "OP_SD_U",
    "OP_SD_UMAX",
    "OP_SD_UMIN",
    "OP_SD_XOR",
    "OP_SH",
    "OP_SHI",
    "OP_SHI_U",
    "OP_SH_PCR",
    "OP_SH_U",
    "OP_SW",
    "OP_SWAPB",
    "OP_SWAPD",
    "OP_SWAPH",
    "OP_SWAPW",
    "OP_SWI",
    "OP_SWI_U",
    "OP_SW_ADD",
    "OP_SW_AND",
    "OP_SW_OR",
    "OP_SW_PCR",
    "OP_SW_SMAX",
    "OP_SW_SMIN",
    "OP_SW_U",
    "OP_SW_UMAX",
    "OP_SW_UMIN",
    "OP_SW_XOR",
    "OP_BIOR",
    "OP_BLOAD",
    "OP_BSTORE",
    "OP_BTEXT",
    "OP_ERCOV",
    "OP_ESAVE",
    "OP_FENTRY",
    "OP_FEXIT",
    "OP_FRET_RA",
    "OP_FRET_STK",
    "OP_MCOPY",
    "OP_MSET",
    "OP_HL_LBU_PCR",
    "OP_HL_LB_PCR",
    "OP_HL_LD_PCR",
    "OP_HL_LHU_PCR",
    "OP_HL_LH_PCR",
    "OP_HL_LWU_PCR",
    "OP_HL_LW_PCR",
    "OP_HL_SB_PCR",
    "OP_HL_SD_PCR",
    "OP_HL_SH_PCR",
    "OP_HL_SW_PCR",
    "OP_V_ADD",
    "OP_V_CMP_EQ",
    "OP_V_CMP_GE",
    "OP_V_CMP_GEU",
    "OP_V_CMP_LT",
    "OP_V_CMP_LTU",
    "OP_V_CMP_NE",
    "OP_V_CSEL",
    "OP_V_FABS",
    "OP_V_FADD",
    "OP_V_FDIV",
    "OP_V_FEQ",
    "OP_V_FGE",
    "OP_V_FLT",
    "OP_V_FMUL",
    "OP_V_FNE",
    "OP_V_FSUB",
    "OP_V_LW",
    "OP_V_LW_BRG",
    "OP_V_MUL",
    "OP_V_RDADD",
    "OP_V_RDAND",
    "OP_V_RDFADD",
    "OP_V_RDFMAX",
    "OP_V_RDFMIN",
    "OP_V_RDMAX",
    "OP_V_RDMIN",
    "OP_V_RDOR",
    "OP_V_RDXOR",
    "OP_V_SUB",
    "OP_V_SW",
    "OP_V_SW_BRG",
    "OP_ACRC",
    "OP_ACRE",
    "OP_EBREAK",
    "OP_FABS",
    "OP_FADD",
    "OP_FCVT",
    "OP_FCVTZ",
    "OP_FDIV",
    "OP_FEQ",
    "OP_FGE",
    "OP_FLT",
    "OP_FMUL",
    "OP_FSUB",
    "OP_HL_SSRGET",
    "OP_HL_SSRSET",
    "OP_SSRGET",
    "OP_SSRSET",
    "OP_SSRSWAP",
    "OP_C_ADD",
    "OP_C_ADDI",
    "OP_C_AND",
    "OP_C_B_DIM",
    "OP_C_B_DIMI",
    "OP_C_EBREAK",
    "OP_C_LDI",
    "OP_C_LWI",
    "OP_C_MOVI",
    "OP_C_MOVR",
    "OP_C_OR",
    "OP_C_SDI",
    "OP_C_SEXT_B",
    "OP_C_SEXT_H",
    "OP_C_SEXT_W",
    "OP_C_SLLI",
    "OP_C_SRLI",
    "OP_C_SSRGET",
    "OP_C_SUB",
    "OP_C_SWI",
    "OP_C_ZEXT_B",
    "OP_C_ZEXT_H",
    "OP_C_ZEXT_W",
    "OP_ASSERT",
    "OP_BC_IALL",
    "OP_BC_IVA",
    "OP_BSE",
    "OP_BSTOP",
    "OP_BWE",
    "OP_BWI",
    "OP_BWT",
    "OP_C_BSTART_STD",
    "OP_C_SETRET",
    "OP_DC_CISW",
    "OP_DC_CIVA",
    "OP_DC_CSW",
    "OP_DC_CVA",
    "OP_DC_IALL",
    "OP_DC_ISW",
    "OP_DC_IVA",
    "OP_DC_ZVA",
    "OP_FENCE_D",
    "OP_FENCE_I",
    "OP_IC_IALL",
    "OP_IC_IVA",
    "OP_J",
    "OP_JR",
    "OP_LR_B",
    "OP_LR_D",
    "OP_LR_H",
    "OP_LR_W",
    "OP_LSRGET",
    "OP_MADD",
    "OP_MADDW",
    "OP_MAX",
    "OP_MAXU",
    "OP_MIN",
    "OP_MINU",
    "OP_PRF",
    "OP_PRFI_U",
    "OP_REV",
    "OP_SCVTF",
    "OP_SC_B",
    "OP_SC_D",
    "OP_SC_H",
    "OP_SC_W",
    "OP_TLB_IA",
    "OP_TLB_IALL",
    "OP_TLB_IAV",
    "OP_TLB_IV",
    "OP_UCVTF",
]
