from __future__ import annotations

# AUTO-GENERATED FILE. DO NOT EDIT.

OP_INVALID = 0
OP_BSTART_CUBE = 1
OP_BSTART_FIXP = 2
OP_BSTART_FP_CALL = 3
OP_BSTART_FP_COND = 4
OP_BSTART_FP_DIRECT = 5
OP_BSTART_FP_FALL = 6
OP_BSTART_FP_ICALL = 7
OP_BSTART_FP_IND = 8
OP_BSTART_FP_RET = 9
OP_BSTART_ICALL = 10
OP_BSTART_IND = 11
OP_BSTART_MPAR = 12
OP_BSTART_MSEQ = 13
OP_BSTART_RET = 14
OP_BSTART_STD_CALL = 15
OP_BSTART_STD_COND = 16
OP_BSTART_STD_DIRECT = 17
OP_BSTART_SYS = 18
OP_BSTART_TEPL = 19
OP_BSTART_TMA = 20
OP_BSTART_VPAR = 21
OP_BSTART_VSEQ = 22
OP_C_BSTART_COND = 23
OP_C_BSTART_DIRECT = 24
OP_C_BSTART_FP = 25
OP_C_BSTART_MPAR = 26
OP_C_BSTART_MSEQ = 27
OP_C_BSTART_STD_CALL = 28
OP_C_BSTART_STD_COND = 29
OP_C_BSTART_STD_DIRECT = 30
OP_C_BSTART_STD_FALL = 31
OP_C_BSTART_STD_ICALL = 32
OP_C_BSTART_STD_IND = 33
OP_C_BSTART_STD_RET = 34
OP_C_BSTART_SYS = 35
OP_C_BSTART_VPAR = 36
OP_C_BSTART_VSEQ = 37
OP_C_BSTOP = 38
OP_B_ARG = 39
OP_B_ATTR = 40
OP_B_DIM_LB0 = 41
OP_B_DIM_LB1 = 42
OP_B_DIM_LB2 = 43
OP_B_EQ = 44
OP_B_GE = 45
OP_B_GEU = 46
OP_B_HINT = 47
OP_B_HINT_TRACE = 48
OP_B_IOD = 49
OP_B_LT = 50
OP_B_LTU = 51
OP_B_NE = 52
OP_ADD = 53
OP_ADDI = 54
OP_ADDIW = 55
OP_ADDW = 56
OP_AND = 57
OP_ANDI = 58
OP_ANDIW = 59
OP_ANDW = 60
OP_BCNT = 61
OP_BIC = 62
OP_BIS = 63
OP_BSTART_STD_FALL = 64
OP_BXS = 65
OP_BXU = 66
OP_CLZ = 67
OP_CSEL = 68
OP_CTZ = 69
OP_DIV = 70
OP_DIVU = 71
OP_DIVUW = 72
OP_DIVW = 73
OP_HL_ADDI = 74
OP_HL_ADDIW = 75
OP_HL_ANDI = 76
OP_HL_ANDIW = 77
OP_HL_BSTART_FP_CALL = 78
OP_HL_BSTART_FP_COND = 79
OP_HL_BSTART_FP_DIRECT = 80
OP_HL_BSTART_FP_FALL = 81
OP_HL_BSTART_SYS = 82
OP_HL_CMP_ANDI = 83
OP_HL_CMP_EQI = 84
OP_HL_CMP_GEI = 85
OP_HL_CMP_GEUI = 86
OP_HL_CMP_LTI = 87
OP_HL_CMP_LTUI = 88
OP_HL_CMP_NEI = 89
OP_HL_CMP_ORI = 90
OP_HL_LBI = 91
OP_HL_LBIP = 92
OP_HL_LBI_PO = 93
OP_HL_LBI_PR = 94
OP_HL_LBP = 95
OP_HL_LBUI = 96
OP_HL_LBUIP = 97
OP_HL_LBUI_PO = 98
OP_HL_LBUI_PR = 99
OP_HL_LBUP = 100
OP_HL_LBU_PO = 101
OP_HL_LBU_PR = 102
OP_HL_LB_PO = 103
OP_HL_LB_PR = 104
OP_HL_LDI = 105
OP_HL_LDIP = 106
OP_HL_LDIP_U = 107
OP_HL_LDI_PO = 108
OP_HL_LDI_PR = 109
OP_HL_LDI_U = 110
OP_HL_LDI_UPO = 111
OP_HL_LDI_UPR = 112
OP_HL_LDP = 113
OP_HL_LD_PO = 114
OP_HL_LD_PR = 115
OP_HL_LHI = 116
OP_HL_LHIP = 117
OP_HL_LHIP_U = 118
OP_HL_LHI_PO = 119
OP_HL_LHI_PR = 120
OP_HL_LHI_U = 121
OP_HL_LHI_UPO = 122
OP_HL_LHI_UPR = 123
OP_HL_LHP = 124
OP_HL_LHUI = 125
OP_HL_LHUIP = 126
OP_HL_LHUIP_U = 127
OP_HL_LHUI_PO = 128
OP_HL_LHUI_PR = 129
OP_HL_LHUI_U = 130
OP_HL_LHUI_UPO = 131
OP_HL_LHUI_UPR = 132
OP_HL_LHUP = 133
OP_HL_LHU_PO = 134
OP_HL_LHU_PR = 135
OP_HL_LH_PO = 136
OP_HL_LH_PR = 137
OP_HL_LUI = 138
OP_HL_LWI = 139
OP_HL_LWIP = 140
OP_HL_LWIP_U = 141
OP_HL_LWI_PO = 142
OP_HL_LWI_PR = 143
OP_HL_LWI_U = 144
OP_HL_LWI_UPO = 145
OP_HL_LWI_UPR = 146
OP_HL_LWP = 147
OP_HL_LWUI = 148
OP_HL_LWUIP = 149
OP_HL_LWUIP_U = 150
OP_HL_LWUI_PO = 151
OP_HL_LWUI_PR = 152
OP_HL_LWUI_U = 153
OP_HL_LWUI_UPO = 154
OP_HL_LWUI_UPR = 155
OP_HL_LWUP = 156
OP_HL_LWU_PO = 157
OP_HL_LWU_PR = 158
OP_HL_LW_PO = 159
OP_HL_LW_PR = 160
OP_HL_ORI = 161
OP_HL_ORIW = 162
OP_HL_SBI = 163
OP_HL_SBIP = 164
OP_HL_SBI_PO = 165
OP_HL_SBI_PR = 166
OP_HL_SBP = 167
OP_HL_SB_PO = 168
OP_HL_SB_PR = 169
OP_HL_SDI = 170
OP_HL_SDIP = 171
OP_HL_SDIP_U = 172
OP_HL_SDI_PO = 173
OP_HL_SDI_PR = 174
OP_HL_SDI_U = 175
OP_HL_SDI_UPO = 176
OP_HL_SDI_UPR = 177
OP_HL_SDP = 178
OP_HL_SDP_U = 179
OP_HL_SD_PO = 180
OP_HL_SD_PR = 181
OP_HL_SD_UPO = 182
OP_HL_SD_UPR = 183
OP_HL_SHI = 184
OP_HL_SHIP = 185
OP_HL_SHIP_U = 186
OP_HL_SHI_PO = 187
OP_HL_SHI_PR = 188
OP_HL_SHI_U = 189
OP_HL_SHI_UPO = 190
OP_HL_SHI_UPR = 191
OP_HL_SHP = 192
OP_HL_SHP_U = 193
OP_HL_SH_PO = 194
OP_HL_SH_PR = 195
OP_HL_SH_UPO = 196
OP_HL_SH_UPR = 197
OP_HL_SUBI = 198
OP_HL_SUBIW = 199
OP_HL_SWI = 200
OP_HL_SWIP = 201
OP_HL_SWIP_U = 202
OP_HL_SWI_PO = 203
OP_HL_SWI_PR = 204
OP_HL_SWI_U = 205
OP_HL_SWI_UPO = 206
OP_HL_SWI_UPR = 207
OP_HL_SWP = 208
OP_HL_SWP_U = 209
OP_HL_SW_PO = 210
OP_HL_SW_PR = 211
OP_HL_SW_UPO = 212
OP_HL_SW_UPR = 213
OP_HL_XORI = 214
OP_HL_XORIW = 215
OP_LUI = 216
OP_MUL = 217
OP_MULU = 218
OP_MULUW = 219
OP_MULW = 220
OP_OR = 221
OP_ORI = 222
OP_ORIW = 223
OP_ORW = 224
OP_REM = 225
OP_REMU = 226
OP_REMUW = 227
OP_REMW = 228
OP_SLL = 229
OP_SLLI = 230
OP_SLLIW = 231
OP_SLLW = 232
OP_SRA = 233
OP_SRAI = 234
OP_SRAIW = 235
OP_SRAW = 236
OP_SRL = 237
OP_SRLI = 238
OP_SRLIW = 239
OP_SRLW = 240
OP_SUB = 241
OP_SUBI = 242
OP_SUBIW = 243
OP_SUBW = 244
OP_XOR = 245
OP_XORI = 246
OP_XORIW = 247
OP_XORW = 248
OP_ADDTPC = 249
OP_B_NZ = 250
OP_B_Z = 251
OP_CMP_AND = 252
OP_CMP_ANDI = 253
OP_CMP_EQ = 254
OP_CMP_EQI = 255
OP_CMP_GE = 256
OP_CMP_GEI = 257
OP_CMP_GEU = 258
OP_CMP_GEUI = 259
OP_CMP_LT = 260
OP_CMP_LTI = 261
OP_CMP_LTU = 262
OP_CMP_LTUI = 263
OP_CMP_NE = 264
OP_CMP_NEI = 265
OP_CMP_OR = 266
OP_CMP_ORI = 267
OP_C_CMP_EQI = 268
OP_C_CMP_NEI = 269
OP_C_SETC_EQ = 270
OP_C_SETC_NE = 271
OP_C_SETC_TGT = 272
OP_HL_ADDTPC = 273
OP_SETC_AND = 274
OP_SETC_ANDI = 275
OP_SETC_EQ = 276
OP_SETC_EQI = 277
OP_SETC_GE = 278
OP_SETC_GEI = 279
OP_SETC_GEU = 280
OP_SETC_GEUI = 281
OP_SETC_LT = 282
OP_SETC_LTI = 283
OP_SETC_LTU = 284
OP_SETC_LTUI = 285
OP_SETC_NE = 286
OP_SETC_NEI = 287
OP_SETC_OR = 288
OP_SETC_ORI = 289
OP_SETC_TGT = 290
OP_SETRET = 291
OP_LB = 292
OP_LBI = 293
OP_LBU = 294
OP_LBUI = 295
OP_LBU_PCR = 296
OP_LB_PCR = 297
OP_LD = 298
OP_LDI = 299
OP_LDI_U = 300
OP_LD_ADD = 301
OP_LD_AND = 302
OP_LD_OR = 303
OP_LD_PCR = 304
OP_LD_SMAX = 305
OP_LD_SMIN = 306
OP_LD_UMAX = 307
OP_LD_UMIN = 308
OP_LD_XOR = 309
OP_LH = 310
OP_LHI = 311
OP_LHI_U = 312
OP_LHU = 313
OP_LHUI = 314
OP_LHUI_U = 315
OP_LHU_PCR = 316
OP_LH_PCR = 317
OP_LW = 318
OP_LWI = 319
OP_LWI_U = 320
OP_LWU = 321
OP_LWUI = 322
OP_LWUI_U = 323
OP_LWU_PCR = 324
OP_LW_ADD = 325
OP_LW_AND = 326
OP_LW_OR = 327
OP_LW_PCR = 328
OP_LW_SMAX = 329
OP_LW_SMIN = 330
OP_LW_UMAX = 331
OP_LW_UMIN = 332
OP_LW_XOR = 333
OP_SB = 334
OP_SBI = 335
OP_SB_PCR = 336
OP_SD = 337
OP_SDI = 338
OP_SDI_U = 339
OP_SD_ADD = 340
OP_SD_AND = 341
OP_SD_OR = 342
OP_SD_PCR = 343
OP_SD_SMAX = 344
OP_SD_SMIN = 345
OP_SD_U = 346
OP_SD_UMAX = 347
OP_SD_UMIN = 348
OP_SD_XOR = 349
OP_SH = 350
OP_SHI = 351
OP_SHI_U = 352
OP_SH_PCR = 353
OP_SH_U = 354
OP_SW = 355
OP_SWAPB = 356
OP_SWAPD = 357
OP_SWAPH = 358
OP_SWAPW = 359
OP_SWI = 360
OP_SWI_U = 361
OP_SW_ADD = 362
OP_SW_AND = 363
OP_SW_OR = 364
OP_SW_PCR = 365
OP_SW_SMAX = 366
OP_SW_SMIN = 367
OP_SW_U = 368
OP_SW_UMAX = 369
OP_SW_UMIN = 370
OP_SW_XOR = 371
OP_BIOR = 372
OP_BLOAD = 373
OP_BSTORE = 374
OP_BTEXT = 375
OP_ERCOV = 376
OP_ESAVE = 377
OP_FENTRY = 378
OP_FEXIT = 379
OP_FRET_RA = 380
OP_FRET_STK = 381
OP_MCOPY = 382
OP_MSET = 383
OP_HL_LBU_PCR = 384
OP_HL_LB_PCR = 385
OP_HL_LD_PCR = 386
OP_HL_LHU_PCR = 387
OP_HL_LH_PCR = 388
OP_HL_LWU_PCR = 389
OP_HL_LW_PCR = 390
OP_HL_SB_PCR = 391
OP_HL_SD_PCR = 392
OP_HL_SH_PCR = 393
OP_HL_SW_PCR = 394
OP_V_ADD = 395
OP_V_CMP_EQ = 396
OP_V_CMP_GE = 397
OP_V_CMP_GEU = 398
OP_V_CMP_LT = 399
OP_V_CMP_LTU = 400
OP_V_CMP_NE = 401
OP_V_CSEL = 402
OP_V_FABS = 403
OP_V_FADD = 404
OP_V_FDIV = 405
OP_V_FEQ = 406
OP_V_FGE = 407
OP_V_FLT = 408
OP_V_FMUL = 409
OP_V_FNE = 410
OP_V_FSUB = 411
OP_V_LW = 412
OP_V_LW_BRG = 413
OP_V_MUL = 414
OP_V_RDADD = 415
OP_V_RDAND = 416
OP_V_RDFADD = 417
OP_V_RDFMAX = 418
OP_V_RDFMIN = 419
OP_V_RDMAX = 420
OP_V_RDMIN = 421
OP_V_RDOR = 422
OP_V_RDXOR = 423
OP_V_SUB = 424
OP_V_SW = 425
OP_V_SW_BRG = 426
OP_ACRC = 427
OP_ACRE = 428
OP_EBREAK = 429
OP_FABS = 430
OP_FADD = 431
OP_FCVT = 432
OP_FCVTZ = 433
OP_FDIV = 434
OP_FEQ = 435
OP_FGE = 436
OP_FLT = 437
OP_FMUL = 438
OP_FSUB = 439
OP_HL_SSRGET = 440
OP_HL_SSRSET = 441
OP_SSRGET = 442
OP_SSRSET = 443
OP_SSRSWAP = 444
OP_C_ADD = 445
OP_C_ADDI = 446
OP_C_AND = 447
OP_C_B_DIM = 448
OP_C_B_DIMI = 449
OP_C_EBREAK = 450
OP_C_LDI = 451
OP_C_LWI = 452
OP_C_MOVI = 453
OP_C_MOVR = 454
OP_C_OR = 455
OP_C_SDI = 456
OP_C_SEXT_B = 457
OP_C_SEXT_H = 458
OP_C_SEXT_W = 459
OP_C_SLLI = 460
OP_C_SRLI = 461
OP_C_SSRGET = 462
OP_C_SUB = 463
OP_C_SWI = 464
OP_C_ZEXT_B = 465
OP_C_ZEXT_H = 466
OP_C_ZEXT_W = 467
OP_ASSERT = 468
OP_BC_IALL = 469
OP_BC_IVA = 470
OP_BSE = 471
OP_BSTOP = 472
OP_BWE = 473
OP_BWI = 474
OP_BWT = 475
OP_C_BSTART_STD = 476
OP_C_SETRET = 477
OP_DC_CISW = 478
OP_DC_CIVA = 479
OP_DC_CSW = 480
OP_DC_CVA = 481
OP_DC_IALL = 482
OP_DC_ISW = 483
OP_DC_IVA = 484
OP_DC_ZVA = 485
OP_FENCE_D = 486
OP_FENCE_I = 487
OP_IC_IALL = 488
OP_IC_IVA = 489
OP_J = 491
OP_JR = 492
OP_LR_B = 493
OP_LR_D = 494
OP_LR_H = 495
OP_LR_W = 496
OP_LSRGET = 497
OP_MADD = 498
OP_MADDW = 499
OP_MAX = 500
OP_MAXU = 501
OP_MIN = 502
OP_MINU = 503
OP_PRF = 504
OP_PRFI_U = 505
OP_REV = 506
OP_SCVTF = 507
OP_SC_B = 508
OP_SC_D = 509
OP_SC_H = 510
OP_SC_W = 511
OP_TLB_IA = 512
OP_TLB_IALL = 513
OP_TLB_IAV = 514
OP_TLB_IV = 515
OP_UCVTF = 516

__all__ = [
    "OP_INVALID",
    "OP_BSTART_CUBE",
    "OP_BSTART_FIXP",
    "OP_BSTART_FP_CALL",
    "OP_BSTART_FP_COND",
    "OP_BSTART_FP_DIRECT",
    "OP_BSTART_FP_FALL",
    "OP_BSTART_FP_ICALL",
    "OP_BSTART_FP_IND",
    "OP_BSTART_FP_RET",
    "OP_BSTART_ICALL",
    "OP_BSTART_IND",
    "OP_BSTART_MPAR",
    "OP_BSTART_MSEQ",
    "OP_BSTART_RET",
    "OP_BSTART_STD_CALL",
    "OP_BSTART_STD_COND",
    "OP_BSTART_STD_DIRECT",
    "OP_BSTART_SYS",
    "OP_BSTART_TEPL",
    "OP_BSTART_TMA",
    "OP_BSTART_VPAR",
    "OP_BSTART_VSEQ",
    "OP_C_BSTART_COND",
    "OP_C_BSTART_DIRECT",
    "OP_C_BSTART_FP",
    "OP_C_BSTART_MPAR",
    "OP_C_BSTART_MSEQ",
    "OP_C_BSTART_STD_CALL",
    "OP_C_BSTART_STD_COND",
    "OP_C_BSTART_STD_DIRECT",
    "OP_C_BSTART_STD_FALL",
    "OP_C_BSTART_STD_ICALL",
    "OP_C_BSTART_STD_IND",
    "OP_C_BSTART_STD_RET",
    "OP_C_BSTART_SYS",
    "OP_C_BSTART_VPAR",
    "OP_C_BSTART_VSEQ",
    "OP_C_BSTOP",
    "OP_B_ARG",
    "OP_B_ATTR",
    "OP_B_DIM_LB0",
    "OP_B_DIM_LB1",
    "OP_B_DIM_LB2",
    "OP_B_EQ",
    "OP_B_GE",
    "OP_B_GEU",
    "OP_B_HINT",
    "OP_B_HINT_TRACE",
    "OP_B_IOD",
    "OP_B_LT",
    "OP_B_LTU",
    "OP_B_NE",
    "OP_ADD",
    "OP_ADDI",
    "OP_ADDIW",
    "OP_ADDW",
    "OP_AND",
    "OP_ANDI",
    "OP_ANDIW",
    "OP_ANDW",
    "OP_BCNT",
    "OP_BIC",
    "OP_BIS",
    "OP_BSTART_STD_FALL",
    "OP_BXS",
    "OP_BXU",
    "OP_CLZ",
    "OP_CSEL",
    "OP_CTZ",
    "OP_DIV",
    "OP_DIVU",
    "OP_DIVUW",
    "OP_DIVW",
    "OP_HL_ADDI",
    "OP_HL_ADDIW",
    "OP_HL_ANDI",
    "OP_HL_ANDIW",
    "OP_HL_BSTART_FP_CALL",
    "OP_HL_BSTART_FP_COND",
    "OP_HL_BSTART_FP_DIRECT",
    "OP_HL_BSTART_FP_FALL",
    "OP_HL_BSTART_SYS",
    "OP_HL_CMP_ANDI",
    "OP_HL_CMP_EQI",
    "OP_HL_CMP_GEI",
    "OP_HL_CMP_GEUI",
    "OP_HL_CMP_LTI",
    "OP_HL_CMP_LTUI",
    "OP_HL_CMP_NEI",
    "OP_HL_CMP_ORI",
    "OP_HL_LBI",
    "OP_HL_LBIP",
    "OP_HL_LBI_PO",
    "OP_HL_LBI_PR",
    "OP_HL_LBP",
    "OP_HL_LBUI",
    "OP_HL_LBUIP",
    "OP_HL_LBUI_PO",
    "OP_HL_LBUI_PR",
    "OP_HL_LBUP",
    "OP_HL_LBU_PO",
    "OP_HL_LBU_PR",
    "OP_HL_LB_PO",
    "OP_HL_LB_PR",
    "OP_HL_LDI",
    "OP_HL_LDIP",
    "OP_HL_LDIP_U",
    "OP_HL_LDI_PO",
    "OP_HL_LDI_PR",
    "OP_HL_LDI_U",
    "OP_HL_LDI_UPO",
    "OP_HL_LDI_UPR",
    "OP_HL_LDP",
    "OP_HL_LD_PO",
    "OP_HL_LD_PR",
    "OP_HL_LHI",
    "OP_HL_LHIP",
    "OP_HL_LHIP_U",
    "OP_HL_LHI_PO",
    "OP_HL_LHI_PR",
    "OP_HL_LHI_U",
    "OP_HL_LHI_UPO",
    "OP_HL_LHI_UPR",
    "OP_HL_LHP",
    "OP_HL_LHUI",
    "OP_HL_LHUIP",
    "OP_HL_LHUIP_U",
    "OP_HL_LHUI_PO",
    "OP_HL_LHUI_PR",
    "OP_HL_LHUI_U",
    "OP_HL_LHUI_UPO",
    "OP_HL_LHUI_UPR",
    "OP_HL_LHUP",
    "OP_HL_LHU_PO",
    "OP_HL_LHU_PR",
    "OP_HL_LH_PO",
    "OP_HL_LH_PR",
    "OP_HL_LUI",
    "OP_HL_LWI",
    "OP_HL_LWIP",
    "OP_HL_LWIP_U",
    "OP_HL_LWI_PO",
    "OP_HL_LWI_PR",
    "OP_HL_LWI_U",
    "OP_HL_LWI_UPO",
    "OP_HL_LWI_UPR",
    "OP_HL_LWP",
    "OP_HL_LWUI",
    "OP_HL_LWUIP",
    "OP_HL_LWUIP_U",
    "OP_HL_LWUI_PO",
    "OP_HL_LWUI_PR",
    "OP_HL_LWUI_U",
    "OP_HL_LWUI_UPO",
    "OP_HL_LWUI_UPR",
    "OP_HL_LWUP",
    "OP_HL_LWU_PO",
    "OP_HL_LWU_PR",
    "OP_HL_LW_PO",
    "OP_HL_LW_PR",
    "OP_HL_ORI",
    "OP_HL_ORIW",
    "OP_HL_SBI",
    "OP_HL_SBIP",
    "OP_HL_SBI_PO",
    "OP_HL_SBI_PR",
    "OP_HL_SBP",
    "OP_HL_SB_PO",
    "OP_HL_SB_PR",
    "OP_HL_SDI",
    "OP_HL_SDIP",
    "OP_HL_SDIP_U",
    "OP_HL_SDI_PO",
    "OP_HL_SDI_PR",
    "OP_HL_SDI_U",
    "OP_HL_SDI_UPO",
    "OP_HL_SDI_UPR",
    "OP_HL_SDP",
    "OP_HL_SDP_U",
    "OP_HL_SD_PO",
    "OP_HL_SD_PR",
    "OP_HL_SD_UPO",
    "OP_HL_SD_UPR",
    "OP_HL_SHI",
    "OP_HL_SHIP",
    "OP_HL_SHIP_U",
    "OP_HL_SHI_PO",
    "OP_HL_SHI_PR",
    "OP_HL_SHI_U",
    "OP_HL_SHI_UPO",
    "OP_HL_SHI_UPR",
    "OP_HL_SHP",
    "OP_HL_SHP_U",
    "OP_HL_SH_PO",
    "OP_HL_SH_PR",
    "OP_HL_SH_UPO",
    "OP_HL_SH_UPR",
    "OP_HL_SUBI",
    "OP_HL_SUBIW",
    "OP_HL_SWI",
    "OP_HL_SWIP",
    "OP_HL_SWIP_U",
    "OP_HL_SWI_PO",
    "OP_HL_SWI_PR",
    "OP_HL_SWI_U",
    "OP_HL_SWI_UPO",
    "OP_HL_SWI_UPR",
    "OP_HL_SWP",
    "OP_HL_SWP_U",
    "OP_HL_SW_PO",
    "OP_HL_SW_PR",
    "OP_HL_SW_UPO",
    "OP_HL_SW_UPR",
    "OP_HL_XORI",
    "OP_HL_XORIW",
    "OP_LUI",
    "OP_MUL",
    "OP_MULU",
    "OP_MULUW",
    "OP_MULW",
    "OP_OR",
    "OP_ORI",
    "OP_ORIW",
    "OP_ORW",
    "OP_REM",
    "OP_REMU",
    "OP_REMUW",
    "OP_REMW",
    "OP_SLL",
    "OP_SLLI",
    "OP_SLLIW",
    "OP_SLLW",
    "OP_SRA",
    "OP_SRAI",
    "OP_SRAIW",
    "OP_SRAW",
    "OP_SRL",
    "OP_SRLI",
    "OP_SRLIW",
    "OP_SRLW",
    "OP_SUB",
    "OP_SUBI",
    "OP_SUBIW",
    "OP_SUBW",
    "OP_XOR",
    "OP_XORI",
    "OP_XORIW",
    "OP_XORW",
    "OP_ADDTPC",
    "OP_B_NZ",
    "OP_B_Z",
    "OP_CMP_AND",
    "OP_CMP_ANDI",
    "OP_CMP_EQ",
    "OP_CMP_EQI",
    "OP_CMP_GE",
    "OP_CMP_GEI",
    "OP_CMP_GEU",
    "OP_CMP_GEUI",
    "OP_CMP_LT",
    "OP_CMP_LTI",
    "OP_CMP_LTU",
    "OP_CMP_LTUI",
    "OP_CMP_NE",
    "OP_CMP_NEI",
    "OP_CMP_OR",
    "OP_CMP_ORI",
    "OP_C_CMP_EQI",
    "OP_C_CMP_NEI",
    "OP_C_SETC_EQ",
    "OP_C_SETC_NE",
    "OP_C_SETC_TGT",
    "OP_HL_ADDTPC",
    "OP_SETC_AND",
    "OP_SETC_ANDI",
    "OP_SETC_EQ",
    "OP_SETC_EQI",
    "OP_SETC_GE",
    "OP_SETC_GEI",
    "OP_SETC_GEU",
    "OP_SETC_GEUI",
    "OP_SETC_LT",
    "OP_SETC_LTI",
    "OP_SETC_LTU",
    "OP_SETC_LTUI",
    "OP_SETC_NE",
    "OP_SETC_NEI",
    "OP_SETC_OR",
    "OP_SETC_ORI",
    "OP_SETC_TGT",
    "OP_SETRET",
    "OP_LB",
    "OP_LBI",
    "OP_LBU",
    "OP_LBUI",
    "OP_LBU_PCR",
    "OP_LB_PCR",
    "OP_LD",
    "OP_LDI",
    "OP_LDI_U",
    "OP_LD_ADD",
    "OP_LD_AND",
    "OP_LD_OR",
    "OP_LD_PCR",
    "OP_LD_SMAX",
    "OP_LD_SMIN",
    "OP_LD_UMAX",
    "OP_LD_UMIN",
    "OP_LD_XOR",
    "OP_LH",
    "OP_LHI",
    "OP_LHI_U",
    "OP_LHU",
    "OP_LHUI",
    "OP_LHUI_U",
    "OP_LHU_PCR",
    "OP_LH_PCR",
    "OP_LW",
    "OP_LWI",
    "OP_LWI_U",
    "OP_LWU",
    "OP_LWUI",
    "OP_LWUI_U",
    "OP_LWU_PCR",
    "OP_LW_ADD",
    "OP_LW_AND",
    "OP_LW_OR",
    "OP_LW_PCR",
    "OP_LW_SMAX",
    "OP_LW_SMIN",
    "OP_LW_UMAX",
    "OP_LW_UMIN",
    "OP_LW_XOR",
    "OP_SB",
    "OP_SBI",
    "OP_SB_PCR",
    "OP_SD",
    "OP_SDI",
    "OP_SDI_U",
    "OP_SD_ADD",
    "OP_SD_AND",
    "OP_SD_OR",
    "OP_SD_PCR",
    "OP_SD_SMAX",
    "OP_SD_SMIN",
    "OP_SD_U",
    "OP_SD_UMAX",
    "OP_SD_UMIN",
    "OP_SD_XOR",
    "OP_SH",
    "OP_SHI",
    "OP_SHI_U",
    "OP_SH_PCR",
    "OP_SH_U",
    "OP_SW",
    "OP_SWAPB",
    "OP_SWAPD",
    "OP_SWAPH",
    "OP_SWAPW",
    "OP_SWI",
    "OP_SWI_U",
    "OP_SW_ADD",
    "OP_SW_AND",
    "OP_SW_OR",
    "OP_SW_PCR",
    "OP_SW_SMAX",
    "OP_SW_SMIN",
    "OP_SW_U",
    "OP_SW_UMAX",
    "OP_SW_UMIN",
    "OP_SW_XOR",
    "OP_BIOR",
    "OP_BLOAD",
    "OP_BSTORE",
    "OP_BTEXT",
    "OP_ERCOV",
    "OP_ESAVE",
    "OP_FENTRY",
    "OP_FEXIT",
    "OP_FRET_RA",
    "OP_FRET_STK",
    "OP_MCOPY",
    "OP_MSET",
    "OP_HL_LBU_PCR",
    "OP_HL_LB_PCR",
    "OP_HL_LD_PCR",
    "OP_HL_LHU_PCR",
    "OP_HL_LH_PCR",
    "OP_HL_LWU_PCR",
    "OP_HL_LW_PCR",
    "OP_HL_SB_PCR",
    "OP_HL_SD_PCR",
    "OP_HL_SH_PCR",
    "OP_HL_SW_PCR",
    "OP_V_ADD",
    "OP_V_CMP_EQ",
    "OP_V_CMP_GE",
    "OP_V_CMP_GEU",
    "OP_V_CMP_LT",
    "OP_V_CMP_LTU",
    "OP_V_CMP_NE",
    "OP_V_CSEL",
    "OP_V_FABS",
    "OP_V_FADD",
    "OP_V_FDIV",
    "OP_V_FEQ",
    "OP_V_FGE",
    "OP_V_FLT",
    "OP_V_FMUL",
    "OP_V_FNE",
    "OP_V_FSUB",
    "OP_V_LW",
    "OP_V_LW_BRG",
    "OP_V_MUL",
    "OP_V_RDADD",
    "OP_V_RDAND",
    "OP_V_RDFADD",
    "OP_V_RDFMAX",
    "OP_V_RDFMIN",
    "OP_V_RDMAX",
    "OP_V_RDMIN",
    "OP_V_RDOR",
    "OP_V_RDXOR",
    "OP_V_SUB",
    "OP_V_SW",
    "OP_V_SW_BRG",
    "OP_ACRC",
    "OP_ACRE",
    "OP_EBREAK",
    "OP_FABS",
    "OP_FADD",
    "OP_FCVT",
    "OP_FCVTZ",
    "OP_FDIV",
    "OP_FEQ",
    "OP_FGE",
    "OP_FLT",
    "OP_FMUL",
    "OP_FSUB",
    "OP_HL_SSRGET",
    "OP_HL_SSRSET",
    "OP_SSRGET",
    "OP_SSRSET",
    "OP_SSRSWAP",
    "OP_C_ADD",
    "OP_C_ADDI",
    "OP_C_AND",
    "OP_C_B_DIM",
    "OP_C_B_DIMI",
    "OP_C_EBREAK",
    "OP_C_LDI",
    "OP_C_LWI",
    "OP_C_MOVI",
    "OP_C_MOVR",
    "OP_C_OR",
    "OP_C_SDI",
    "OP_C_SEXT_B",
    "OP_C_SEXT_H",
    "OP_C_SEXT_W",
    "OP_C_SLLI",
    "OP_C_SRLI",
    "OP_C_SSRGET",
    "OP_C_SUB",
    "OP_C_SWI",
    "OP_C_ZEXT_B",
    "OP_C_ZEXT_H",
    "OP_C_ZEXT_W",
    "OP_ASSERT",
    "OP_BC_IALL",
    "OP_BC_IVA",
    "OP_BSE",
    "OP_BSTOP",
    "OP_BWE",
    "OP_BWI",
    "OP_BWT",
    "OP_C_BSTART_STD",
    "OP_C_SETRET",
    "OP_DC_CISW",
    "OP_DC_CIVA",
    "OP_DC_CSW",
    "OP_DC_CVA",
    "OP_DC_IALL",
    "OP_DC_ISW",
    "OP_DC_IVA",
    "OP_DC_ZVA",
    "OP_FENCE_D",
    "OP_FENCE_I",
    "OP_IC_IALL",
    "OP_IC_IVA",
    "OP_J",
    "OP_JR",
    "OP_LR_B",
    "OP_LR_D",
    "OP_LR_H",
    "OP_LR_W",
    "OP_LSRGET",
    "OP_MADD",
    "OP_MADDW",
    "OP_MAX",
    "OP_MAXU",
    "OP_MIN",
    "OP_MINU",
    "OP_PRF",
    "OP_PRFI_U",
    "OP_REV",
    "OP_SCVTF",
    "OP_SC_B",
    "OP_SC_D",
    "OP_SC_H",
    "OP_SC_W",
    "OP_TLB_IA",
    "OP_TLB_IALL",
    "OP_TLB_IAV",
    "OP_TLB_IV",
    "OP_UCVTF",
]
