from __future__ import annotations

# Allowed stage postfix tokens for Janus/BCC naming lint.
STAGE_TOKENS = {
    "f0",
    "f1",
    "f2",
    "f3",
    "f4",
    "d1",
    "d2",
    "d3",
    "s1",
    "s2",
    "p1",
    "i1",
    "i2",
    "e1",
    "e2",
    "e3",
    "e4",
    "w1",
    "w2",
    "rob",
    "pcb",
    "fls",
    "renu",
    "bisq",
    "bctrl",
    "brenu",
    "brob",
    "liq",
    "lhq",
    "stq",
    "scb",
    "mdb",
    "l1d",
    "noc",
    "tmu",
    "tma",
    "cube",
    "vec",
    "tau",
    "top",
}

INTERFACE_PREFIXES = {
    "f0_to_f1_stage",
    "f1_to_f2_stage",
    "f2_to_f3_stage",
    "f3_to_f4_stage",
    "f3_to_pcb_stage",
    "f4_to_d1_stage",
    "d1_to_d2_stage",
    "d2_to_d3_stage",
    "d3_to_s1_stage",
    "s1_to_s2_stage",
    "s2_to_iex_stage",
    "iex_to_rob_stage",
    "rob_to_flush_ctrl_stage",
    "bctrl_to_pe_stage",
    "pe_to_brob_stage",
    "lsu_to_rob_stage",
    "pcb_to_bru_stage",
}
